### ISSUE TITLE
add allUsers to playlist_manager.py

### ISSUE THREAD

**Issue by zenjabba** [blacktwin/JBOPS#100]
This script is perfect for what I need, can you add your todo of adding allUsers as an option please

**Comment by reaperofpower** [comment]
Was thinking the same thing! Maybe like If libraries X,Y selected check for users shared and then add playlist for them?

**Comment by blacktwin** [comment]
updated. Check out the examples. [Contact me](https://github.com/blacktwin/JBOPS#contact) if you have any issues.
