### ISSUE TITLE
Kill stream if transcode is lower than 720p

### ISSUE THREAD

**Issue by MrTwIXx** [blacktwin/JBOPS#102]
Hey there,
I want to kill all streams which transcode in quality lower than 720p.

4K --> 1080p Don't kill
4K --> 720p   Don't kill
4K --> 480p Kill
4K --> SD Kill
1080p --> 720p Don't kill
1080p --> 480p Kill
1080p --> SD Kill
720p --> 480p Kill

Do you understand what I mean?

**Comment by blacktwin** [comment]
I understand. Use the conditions to achieve this. Something like [this](https://imgur.com/LwcH8Ge).

**Comment by MrTwIXx** [comment]
Thanks will try it. Is it possible to whitelist a user?

**Comment by blacktwin** [comment]
Use the conditions. Something like [this](https://imgur.com/LwcH8Ge).

**Comment by blacktwin** [comment]
Use the conditions. `Username | is not | MrTXIXx`

**Comment by MrTwIXx** [comment]
Thanks all works now :)
