### ISSUE TITLE
limiterr.py - Certain amount of Streams / Players per Day / Period

### ISSUE THREAD

**Issue by clovisd** [blacktwin/JBOPS#103]
Hey!

I'm wondering if its possible to use limiterr to limit both the amount of plays someone is allowed but also do that over a certain period. If this is not possible, could it be considered as a possible addition to the current script?

EDIT: How is this play data stored? I'm guessing limiterr reads the Tautulli database to figure out play count / duration etc? Maybe I can set a cron to delete / reset that data and then set limits that way?

Thank you,
C

**Comment by blacktwin** [comment]
I'm not sure I understand. Can you provide an example situation? Are you talked about having something like a weekly/monthly allowance of plays? 

> How is this play data stored? 

Tautulli's DB. The script uses Tautulli's API to get the data.

>  Maybe I can set a cron to delete / reset that data and then set limits that way?

I would not recommend touching the DB unless you know what you're doing. And even then, I'd recommend not touching it. Just need to adjust the search terms.

**Comment by ubun2Junky** [comment]
Blacktwin, I'm not sure if this is what clovisd means, but in my case, I'd like to be able to allow my kids to watch an hour of tv per day on the weekdays.  My settings are.

Condition:
  `{username} is Kids and {Current Weekday} is less than 6. ` 

Playback Start Argument:
`--jbop time --username {username} --sessionId {session_id}  --limit hours=1 --killMessage '{user}, you have met your limit of 1 hour.'`

This will allow my kids to watch one hour of tv between Monday and Friday.  Is there a way it can be set per day?

**Comment by blacktwin** [comment]
@ubun2Junky 
There is now a `--today` arg that will limit the history search to only today. See this [example](https://github.com/blacktwin/JBOPS/blob/master/killstream/limiterr_readme.md#limit-user-to-total-play-sessions-for-the-day).  

Adding `--today` to you to your arguments above would allow 1 hour a day during the week. Let me know how it works.

**Comment by ubun2Junky** [comment]
I tried the --today argument.  I'm getting the following error:
`Tautulli Notifiers :: Script error: 
    usage: limiterr.py [-h] --jbop {watch,plays,time,limit} --username USERNAME 
                                          --sessionId SESSIONID [--notify NOTIFY] [--limit LIMIT] 
                                          [--grandparent_rating_key GRANDPARENT_RATING_KEY] 
                                          [--delay DELAY] 
                                          [--killMessage KILLMESSAGE [KILLMESSAGE ...]] [--section] 
    limiterr.py: error: unrecognized arguments: --today`

**Comment by blacktwin** [comment]
@ubun2Junky you've downloaded the new version of the [script](https://github.com/blacktwin/JBOPS/blob/master/killstream/limiterr.py#L284-L286)?

**Comment by blacktwin** [comment]
@clovisd @ubun2Junky any updates?

**Comment by ubun2Junky** [comment]
blacktwin;
Sorry for taking long to get back!  I did a git pull and inserted the recommended --today argument and it seems to have done the trick for me!  I'm happy it works, my kids are not as impressed!  Thx for the awesome work, really appreciate it!

**Comment by skube** [comment]
I'm definitely using the latest version of the script, yet I seem to have the same issue:
```
limiterr.py: error: unrecognized arguments: --today
```

With the following arguments: 
```
--jbop time --username {username} --sessionId {session_id} --limit minutes=1 --killMessage "Whoa! {user}, you have met your limit for today!" --today
```
