### ISSUE TITLE
Error 404 library/metadata

### ISSUE THREAD

**Issue by reaperofpower** [blacktwin/JBOPS#104]
Not sure of this is related to plexapi or the playlist manager so figured I would posit it here also
 https://github.com/pkkid/python-plexapi/issues/309

**Comment by blacktwin** [comment]
What is that that rating_key for? Can you confirm that it actually exists? Does the script always fail on this rating_key? When creating any other Playlist type does it fail? Are you running the script on the local machine where Plex is installed? Is the plex.tv down? 

You haven't provided much information.

**Comment by reaperofpower** [comment]
Sorry for the lack of info, no idea what rating_key is. I can run the in history playlists and they work just fine, this one is the top 5 movies where it fails. It's on a local machine where Plex is installed and running

**Comment by blacktwin** [comment]
rating_key is the number that Plex uses to ID the show, season, episode, movie, artist, album, track, etc. Look up that rating_key either through Tautulli or Plex.

Tautulli: `http://TAUTULLI:PORT/info?rating_key=124822`

Plex: Go to the webUI and click a move or show. In the address bar replace the rating with 124822
example: `http://127.0.0.1:32400/web/index.html#!/server/SERVERID/details?key=%2Flibrary%2Fmetadata%2F124822`

**Comment by reaperofpower** [comment]
Ahh I think we found the problem!
![](https://i.imgur.com/EWtudI8.jpg)

**Comment by blacktwin** [comment]
Ok, what happened to that file/content?

**Comment by reaperofpower** [comment]
It was replaced with a different file causing it to generate new metadata

**Comment by blacktwin** [comment]
Clean trash? and run the script again and see what happens? Basically we need Plex to dump this rating_key.

**Comment by blacktwin** [comment]
Well yeah, thats why I wanted to know what was going on with your rating_key that threw an error. :)
