### ISSUE TITLE
[Feature] Playlist from Trakt Trending and/or Lists

### ISSUE THREAD

**Issue by reaperofpower** [blacktwin/JBOPS#105]
Call the Trakt API `IE: https://api.trakt.tv/lists/trending` and gather list of Movies/TV Shows and Create Playlist. 

Also maybe allow for Customer lists `IE https://api.trakt.tv/lists/2725050` This is the Halloween Movie list. Great for Holiday Playlists

**Comment by blacktwin** [comment]
Great! Thanks.

**Comment by blacktwin** [comment]
Checking out https://github.com/pbrink231/plex_top_playlists/blob/master/plex_playlist_update.py

**Comment by blacktwin** [comment]
I don't use Trakt and there are other projects that are similar and do use Trakt. I will likely not be working on this. Closing.
