### ISSUE TITLE
[Request] Random option in Playlist Manager

### ISSUE THREAD

**Issue by irodimus** [blacktwin/JBOPS#107]
I'm really digging the playlist_manager.py script as it helps me and others see movies and tv shows that have been watched by others in a period of time. One thing I've like the most is that it has allowed me to watch movies on my server I've forgotten about when they do manage to get watched by others. This has brought up this request in if there is a possibility of adding a random option with specified number of shows, episodes, or movies in a playlist. This can be set as a cron job to run the script at a specified time frame, which I do now for most popular shows and movies. Since this appears to use PlexAPI for server connection, the option can be there for the above as it has hooks for searching the server for specific arguments (please correct me if I'm wrong). My library is extensive and sometimes I just want to click on a movie and go instead of searching for something if i can help it.

Couple of bonus things if possible:

- Custom naming of playlist
- Creating playlist using categories
- Use a specific library (I think something like this is implemented already)

It's not totally big deal if this is not possible, but as is, this script is awesome in my book the way it currently is. Thanks for coding and sharing it!

**Comment by blacktwin** [comment]
- [ ] Random selection based on library

- [ ] Custom item limits

- [ ] Custom naming of playlist

- [ ] Playlist by genre, rating, unwatched, studio, network (shows), labels, collections, country, writer, director, etc.

Anything else?

**Comment by blacktwin** [comment]
random is now added as a selector `--jbop random`
