### ISSUE TITLE
Bad Request when files no longer found in Playlist Manager

### ISSUE THREAD

**Issue by irodimus** [blacktwin/JBOPS#108]
I had the playlist_manager script set to run every after 30 days in a cron job but during that time, files have moved or movie entries have been deleted. When I try to update the playlist, I get a Bad Request error like this:

```
plex-ht:Scripts administrator$ python playlist_manager.py --jbop mostPopularMovies --action add --self --days 30 --top 25
Creating playlist(s)...
Traceback (most recent call last):
  File "playlist_manager.py", line 454, in <module>
    create_playlist(title, keys_list, x['server'], x['user'])
  File "playlist_manager.py", line 292, in create_playlist
    obj = plex.fetchItem(key)
  File "/usr/local/lib/python2.7/site-packages/plexapi/base.py", line 136, in fetchItem
    for elem in self._server.query(ekey):
  File "/usr/local/lib/python2.7/site-packages/plexapi/server.py", line 348, in query
    raise BadRequest('(%s) %s; %s %s' % (response.status_code, codename, response.url, errtext))
plexapi.exceptions.BadRequest: (404) not_found; http://localhost:32400/library/metadata/911482 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
```
I'm hoping someone can verify if the file or entry no longer being there is what is causing this to occur. If it is, anyway to ignore and select another media file?

**Comment by blacktwin** [comment]
You've deleted/moved a file that Plex is still reporting exists but when trying to fetch the information about the moved file there is nothing. So you'll need to run Empty Trash on the library before running again. See #104

**Comment by blacktwin** [comment]
For to mention this issue in 0ce14ad. You'll at least get an explanation as to why something wasn't added to the playlist.

**Comment by irodimus** [comment]
Before I tried 0ce14ad, emptying the trash in Plex still gave the Bad Request error. After I applied 0ce14ad, I now got the explanation but no error and the playlist still finished creating so i'd say that resolved it.
