### ISSUE TITLE
limiterr.py - Notification

### ISSUE THREAD

**Issue by sbcrumb** [blacktwin/JBOPS#109]
This might be possible to already do and I am just missing it.
But I have a select set of people I am limiting to x plays a day. And I would love to know when that person reaches that IE pushover alert that they reached it and the script kicked them off. Is that possible?

**Comment by blacktwin** [comment]
Already possible. See this [example](https://github.com/blacktwin/JBOPS/blob/master/killstream/limiterr_readme.md#limit-user-to-total-playswatches-and-send-a-notification-to-agent-1).

`--notify` is the arguments you'd use followed by the agent ID number from Tautulli. The body of the notification contains the kill message.

**Comment by sbcrumb** [comment]
perfect I will give that a try. --notify 1 I am using cause that is what my pushover says next to it.
I had the stream setup to kill on plays. Just wanted to be notified of those trying to break that limit. and when it was hit so this should work.
