### ISSUE TITLE
Multiple Most Popular Movies lists updating issue

### ISSUE THREAD

**Issue by irodimus** [blacktwin/JBOPS#110]
So I made two Most Popular Movies lists, one 7 days and one 30 days. I have cron jobs to run each of them after a specified time running the update action. Assuming both playlist have been added and showing in my Playlist section in Plex, when the 30 days one runs, it just updates the 30 days by deleting the old playlist and crating a new 30 days playlist. 
```
plex-ht:Scripts administrator$ python playlist_manager.py --jbop mostPopularMovies --action add --self --days 7 --top 25
Creating playlist(s)...
...Added Most Popular Movies (7 days) playlist to 'admin'.
Done.
```
Now, if the 7 days runs, both the 7 days and 30 days playlist are deleted and a new 7 days playlist is created.
```
plex-ht:Scripts administrator$ python playlist_manager.py --jbop mostPopularMovies --action update --self --days 7 --top 25
Deleting the playlist(s)...
...Deleted Most Popular Movies (7 days) for 'admin'.
...Deleted Most Popular Movies (30 days) for 'admin'.
Creating playlist(s)...
...Added Most Popular Movies (7 days) playlist to 'admin'.
Done.
```
Edit: I messed with it a little more and it seems like maybe only one Most Popular Movies list is allowed as they all get deleted when updating. Tried it again updating the 30 day list and it also deleted the 7 day one. From the looks of it, the update action logic deletes all Most Popular Movies lists ignoring the (x days).

**Comment by blacktwin** [comment]
Yup. Sounds about right. For updating it looks for the [common titles for the playlist](https://github.com/blacktwin/JBOPS/blob/master/fun/playlist_manager.py#L329-L344)s deletes it then creates a new playlist. Should probably just extend the search to the exact title.

**Comment by blacktwin** [comment]
Ok. 29ad54f should fix your issue. When selecting playlists to delete, it will use the entire name.

`playlist_manager.py --jbop mostPopularMovies --action remove --user Blacktwin --days 15`
This will remove the 'Most Popular Movies (15 days)' playlist(s).

`playlist_manager.py --jbop mostPopularMovies --action update --user Blacktwin`
This will remove and create a new 'Most Popular Movies (30 days)' playlist(s). 30 being the default value for `--days`.

Can you confirm that this resolves your issue?

**Comment by irodimus** [comment]
Applying 29ad54f fixes it. Thanks!
