### ISSUE TITLE
Syntax error when trying to run kill_stream.py

### ISSUE THREAD

**Issue by gmaster12** [blacktwin/JBOPS#115]
Im running Python 2.7 on Ubuntu 16.04 with Tautulli 2.1.25.

Trying to use the script per the example to kill any streams paused after 5 mins. I get a syntax error though. Any assistance would be appreciated.

2018-11-13 03:46:43 | INFO | Tautulli Notifiers :: Script notification sent.
-- | -- | --
2018-11-13 03:46:43 | ERROR | Tautulli Notifiers :: Script error:         File "/config/kill_stream.py", line 7             <!DOCTYPE html>             ^     SyntaxError: invalid syntax
2018-11-13 03:46:43 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.
2018-11-13 03:46:43 | DEBUG | Tautulli Notifiers :: Full script is: ['python', u'/config/kill_stream.py', '--jbop', 'paused', '--interval', '15', '--limit', '300', '--sessionId', '5mem38zkiidoo8vn6kiz1snu', '--killMessage', 'Your stream was paused for over 5 minutes and has been automatically stopped for you.']

**Comment by blacktwin** [comment]
Have you modified the script?

**Comment by gmaster12** [comment]
No modifications, I did a straight wget from here right into the target dir. I'll post a copy of the first page of the script. There are 6 spaces before the first line so it errors on <!DOCTYPE html>








<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">



  <link crossorigin="anonymous" media="all" integrity="sha512-wTTqmxYgVetC9399S4yH2TVoV8rVTOV7yHAWKhn0L+ya2eHNLiao7GuMGRx9iBEu83NpKtJibZrlMyYDYXYC0Q==" rel="stylesheet" href="https://assets-cdn.github.com/assets/frameworks-dd10d63b72c3bc4$
  <link crossorigin="anonymous" media="all" integrity="sha512-kFfNRgIn1u64ZXJCJuapQrT+swDqJCZyDE8FyycxOkQwpRuzlK6arRw/Pr0VqffhmPLao0XQoV/ym85wD4hq6A==" rel="stylesheet" href="https://assets-cdn.github.com/assets/github-c7ab4bcd2bbc288bc8d$


  <link crossorigin="anonymous" media="all" integrity="sha512-QbxBZqAu/zl5DDhd2QizVMJEVzg31c5Mlqi5uPXG9U7GQFnAk64qWU/ngS64iYhFycI93jHr5hLoAIWvTswe4w==" rel="stylesheet" href="https://assets-cdn.github.com/assets/site-d5d073510fa15e2c00f1b$



  <meta name="viewport" content="width=device-width">

  <title>JBOPS/kill_stream.py at master · blacktwin/JBOPS · GitHub</title>
    <meta name="description" content="Just a Bunch Of Plex Scripts. Contribute to blacktwin/JBOPS development by creating an account on GitHub.">
    <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="GitHub">
  <link rel="fluid-icon" href="https://github.com/fluidicon.png" title="GitHub">
  <meta property="fb:app_id" content="1401488693436528">


    <meta property="og:image" content="https://avatars2.githubusercontent.com/u/22177672?s=400&amp;v=4" /><meta property="og:site_name" content="GitHub" /><meta property="og:type" content="object" /><meta property="og:title" content="blac$

  <link rel="assets" href="https://assets-cdn.github.com/">

  <meta name="pjax-timeout" content="1000">

  <meta name="request-id" content="8DB6:6984:2F07DB3:5516EFD:5BEA3326" data-pjax-transient>




  <meta name="selected-link" value="repo_source" data-pjax-transient>

      <meta name="google-site-verification" content="KT5gs8h0wvaagLKAVWq8bbeNwnZZK1r1XQysX3xurLU">
    <meta name="google-site-verification" content="ZzhVyEFwb7w3e0-uOTltm8Jsck2F5StVihD0exw2fsA">
    <meta name="google-site-verification" content="GXs5KoUUkNCoaAZn7wPN-t01Pywp9M3sEjnt_3_ZWPc">

  <meta name="octolytics-host" content="collector.githubapp.com" /><meta name="octolytics-app-id" content="github" /><meta name="octolytics-event-url" content="https://collector.githubapp.com/github-external/browser_event" /><meta name="o$
<meta name="analytics-location" content="/&lt;user-name&gt;/&lt;repo-name&gt;/blob/show" data-pjax-transient="true" />



    <meta name="google-analytics" content="UA-3769691-2">


<meta class="js-ga-set" name="dimension1" content="Logged Out">

**Comment by gmaster12** [comment]
![image](https://user-images.githubusercontent.com/32989867/48418641-689c3100-e71b-11e8-87d0-d3017a08dfbb.png)

**Comment by blacktwin** [comment]
Not sure how you'd wget to n pull the script but it looks you've pulled the html page for the script not the script.

**Comment by gmaster12** [comment]
That explains it then:) I thought I could just wget https://github.com/blacktwin/JBOPS/blob/master/killstream/kill_stream.py . I'm sure once I get the correct script it will solve the issue. Thankyou again.
