### ISSUE TITLE
[QUESTION] How to kill only streams that transcode 4K VIDEO

### ISSUE THREAD

**Issue by gmaster12** [blacktwin/JBOPS#117]
The kill_stream works great for stopping 4K transcodes. I'm looking for a way for it to stop only VIDEO: 4k transcodes. Some clients needs to transcode the audio which is fine. The kill_stream stops the stream even if the VIDEO is directplay/directsteam while audio or the container is transcoded.

![image](https://user-images.githubusercontent.com/32989867/48442865-05c78b80-e755-11e8-9492-befdcd3fb240.png)

**Comment by blacktwin** [comment]
It's all in the conditions you set in Tautulli. What are you conditions?

Try: [ `Video Decision` | `is` | `transcode` ]
