### ISSUE TITLE
kill else if buffering script is not working (for me)

### ISSUE THREAD

**Issue by prinzpi** [blacktwin/JBOPS#118]
Hi,

I have tried to setup the kill_else_if_buffering.py script.
But without success. It will just recognized that there is an buffering and also a notification will be sent, but that's all. The notification is just "empty" and no session from other users will be killed.

In the log it's look like this:
![logs](https://user-images.githubusercontent.com/12089703/48632809-22b4c680-e9c2-11e8-8f3b-2aa497c98fa9.PNG)

So there is a trigger, but no action?!
Can you please confirm that the script is up and working for you.

Thanks.

**Comment by blacktwin** [comment]
Please post a link to your complete Tautulli logs on Gist.
How to Find Your Logs
View the Tautulli logs by clicking on "View Logs" in the settings menu. Click the "Download logs" button to save a copy of the log file. If Tautulli is unable to start, then the tautulli.log file is located in the logs folder where Tautulli is installed. Paste the logs on Gist and post the link here, do not upload the file as an attachment.

**Comment by prinzpi** [comment]
Of course, here you go:
https://gist.github.com/prinzpi/c2069099ed8cf6c37f561e893d957d19

Best regards.

**Comment by blacktwin** [comment]
Looks like you might have modified the script. Here is the first [error](https://gist.github.com/prinzpi/c2069099ed8cf6c37f561e893d957d19#file-gistfile1-txt-L7112-L7113) then you added something because the [lines don't match up.](https://gist.github.com/prinzpi/c2069099ed8cf6c37f561e893d957d19#file-gistfile1-txt-L7995-L8000). So what did you change?

**Comment by prinzpi** [comment]
I have executed the script manually and was facing some syntax error, I have tried to fix those by myself (e.g. deleting some lines at the header).

**To find the issue more efficient I'm now using the original file again.**

The logs are displaying following:
```
Tautulli Notifiers :: Script error:
        File "/opt/Tautulli/custom_scripts/kill_else_buffering.py", line 83
            main()
                  ^
    IndentationError: expected an indented block 
```

I have tried to fix this issue by indenting the `main()` block with one tab, but after this I'm now receiving following issue (so this seems not to have resolved the issue)
```
Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/opt/Tautulli/custom_scripts/kill_else_buffering.py", line 83, in <module>
            main()
        File "/opt/Tautulli/custom_scripts/kill_else_buffering.py", line 75, in main
            MESSAGE = DEFAULT_REASON.format(user=to_finish[3], x=len(filtered_dict.values()[0]),
    UnboundLocalError: local variable 'to_finish' referenced before assignment 
```

Need to say that those error messages was just produced by "only" using the "Test script" button and not in a real scenario when somebody was buffering (not sure if this is relevant).

Regards.

**Comment by blacktwin** [comment]
Ok so start over. Copy the script from the repo again and start fresh. What do you get?

**Comment by prinzpi** [comment]
> 
> 
> Ok so start over. Copy the script from the repo again and start fresh. What do you get?

I'm receiving following error message by using the "Test Script" button:

```
Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/opt/Tautulli/custom_scripts/kill_else_buffering.py", line 86, in <module>
            main()
        File "/opt/Tautulli/custom_scripts/kill_else_buffering.py", line 66, in main
            title = unicodedata.normalize('NFKD', title).encode('ascii', 'ignore').translate(None, "'")
    TypeError: normalize() argument 2 must be unicode, not str 
```

**Comment by blacktwin** [comment]
Ok. I've updated the script. Please try and let me know if it's resolved.

**Comment by prinzpi** [comment]
Hi, thanks for the update.
Now I don't receive any error messages anymore. 👍 

Now the script will be triggered, but nothing happens.
I have entered the username of my friend as admin, we both watched a movie and the script was triggered as you can see in the logs, but no action. My Stream was still up and running?! 

I have uploaded the new logs on gist:
https://gist.github.com/prinzpi/40d70e0d947181ce95849fd3f914cc06

**Comment by blacktwin** [comment]
You'll need more than just one additional stream from users other than admin. The script is specific in what it's looking for. 

- [ ] Admin stream
- [ ] User(s) with more than 1 transcoding stream.

When the script ran, was the above true?

**Comment by prinzpi** [comment]
> 
> 
> You'll need more than just one additional stream from users other than admin. The script is specific in what it's looking for.
> 
>     * [ ]  Admin stream
> 
>     * [ ]  User(s) with more than 1 transcoding stream.
> 
> 
> When the script ran, was the above true?

Ahh, got it. Then I may misunderstood the script in generally.

Would it suits to my scenario which is:
Admin user and specific user(s) are privileged, so if it's buffering **all** streams (1 stream would be enough) from not admin / privileged user will be terminated if I change following line of code:


```
# Remove users with only 1 stream. Targeting users with multiple concurrent streams
    filtered_dict = {key: value for key, value in user_dict.items()
                     if len(value) is not 1}
```

Into:
```
# Remove users with only 1 stream. Targeting users with multiple concurrent streams
    filtered_dict = {key: value for key, value in user_dict.items()
                     if len(value) is 1}
```

Regards.

**Comment by blacktwin** [comment]
That edit would only select users with 1 stream and not 1 or more. 

```python
# Remove users with only 1 stream. Targeting users with multiple concurrent streams
    filtered_dict = {key: value for key, value in user_dict.items()
                     if len(value) > 0}
```

But really if you want to do that then just remove the filter_dict part.


```python
    for session in plex.sessions():
        if session.transcodeSessions:
            trans_dec = session.transcodeSessions[0].videoDecision
            username = session.usernames[0]
            if trans_dec == 'transcode' and username not in ADMIN_USER:
                sess_key = session.sessionKey
                percent_comp = int((float(session.viewOffset) / float(session.duration)) * 100)
                time_to_comp = int(int(session.duration) - int(session.viewOffset)) / 1000 / 60
                title = unicode(session.grandparentTitle + ' - ' if session.type == 'episode' else '') + session.title
                title = unicodedata.normalize('NFKD', title).encode('ascii', 'ignore').translate(None, "'")
                add_to_dictlist(user_dict, username, [sess_key, percent_comp, title, username, time_to_comp])

    # Find who to kill and who will be finishing first.
    if user_dict:
        for users in user_dict.values():
            to_kill = min(users, key=itemgetter(1))
            to_finish = max(users, key=itemgetter(1))
       
        MESSAGE = DEFAULT_REASON.format(user=to_finish[3], x=len(filtered_dict.values()[0]),
                                        video=to_finish[2], time=to_finish[1], comp=to_finish[4])
    
        print(MESSAGE)
        kill_session(to_kill[0], MESSAGE)
```

like that ^

**Comment by prinzpi** [comment]
> ```python
>        
>         MESSAGE = DEFAULT_REASON.format(user=to_finish[3], x=len(filtered_dict.values()[0]),
>                                         video=to_finish[2], time=to_finish[1], comp=to_finish[4])
> ```

Thanks, I have just changed the` x=len(filtered_dict.values()[0])` because the filtered_dict is therefore not existing anymore. Now it's working.

Have a nice day.

**Comment by blacktwin** [comment]
Yeah, oops. I corrected the above snippet.

```python
 MESSAGE = DEFAULT_REASON.format(user=to_finish[3], x=len(user_dict.values()[0]),
                                        video=to_finish[2], time=to_finish[1], comp=to_finish[4])
```
