### ISSUE TITLE
send mail to all users with localusers crash script

### ISSUE THREAD

**Issue by arsenicks** [blacktwin/JBOPS#120]
Hey, first thanks for sharing your code!

So here's the deal, I'm trying to notify all my users except one, I call the script like this:
/usr/bin/python /home/xxxxx/.config/tautulli/notify_added_lastweek.py -t poster -d 7 -u all -i chialleux70 -s 205 135

And I get:
Traceback (most recent call last):
  File "/home/xxxxxx/.config/tautulli/notify_added_lastweek.py", line 339, in <module>
    print('Sending email(s) to {}'.format(', '.join(to)))
TypeError: sequence item 1: expected string, NoneType found

I'm really not good at coding but from what I understand the "list" of email contain a NoneType item in it. I think this is because I have local users I created inside my plex which have no email address associated. Anyway I saw you checked for x['email'] != '' but for some reason it didn't work. Here's my "patch" and it's working, feel free to tell me if it's stupid if it is I'll be glad to learn the correct way ;)

Offending code:
`
        [to.append(x['email']) for x in get_users() if x['email'] != '' and x['email'] not in to
`

Code fixed:
`        [to.append(x['email']) for x in get_users() if x['email'] != None and x['email'] not in to`

**Comment by blacktwin** [comment]
Thanks. This script is pretty much obsolete ever since Tautulli added a newsletter. You might want to check that out.
