### ISSUE TITLE
Could not find a version that satisfies the requirement basemap

### ISSUE THREAD

**Issue by onedr0p** [blacktwin/JBOPS#123]
I am unable to pull in the requirements for this project...

```
$ pip install -r requirements.txt
Collecting requests (from -r requirements.txt (line 5))
...
Collecting basemap (from -r requirements.txt (line 9))
  Could not find a version that satisfies the requirement basemap (from -r requirements.txt (line 9)) (from versions: )
No matching distribution found for basemap (from -r requirements.txt (line 9))
```

**Comment by onedr0p** [comment]
The solution is [here](https://github.com/matplotlib/basemap/issues/251#issuecomment-419000005_, any change @blacktwin you can add this to the readme?

**Comment by blacktwin** [comment]
So libgeos is needed for Linux installs? I've only ran on windows.

**Comment by onedr0p** [comment]
It appears so.

**Comment by blacktwin** [comment]
For now, I've created a requirements.txt for the maps section and removed those required libraries from the main requirements.txt.
