### ISSUE TITLE
limiterr.py script errors

### ISSUE THREAD

**Issue by alexanderupton** [blacktwin/JBOPS#124]
Hello, 

I'm attempting to use limiterr.py as a script to execute when select users play content and each time the script executes within the conditions it never kills the sesion and the user is never alerted.

The logs report the following errors. It's worth noting that the first error "recordsFiltered" appears when using a limit based on the number of plays.

The second error "data" occurs when switching to a time based trigger, ex:
--limit days=0 --limit hours=0 --limit minutes=1 

Thus far I'm unable to make the script execute properly. Any suggestions would be greatly appreciated.

Thank you!

OS = Windows7 x86_64
Python = x86_64 2.7.15
Tautulli =  v2.1.26 

1:
Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "D:\PlexPy\scripts\limiterr.py", line 325, in <module>
            total_jbop = history['recordsFiltered']
    KeyError: 'recordsFiltered' 

2:
Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "D:\PlexPy\scripts\limiterr.py", line 323, in <module>
            total_jbop = sum([data['duration'] for data in history['data']])
    KeyError: 'data'

**Comment by blacktwin** [comment]
It would be easier to look through the logs. Can you post them in gist?

> Please post a link to your complete Tautulli logs on Gist.
How to Find Your Logs
View the Tautulli logs by clicking on "View Logs" in the settings menu. Click the "Download logs" button to save a copy of the log file. If Tautulli is unable to start, then the tautulli.log file is located in the logs folder where Tautulli is installed. Paste the logs on Gist and post the link here, do not upload the file as an attachment.

Is this your first script that you've setup? Are any other scripts setup and working correctly? 

First thing I'd check is if you have the API enabled (Tautulli Settings > Web Interface > API

**Comment by alexanderupton** [comment]
> "First thing I'd check is if you have the API enabled (Tautulli Settings > Web Interface > API"

That was what I needed... I had only previously used the Prowl notification agent which didn't require enablement of the API.  I didn't see any reference to this in the readme files either, but will remember this for the future.

Thank you very much for the quick response and your contributions. Most appreciated!

**Comment by blacktwin** [comment]
Good point. I'll add it. Thanks!

**Comment by blacktwin** [comment]
Hey! it was in the [readme](https://github.com/blacktwin/JBOPS#enable-api-in-tautulli)
