### ISSUE TITLE
Remove inactive account script error

### ISSUE THREAD

**Issue by irodimus** [blacktwin/JBOPS#125]
I tried running the "removing_inactive_users.py" script and it gave an error on Line 19 when it appeared to look for the CONFIG file even after entering the TOKEN and URL manually. I did comment lines 19, 20, 24, and 25 looking for the CONFIG file for both Tautulli and Plex and it continued.

I tested it first commenting the unshare and remove lines and it gave me the list of users with times. I then uncommented the unshare line and it gave me this error:

```
Traceback (most recent call last):
  File "remove_inactive_users.py", line 113, in <module>
    main()
  File "remove_inactive_users.py", line 97, in main
    unshare(username)
  File "remove_inactive_users.py", line 71, in unshare
    plex.myPlexAccount().updateFriend(user=user, server=plex, removeSections=True, sections=sections_lst)
  File "/usr/local/lib/python2.7/site-packages/plexapi/myplex.py", line 266, in updateFriend
    user = user if isinstance(user, MyPlexUser) else self.user(user)
  File "/usr/local/lib/python2.7/site-packages/plexapi/myplex.py", line 325, in user
    raise NotFound('Unable to find user %s' % username)
plexapi.exceptions.NotFound: Unable to find user USER
```

USER is the user that was passed the threshold. I'm not sure if commenting those lines looking for the CONFIG file may have messed with the script but I figured I'd post this.

**Comment by blacktwin** [comment]
Does that user exist in your Plex Settings > Family & Friends > Sharing? Is that user an awaiting invitation?

**Comment by irodimus** [comment]
The user is in Sharing and has been been for over a year. The only difference is that in Plex, it shows the username that plex uses to register and not the friendly name I have given it Tautulli.

So for example, a plex username in Plex is 'user1@mail.net', but I changed the Friendly Name in Tautulli for the user to 'Tim'.

 I'm wondering if thats where its may be getting confused and it's looking for the user that Tautulli gives which is 'Tim' and there is no user in Plex for that as it would be 'user1@mail.net'.

**Comment by blacktwin** [comment]
Ok thats sounds like thats the issue. [`get_users_table`](https://github.com/Tautulli/Tautulli/blob/master/API.md#get_users_table) only pulls the friendly name, which is editable in Tautulli. Which is what is used to match against Plex's user list.

**Comment by irodimus** [comment]
Just tried https://github.com/blacktwin/JBOPS/commit/2a39697acd67eb59f75f05b7abead713505fcb52 and now I get this only with no list of times for the other users:

```
plex-ht:Scripts administrator$ python2 remove_inactive_users.py
User: USER1 has records in Tautulli but does not exist in Plex.
USER1 was last seen 69 days ago.
User: USER2 has records in Tautulli but does not exist in Plex.
USER2 was last seen 8 hours ago.
```

**Comment by blacktwin** [comment]
Are the other users in the `USER_IGNORE` list?

**Comment by irodimus** [comment]
No, just the example ignore user you listed. I hadn't changed anything, just updated to the new commit.

**Comment by blacktwin** [comment]
Do they have history in Tautulli?

**Comment by irodimus** [comment]
Sure do. User1 is a regular user and User2 is my own admin account.

**Comment by blacktwin** [comment]
I goofed. Try again.

**Comment by blacktwin** [comment]
That should be the last one.

**Comment by irodimus** [comment]
I just noticed that USER1 was no longer in Plex after removing the friendly name in Tautulli so that's correct to show. That was my bad. USER2 though is my admin account so that doesn't show in the Sharing view in Plex and that might be why it shows up.

I tried https://github.com/blacktwin/JBOPS/commit/e2475fae3b3015ed8048bf3a9e3bd65d922b5713
and it shows the list now but still shows the issue with the admin account posted above.

**Comment by blacktwin** [comment]
there is baa6873 to try.

**Comment by irodimus** [comment]
I ran into another thing. If you have already unshared all libraries from a user, rerunning the script will error:
```
Traceback (most recent call last):
  File "remove_inactive_users.py", line 139, in <module>
    main()
  File "remove_inactive_users.py", line 133, in main
    unshare(username)
  File "remove_inactive_users.py", line 96, in unshare
    plex.myPlexAccount().updateFriend(user=user, server=plex, removeSections=True, sections=sections_lst)
  File "/usr/local/lib/python2.7/site-packages/plexapi/myplex.py", line 283, in updateFriend
    response_servers = self.query(url, self._session.delete, json=params, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/plexapi/myplex.py", line 176, in query
    raise BadRequest('(%s) %s %s; %s' % (response.status_code, codename, response.url, errtext))
plexapi.exceptions.BadRequest: (404) not_found https://plex.tv/api/servers/20253b4dc5cce18dc752eb4dfeebf9eb9eeea237/shared_servers; <!DOCTYPE html> <html> <head>   <title>The page you were looking for doesn't exist (404)</title> <link href="/assets/errors.css" media="screen" rel="stylesheet" type="text/css" />   <script type="text/javascript">     var _gaq = _gaq || [];     _gaq.push(['_setAccount', 'UA-6111912-23']);     _gaq.push(['_setDomainName', 'plex.tv']);     _gaq.push(['_trackPageview', '/404?url=' + window.location.pathname]);     (function() {       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);     })();   </script> </head>  <body> <div class="block">   <div class="dialog">   	<h1>Oops; a 404 error...</h1>     <h2>That's "page not found" in human language.</h2>     <p>You may have mistyped the address or the page may have moved.<br/>   	  <a href="/">Let us take you to the main page</a> and we can start all over again, shall we?     </p>   </div> </div> </body> </html>
```

**Comment by blacktwin** [comment]
> Oh, I noticed that the list the script displays now uses the Plex usernames and not the friendly names from Tautulli. I'm guessing this is by design now unless the user is not found in Plex.

Yes. 

> I ran into another thing.

hmmm, i'll have to look into that.

**Comment by blacktwin** [comment]
- [ ] check if user has any libraries shared before attempting to unshare.

**Comment by blacktwin** [comment]
Interesting, looks like referencing the issue with 'resolved' in the commit closes the issue. Please Reopen if not resolved. Let me know either way please.

**Comment by irodimus** [comment]
Yes it resolves it by not crashing and just saying the User has records in Tautulli but does not exist in Plex now when that user has no shares.

Is there a way to just show the current active users with accounts and shares?

**Comment by blacktwin** [comment]
Just comment out this [line](https://github.com/blacktwin/JBOPS/blob/11715e1e6e177055d6264225515c38c19c50cc4b/utility/remove_inactive_users.py#L122).

```python
        # Check if friendly username from Tautulli does not exist in Plex
        if username not in users_dict.values():
            try:
                username = users_dict[user_id]
            except KeyError:
                # print('User: {} has records in Tautulli but does not exist in Plex.'.format(username))
                last_entry(last_seen, username)
                continue
```
Or delete the user from [Tautulli](https://github.com/blacktwin/JBOPS/blob/11715e1e6e177055d6264225515c38c19c50cc4b/utility/purge_removed_plex_friends.py).
