### ISSUE TITLE
kill_time.py

### ISSUE THREAD

**Issue by antigravity83** [blacktwin/JBOPS#128]
Hi mate

Just wondering - I have the your script setup to kill consecutive streams between 12am-7am. 

Couple of things I wanted to check with you:

- Are the usernames are taken from Tautulli, or Plex.
- Can the usernames have spaces in them? ie. ('First Last') Or do I need to put a \ or \\ after the First name?
- If you set the consecutive streams limit to 2, when does the kill message appear? Before the 2nd consecutive stream starts? Or when the 3rd starts?
- Does it limit consecutive streams? Or just total streams during the time period set?

Thanks for your help!

**Comment by antigravity83** [comment]
What to enter into Tautulli was a bit vague also, maybe because it was created when the UI was different? 

This is what I've entered into Tautulli under Notification Agents. If you could confirm if this is correct that'd be much appreciated (and by anyone else who may want to use this script 👍 )

<img width="558" alt="capture1" src="https://user-images.githubusercontent.com/27241813/50038414-082a4780-006b-11e9-902c-25b0020b31e8.PNG">
<img width="557" alt="capture2" src="https://user-images.githubusercontent.com/27241813/50038415-09f40b00-006b-11e9-8b72-281b048ccc64.PNG">
<img width="563" alt="capture3" src="https://user-images.githubusercontent.com/27241813/50038418-0ceefb80-006b-11e9-867f-34ac4ae71b32.PNG">
<img width="553" alt="capture4" src="https://user-images.githubusercontent.com/27241813/50038419-0eb8bf00-006b-11e9-9a3b-38129c9c5965.PNG">

**Comment by antigravity83** [comment]
Receiving this error in the Tautulli logs. I've tried with a space, with / and with //. None work. 
```


Tautulli Notifiers :: Script error:         File "/opt/plexpy2/scripts/kill_time.py", line 35             'Christine/ D': 2,                                       ^     SyntaxError: invalid syntax
--



```

**Comment by blacktwin** [comment]
Use [this ](https://github.com/blacktwin/JBOPS/blob/master/killstream/kill_stream.py) instead.  Here is an [example ](https://github.com/blacktwin/JBOPS/blob/master/killstream/readme.md#limit-user-stream-count-kill-last-stream) that might help with what you want to do.
> Are the usernames are taken from Tautulli, or Plex.
```
{user} | The friendly name of the person streaming.
{username} | The username of the person streaming.
```

>Can the usernames have spaces in them? ie. ('First Last') Or do I need to put a \ or \ after the First name?

Just need to be the exact same name as either the Friendly Name {user} you assigned in Tautulli or the Username {username} from Plex.

>If you set the consecutive streams limit to 2, when does the kill message appear? Before the 2nd consecutive stream starts? Or when the 3rd starts?

In this [example](https://github.com/blacktwin/JBOPS/blob/master/killstream/readme.md#limit-user-stream-count-kill-last-stream) the user would not be able to have more than 3 streams.

> Does it limit consecutive streams? 

Yes.

> Or just total streams during the time period set?

Combine with this [example](https://github.com/blacktwin/JBOPS/blob/master/killstream/readme.md#kill-by-hours-of-the-day) for limiting the user's stream count during a time range.

**Comment by antigravity83** [comment]
Thanks - I think you may have understood my requirements though. 

I want to stop people from streaming content when they fall asleep at night. 

Your original script, kill_time.py allows a certain number of streams in a certain time period, and gives the user an option to continue if they are still awake. 

The example you quoted don't seem to do that? (ie. one kills all streams between a certain time, the other limits streams for all times - and neither give the option for the user to manually intervene to continue watching)

Does kill_time.py still work with Tautulli? I'm getting the following error no matter what I try:

```
Tautulli Notifiers :: Script error:         
File "/opt/plexpy2/scripts/kill_time.py", line 35 
'Christine/ D': 2,
^     SyntaxError: invalid syntax
```

Christine D is a user in both Plex and Tautulli

**Comment by blacktwin** [comment]
> I want to stop people from streaming content when they fall asleep at night.

oh gotcha. Here is an [example](https://github.com/blacktwin/JBOPS/blob/master/killstream/limiterr_readme.md#limit-user-to-an-amount-of-plays-of-a-show-during-a-time-of-day) using this [script](https://github.com/blacktwin/JBOPS/blob/master/killstream/limiterr.py).

>Does kill_time.py still work with Tautulli? 

Maybe? It's been replaced or combined into [limiterr.py](https://github.com/blacktwin/JBOPS/blob/master/killstream/limiterr.py)

>I'm getting the following error no matter what I try:

Looks like you have an invalid syntax. Maybe you've edited the script and made a mistake.

**Comment by antigravity83** [comment]
> oh gotcha. Here is an [example](https://github.com/blacktwin/JBOPS/blob/master/killstream/limiterr_readme.md#limit-user-to-an-amount-of-plays-of-a-show-during-a-time-of-day) using this [script](https://github.com/blacktwin/JBOPS/blob/master/killstream/limiterr.py).

Ahh beautiful, thank you! Will give that a shot now. Thanks

**Comment by antigravity83** [comment]
Ok thanks - I changed it to 10 seconds so users don't have to wait too long to manually play again - but all I seem to get is "User is awake". 

I'll change it to 20 seconds. 

Thanks again for your help - scripts are fantastic!
