### ISSUE TITLE
Playlist Manager --libraries for Popular lists

### ISSUE THREAD

**Issue by irodimus** [blacktwin/JBOPS#131]
Is it possible to use the --libraries option with PopularTV or PopularMovies lists? I tried but it did not seem to work. I have several Movies libraries but don't want them to all be included in these lists.

**Comment by blacktwin** [comment]
Well it's currently pulling from Tautulli so it would only pull from libraries that Tautulli is recording history on and you've selected to be displayed on the home page. 

And yes, good suggestion. I'll use the `--allLibraries`  with exclusion as I have in other scripts.

**Comment by blacktwin** [comment]
Should be good to go now.
