### ISSUE TITLE
Getting errors during install on Ubuntu 18.10

### ISSUE THREAD

**Issue by jwaltrip4** [blacktwin/JBOPS#134]
follows basics I think, but when I to install basemaps  I get this

Collecting basemap (from -r requirements.txt (line 8))
  Could not find a version that satisfies the requirement basemap (from -r requirements.txt (line 8)) (from versions: )
No matching distribution found for basemap (from -r requirements.txt (line 8))

**Comment by blacktwin** [comment]
Maybe try [this](https://gist.github.com/junzis/36fee36acd7cadfdf1c01c06d97f4947)? 

This is package is only needed if you indeed on using the ips_to_maps.py script.

**Comment by jwaltrip4** [comment]
that is exactly what I am trying to set up :)

**Comment by blacktwin** [comment]
Did the links help get you going?

**Comment by jwaltrip4** [comment]
I am still getting errors... :)
when I run python ips_to_maps.py, I get this

Tautulli API 'get_users_tables' request failed: 'data'.Tautulli API
'get_users_tables' request failed: 'data'.Traceback (most recent call last):
  File "ips_to_maps.py", line 377, in <module>
    user_lst = sorted(get_users_tables('friendly_name', user_count))
TypeError: 'NoneType' object is not iterable

**Comment by blacktwin** [comment]
Make sure that the API_KEY is correct and that API is enabled in Tautulli's Web Interface Settings.
