### ISSUE TITLE
Limit to x plays a day

### ISSUE THREAD

**Issue by sbcrumb** [blacktwin/JBOPS#135]
I am trying to limit 2 users to 3 plays a day.
But what I am seeing in the logs when the user has one play is the following.

--jbop watch --username xxxx--sessionId 6406145D-2E0D-4515-8C1E-2EF661480EC5 --today --limit plays=3 --notify 1 --killMessage 'You have met your limit of 3 watches .'

But the person's only showing having 1 play today.

My Trigger are this
Triggers on Playback Start and Transcode Change.

Conditions
Username is x and y

**Comment by blacktwin** [comment]
Ok. Tell them to watch more? I'm not sure I understand. If they trigger the script the script will run and check if they've met the threshold (3) if not then nothing happens. What is the issue? Is it killing the stream after 1 watch?

**Comment by sbcrumb** [comment]
Lol ok so it is logging that it killed it. But I am guessing that it didn't actually kill it? I just noticed it int he logs and they are not streaming any longer so I assumed it killed them but maybe it didnt.

**Comment by blacktwin** [comment]
There would be an acknowledgement that the stream was killed in the logs.

**Comment by sbcrumb** [comment]
ok then it is killing before 3 is hit cause according to plexpy they are at 1 play.

**Comment by blacktwin** [comment]
Can you share your logs? post them to a gist and share the link.

**Comment by sbcrumb** [comment]
yeah hang on

**Comment by sbcrumb** [comment]
https://gist.github.com/sbcrumb/627e074784c657b40caaab2432477ad9

**Comment by blacktwin** [comment]
Based on the logs, no streams were killed.

**Comment by sbcrumb** [comment]
ok any reason it is logging like it is? Or is that normal?

**Comment by blacktwin** [comment]
Normal'ish. The session_id it's getting is incorrect and this can happen sometimes. What should be normal is an output of "User x has watched z amount and limit is y" if less then limit then script dies. If more than, there should an output into the logs says that the stream was killed.

**Comment by sbcrumb** [comment]
ok I will keep an eye on it. Thanks
