### ISSUE TITLE
[Request] Killstream message enhancements

### ISSUE THREAD

**Issue by drizuid** [blacktwin/JBOPS#136]
Can we get the option to send {player} and {platform} in the richmedia stream to discord/slack?  I have my plex users in a discord channel so they can see this info, but for some of them, they have to ask me which device was being used. Currently, i have a script that sends that info to me via pushover so I can yell at them on discord but im looking to automate. Eventually i'll need to look at matching their plex friendly name with their discord name so I can use mentions.. but that's future (unless you guys are already looking at it!)

**Comment by blacktwin** [comment]
> Can we get the option to send {player} and {platform} in the richmedia stream to discord/slack?

You can do this now. A simple edit to the script. This [block](https://github.com/blacktwin/JBOPS/blob/master/killstream/kill_stream.py#L441-L470). Mainly this part:

```python
                    "fields": [
                        {
                            "inline": True,
                            "name": "User",
                            "value": self.stream.friendly_name
                        },
```

Create another dictionary with inline, name, and value. 

- Inline is the positioning
- name is what you'll see as the subject of the message
- value is what you'll see as the body of the message

Use this [picture](https://camo.githubusercontent.com/f932e72bda6882af54574a3e80b2b3d45d073f2b/68747470733a2f2f692e696d6775722e636f6d2f3969515a7371342e706e67) for reference.

You'd want:

```python
{"inline": True,
 "name": "Player",
"value": self.stream.player},
{"inline": True,
 "name": "Platform",
"value": self.stream.platform},
```
To find what the other possible `self.stream.*` names are, check [here](https://github.com/Tautulli/Tautulli/blob/master/API.md#get_activity). It's up to you what you want to see in the message.

> Eventually i'll need to look at matching their plex friendly name with their discord name so I can use mentions

Again that is up to you. To tag someone in discord from a bot or script you need to use their ID. So in Discord right click on the user and Copy ID. Then wrap it in `<>` and prefix an `@`: `<@1234567890>`. You can add some kind of dictionary of your users and their IDs into the script.

```python
discord_users = {'steve': '<@1234567890>',
                 'mike': '<@0987654321>'}
```
Then check against it to grab the ID to add into the message.

**Comment by blacktwin** [comment]
![](https://cdn.discordapp.com/attachments/283629564087762945/531292526406008841/unknown.png)


👍
