### ISSUE TITLE
Rich notifications stop "Limit user to an amount of Plays of a show during a time of day" from working

### ISSUE THREAD

**Issue by antigravity83** [blacktwin/JBOPS#137]
When adding the following to the "Limit user to an amount of Plays of a show during a time of day", it stops the script from working. 

`--notify 9 --serverName {server_name} --posterUrl {poster_url} --richColor '#2C2D30' --richMessage slack`

> With --notify 9 referring to the Slack webhook. 

The above line works when adding to any kill_stream.py script.

**Comment by blacktwin** [comment]
limiterr.py does not have the rich notification. May combine limiterr.py into the kill_stream.py at some point.

**Comment by antigravity83** [comment]
Ok thanks - will using the notify tag work without rich notifications?

ie. tag the slack webhook notifier?
