### ISSUE TITLE
Limiterr.py script ignores custom --killMessage

### ISSUE THREAD

**Issue by antigravity83** [blacktwin/JBOPS#138]
When using "Limit user to an amount of Plays of a show during a time of day", the script ignores whatever is entered into the --killMessage argument, and instead sends what is hardcoded into the script:

```
LIMIT_MESSAGE = 'Are you still watching or are you asleep? ' \
                'If not please wait ~{delay} seconds and try again.'
```

**Comment by blacktwin** [comment]
There you go. Good catch.

**Comment by antigravity83** [comment]
Thanks 👍
