### ISSUE TITLE
limiterr limit replays of the same content

### ISSUE THREAD

**Issue by StarScream159** [blacktwin/JBOPS#139]
Hey, love your scripts. They are great and hopefully what I'm looking for is possible. I searched but couldn't see someone asking the same question.

What I'd like to be able to do is kill a stream if the user is re-watching something they've previously watched. Either by count or by time.

ie. kill stream if user has watched this item more then 5 times
ie. kill stream if user has watched this item in the last day/week/month

**Comment by blacktwin** [comment]
Interesting. Can I ask why? What is it that a user is playing so much that you want it to not be possible? 

You can kinda do this with [this](https://github.com/blacktwin/JBOPS/blob/master/killstream/limiterr_readme.md#limit-user-to-an-amount-of-plays-of-a-show-during-a-time-of-day) but it only works at the Show level currently, not for episodes or movies.

**Comment by StarScream159** [comment]
I have a user that repeats the same couple movies over and over for the kids. You know young kids and how they can watch the same Disney movie over and over. If the user wants to do that, I'll just give him the file. No sense in wasting my bandwidth and hydro to transcode it over and over.

I could just delete the movies/files, which I'll probably do as a stop-gap. But that just removes it for everyone, including myself and it might just happen again with a different title.

I saw the link you posted before I created this. I tend to not have a problem with Shows, this is only a movies thing.

**Comment by blacktwin** [comment]
I'm not sure that killing the stream would be the best fit for this case. It maybe better to, like you said, give the file up if you've noticed that a user has watched some over X amount of times. Which can be found in the users history. 

Has Joey watched Frozen 18 times this month? Hey Joey's parent you want Frozen.file?

**Comment by StarScream159** [comment]
Okay. I'll just take that approach.
