### ISSUE TITLE
How to add delay to any script?

### ISSUE THREAD

**Issue by seanvree** [blacktwin/JBOPS#14]
Hey buddy, 

not sure if this is possible, but wondering if it's possible to add a notification delay to any script?

The one I'm concerned about is this one:

https://gist.github.com/JonnyWong16/1b1b02536e25002daf678946f513b950

This one sends a notification when a certain number of streams is currently active. The problem is that it notifies like every 30 seconds.  Possible to edit the code to put in a "do not notify more than x minutes" type of deal?

Thanks brotha.

**Comment by blacktwin** [comment]
@seanvree You have an issue with code that isn't mine....... :) ummm. I have a[ delay_notify](https://github.com/blacktwin/JBOPS/blob/master/notify/notify_delay.py) script. The delay part can be found [here](https://github.com/blacktwin/JBOPS/blob/master/notify/notify_delay.py#L100-L111). You could some how work it into this [section](https://gist.github.com/JonnyWong16/1b1b02536e25002daf678946f513b950#file-notify_stream_threshold-py-L34-L44).

**Comment by seanvree** [comment]
Coo, thanks brotha.

**Comment by seanvree** [comment]
@blacktwin  I wonder if simply adding these lines:

``
            sleep(INTERVAL)
            x += INTERVAL
```

So that entire block you posted above from @jonnywong16 's script would look like this:

```
    if streams >= STREAM_THRESHOLD:
        print("Number of streams exceeds {threshold}.".format(threshold=STREAM_THRESHOLD))
        print("Sending PlexPy notification to agent ID: {agent_id}.".format(agent_id=AGENT_ID))
	sleep(INTERVAL)
        x += INTERVAL

        params = {'apikey': PLEXPY_APIKEY,
                  'cmd': 'notify',
                  'agent_id': AGENT_ID,
                  'subject': NOTIFY_SUBJECT,
                  'body': NOTIFY_BODY.format(streams=streams, timestamp=timestamp)
                  }

        r = requests.post(PLEXPY_URL.rstrip('/') + '/api/v2', params=params)
	x = 0

```

**Comment by blacktwin** [comment]
@seanvree You've got some indention issues and you're increasing `x` but not doing anything with it. You want to test `x` like `while x < TIMEOUT:` so that it keeps checking in to see `if x < TIMEOUT` if it is and the the threshold is still met then notify. Does that help?
