### ISSUE TITLE
[Request] kill_stream.py Kill transcode only if platform is not Opera TV Store

### ISSUE THREAD

**Issue by Deepcuts** [blacktwin/JBOPS#140]
I have some users that are just lazy/don't care as long as it works, that are using platforms that can direct play without any problems but don't setup their clients to do so.
Then, I have users that had the bad luck of choosing a Sony or LG TV. Those TVs are unable to direct play most of my content no matter how the user sets up their devices. 

Is there any way to keep the current and working setup that kills any transcode but NOT if the platform is "Opera TV Store" for example?

Later edit
I guess I was too tired to see that Tautulli already has the option.
For anyone who needs this:
![image](https://user-images.githubusercontent.com/4704834/51844769-b7bb3080-231e-11e9-9ef2-b1cd556f5d81.png)

The non-issue can be closed.
Thank you.

**Comment by blacktwin** [comment]
Condition logic can be left empty if it's an `and` statement just as it's described.
