### ISSUE TITLE
delete_watched_TV removes all unwatched episodes

### ISSUE THREAD

**Issue by Generator** [blacktwin/JBOPS#142]
delete_watched_TV at start worked without issues, but now started to removing all unwatched episodes.

**Sample setings**
```
SHOW_LST = [1234, 4321, 6789]  # Show rating keys.
USER_LST = ['Bob', 'Joe'] # Name of users
```
**Bob** watched all episodes of **SampleShow** (4321), but **Joe** only watched one or none of the episodes, however delete_watched_TV removes all episodes 
``` 
SampleShow SampleEpisode1 has been watched by Bob & Joe
Removing /path/to/TVShows/SampleShow/Season 01/SampleEpisode1.mkv
...
```

**Screenshots**
History
![screenshot_2019-02-06 tautulli - history sanguepipi](https://user-images.githubusercontent.com/44146/52352052-cd69dd80-2a23-11e9-885e-aa971016db8b.png)

cmd output
![captura de ecra_2019-02-06_15-23-28](https://user-images.githubusercontent.com/44146/52352069-d6f34580-2a23-11e9-9586-1b952a557ed4.png)

Script settings
```
TAUTULLI_APIKEY = 'xxxxxxxxx'  # Your Tautulli API key
TAUTULLI_URL = 'http://localhost:8181/'  # Your Tautulli URL
SHOW_LST = [2111, 2037, 2099, 1969, 1901]  # Show rating keys.
USER_LST = ['American_Jesus', 'Ruben']  # Name of users
```

The same happens with other show, where one of the use haven't watched any episode.

**Comment by blacktwin** [comment]
Confirmed. Looking into it now.

**Comment by Generator** [comment]
Just to mention.  with another (single) user, none of the watched episodes are getting removed, and no terminal output.

**Comment by blacktwin** [comment]
@Generator please try this update. Comment out the actual deletion line

`# os.remove(meta_dict['file'])`

**Comment by Generator** [comment]
Could only test with a single user for now (don't have common watched episodes now) seems to be working.  
I'll make further tests when some episode is watched by two or more users, tried (re)adding some watched episode but didn't see it as watched.

Also i was using Tautulli's friendly name, instead of real full name, that could be one of the issues, the script doesn't seem to look up for friendly names.

**Comment by blacktwin** [comment]
@Generator you good?

**Comment by Generator** [comment]
I think so, i'm trying to figure it out if the rating keys of a show stay the same after all episodes are removed and later added.

I'm closing the issue, i'll re-open or create a new one if found something else.
