### ISSUE TITLE
Kill Paused Streams

### ISSUE THREAD

**Issue by jayserver** [blacktwin/JBOPS#143]
Followed the guide, setup the arguments, but it doesn't seem to work. 

What am I doing wrong?

Thanks

**Comment by blacktwin** [comment]
I have no idea. You'll need to provide some more information. Maybe screenshots for your agent's configuration tabs or logs.

**Comment by jayserver** [comment]
I've attached screens. And yes, I have Plex Pass and the latest Tautulli installed.

<img width="787" alt="screen shot 2019-02-08 at 12 05 28 pm" src="https://user-images.githubusercontent.com/46820923/52493626-f8763d80-2b99-11e9-8658-4e6c55447d19.png">
<img width="764" alt="screen shot 2019-02-08 at 12 05 21 pm" src="https://user-images.githubusercontent.com/46820923/52493627-f8763d80-2b99-11e9-824f-f20fcf32375c.png">
<img width="767" alt="screen shot 2019-02-08 at 12 05 15 pm" src="https://user-images.githubusercontent.com/46820923/52493628-f8763d80-2b99-11e9-9597-70da060fbaa1.png">
<img width="767" alt="screen shot 2019-02-08 at 12 05 09 pm" src="https://user-images.githubusercontent.com/46820923/52493629-f8763d80-2b99-11e9-92fa-8964387a334c.png">

**Comment by blacktwin** [comment]
### Please post a link to your complete Tautulli logs on Gist.
#### How to Find Your Logs

View the Tautulli logs by clicking on "View Logs" in the settings menu. Click the "Download logs" button to save a copy of the log file. If Tautulli is unable to start, then the tautulli.log file is located in the logs folder where Tautulli is installed. Paste the logs on Gist and post the link here, do not upload the file as an attachment.

**Comment by jayserver** [comment]
Hi, 

Here is the Gist.

https://gist.github.com/jayserver/be13ea7bff8ca33ecc3075405eadd952#file-tautullilog

**Comment by Arcanemagus** [comment]
```
2019-02-08 12:10:04 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Full script is: ['python', u'/config/scripts/kill_stream.py', '--jbop', 'stream', '--username', 'imzaahra', '--sessionId', 'EB494114-143E-4528-97AB-C3CB35649E61', '--killMessage', 'Paused streams are automatically stopped.']
2019-02-08 12:10:04 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Executing script in a new thread.
2019-02-08 12:10:05 - ERROR   :: Thread-36 : Tautulli Notifiers :: Script error: 
    File "/config/scripts/kill_stream.py", line 7
      <!DOCTYPE html>
      ^
  SyntaxError: invalid syntax
```

It looks like you downloaded the _page_ of the script, not the script itself. You should either clone the whole repository (so you can easily update), or manually download it from the <kbd>Raw</kbd> button at the top of the file.

**Comment by jayserver** [comment]
Is there something wrong with how I setup the conditions? As shown in the screenshots above?

Now its showing in the logs custom conditions are reporting to false. Even though I have two paused streams, one local, one remote.

**Comment by Arcanemagus** [comment]
The condition requires the stream to be transcoding, if those streams aren't transcoding then it _should_ be evaluating to false.

**Comment by blacktwin** [comment]
Looks like this can be closed. @jayserver good to go?

**Comment by jayserver** [comment]
All good!

Thanks!
