### ISSUE TITLE
[Request] Multiple filter/searches in Playlist Manager

### ISSUE THREAD

**Issue by irodimus** [blacktwin/JBOPS#145]
Is it possible to add `--filter` or `--search` for multiple queries when creating a playlist? For example, if it's possible to filter for action and comedy genres or search for South Park and Teen Hunger Force. I tried a few things like multiple `--filter` or `--search` options and it seems the last instance of either gets used only.

**Comment by blacktwin** [comment]
Confirmed issue.

**Comment by blacktwin** [comment]
@irodimus can you please test to confirm?

**Comment by irodimus** [comment]
Ok, my observations with https://github.com/blacktwin/JBOPS/commit/c603efb472cb2d7f1a4ec1510e76751d5e791332 when tested:

Using multiple `--filter` with two different keywords like `genre` does not work. I'm not sure if that is by design or not but it makes finding movies, for example, that are considered like action+comedy not to be found. In most cases, the last `--filter` is what kind of movies get returned. If you two different keywords like `genre` and `decade` though, it does work.

Generally, I was looking to use this for TV Shows where two shows could be included in one playlist using the `grandparentTitle`. I use this when doing a `--search` to come up with playlist for random specific shows and it works. Using multiple `--search` for tv shows like "looney tunes" and another "disney animated shorts" on the same command will only create the playlist for the last `--search`.

That's what I've seen so far from what I've tested. I'm still messing with it but if I notice anything else, I will let you know.

**Comment by blacktwin** [comment]
Can you share an example on your arguments?

**Comment by irodimus** [comment]
Sure.

This works:
```
python playlist_manager.py --jbop random --action update --name "09 Test" --limit 50 --libraries Movies --filter genre=comedy --filter year=1990
```
This does not (the last filter is what gets returned):
```
python playlist_manager.py --jbop random --action update --name "09 Test" --limit 50 --libraries Movies --filter genre=comedy --filter genre=horror
```
This is what I'm trying to create but I only get the Disney Animated Shorts in the playlist:
```
python playlist_manager.py --jbop random --action update --name "09 Cartoons" --libraries "TV Shows" --limit 100 --search grandparentTitle="looney tunes" --search grandparentTitle="disney animated shorts"
```
The above will work fine to get either show if there is only one `grandparentTitle` keyword used.

**Comment by blacktwin** [comment]
Ok. I see the problem. The `--filter` isolate matches based on `or` and not `and`.

This is what the script is doing:
![image](https://user-images.githubusercontent.com/22177672/53172991-b8a95000-35b4-11e9-91ac-d3dbed35303f.png)
This is what you want:
![image](https://user-images.githubusercontent.com/22177672/53172964-a16a6280-35b4-11e9-9683-7ad93b692580.png)

As for the `--search` you can only search one field for one keyword(s). You can search multiple fields, just not multiples of the same field. 

I'll have to look into both of these. It might be that I need to add something like `--search title=['star', 'wars']` to allow for multiple keywords for a field. The same for `--filter genre=['comedy', 'horror']` would mean `comedy and horror`, item would need to be both.

**Comment by blacktwin** [comment]
Also thanks a lot for all the help in testing this. I really appreciate it.

**Comment by blacktwin** [comment]
`AND` functionality is being added but `OR` maybe resolved by adding a `merge` action. Where you'd create a playlist `--filter genre=Horror` and another `--filter genre=Action` then merge the two to get a `Horror OR Action` playlist. Maybe...

**Comment by blacktwin** [comment]
Forgot to add in recent commits to reference this issue.
5ddd981f2f98fa1e9659eab7e80a1339333d2366
2a2a9f74ff36c2070e316f749465c080e37ab302

**Comment by blacktwin** [comment]
I think this can be closed now. If someone is having issues with what was implemented or wants more added please create a new issue.
