### ISSUE TITLE
Not have python window pop up on kill_stream.py

### ISSUE THREAD

**Issue by royalchinook** [blacktwin/JBOPS#149]
The Kill_stream.py script is working well for me on killing paused streams but every time someone pauses a stream I get a pop up Python cmd window on my screen.  Is there a way to have that come up in the background, minimized or not at all?  Thank you!

**Comment by blacktwin** [comment]
Yes. Add `pythonw` to the beginning of your argument string. 
So:
`pythonw  --jbop paused --interval 30 --limit 600 --sessionId {session_id} --killMessage Your stream was paused for over 10 minutes and has been automatically stopped for you.`
