### ISSUE TITLE
[REQUEST] Notification

### ISSUE THREAD

**Issue by Foebik** [blacktwin/JBOPS#15]
I know we can get notified of when a pause situation happens. 
I was wondering if the script actually kills a transacode, can we get a notification in regards to that action?

**Comment by blacktwin** [comment]
Yeah. You could use [PlexPy's](https://github.com/JonnyWong16/plexpy/blob/master/API.md#notify) `notify` to have PlexPy handle the notification. Use what ever notification agent you want and set it up in PlexPy. 

If you would want more flexibility (PlexPy's `To:` is static) in who/what receives the notification you can try and find a python module to simply the task.

**Comment by blacktwin** [comment]
Try [this](https://github.com/blacktwin/JBOPS/blob/master/killstream/kill_trans_pause_notify.py).

**Comment by blacktwin** [comment]
@Foebik Did script above work out for you? Please close if it did.
