### ISSUE TITLE
Docker help

### ISSUE THREAD

**Issue by bpersino** [blacktwin/JBOPS#150]
If I am using a docker version of tautulli, is there a way to get the script to work with docker?  Does anybody have a guide on how to do this?

**Comment by Arcanemagus** [comment]
Just like with any other installation you simply need to place the script somewhere Tautulli can see it. The only additional part for Docker is that you can either put it under `/config`, or add a new volume for the scripts.

**Comment by bpersino** [comment]
But most of the script require "requests" to be installed.  It appears that tautulli has plexapi already bundled, but does it have "requests" installed by default? 
http://docs.python-requests.org/en/master/user/install/#install
