### ISSUE TITLE
Admin Exemptions 

### ISSUE THREAD

**Issue by Foebik** [blacktwin/JBOPS#151]
Sorry if this has been discussed before. I'm updating to these new scripts, the ones I have are quite old. I currently user the kill stream for both being paused too long and for more than 1 IP. 

How can I make myself, the admin, exempt from those?

**Comment by Arcanemagus** [comment]
Kill stream is meant to be controlled entirely by conditions in Tautulli. In this case you would add a condition along the lines of `User name` | `is not` | `Foebik`.

**Comment by Foebik** [comment]
That makes sense... I'll give that a try. Thank you.
