### ISSUE TITLE
[Request] Add parameter that limits notifications to episodes aired in last n number of days

### ISSUE THREAD

**Issue by bendloewen** [blacktwin/JBOPS#152]
Would it be possible to add a parameter and logic gate to this script so that notifications will only be sent out if the episode has a recent air date? This would be helpful so users don't receive a TON of email notifications when I add additional but older seasons of an existing show on my server that they have already watched.

**Comment by blacktwin** [comment]
The simple, although loose, solution is already available. Use the Condition for Year or Release/Air Date.
![image](https://user-images.githubusercontent.com/22177672/56133059-8c2d0700-5f59-11e9-9806-4caab05d0a17.png)

Each of these Conditions have the `Greater than` or `Is` operator. I'd suggest using the Year Condition as it's unlikely that 2 new seasons would be released in the same year. 
`Year | Is | 2019` Would only allow notification of recently added content from this Year.

The scripting solution(s) could vary. You could send the notification to a script to check the release/air date then send a  [`notify_recently_added`](https://github.com/Tautulli/Tautulli/blob/master/API.md#notify_recently_added) and select the desired notifier ID. Or a cron/task scheduled script to update your [notification's conditions](https://github.com/Tautulli/Tautulli/blob/master/API.md#set_notifier_config) to `Release Date | Greater than | 2019-04-13` (-2 days from today).

**Comment by blacktwin** [comment]
@bendloewen Please try. You'll need another notification agent setup to send accepted items to.
