### ISSUE TITLE
limiterr.py applied for specific shows?

### ISSUE THREAD

**Issue by nebbles** [blacktwin/JBOPS#156]
Currently unsure how I could set the `limiterr.py` script to only allow one episode of a particular show to be viewed per day. So far:

`--jbop limit --username {username} --sessionId {session_id} --grandparent_rating_key {grandparent_rating_key} --limit plays=1 --today --killMessage "only one episode a day!"`

But unsure of how to apply this to only one show (I have gathered the necessary `grandparent_rating_key` from the logs for the desired show). Is the possible in its current form or would this be a feature request?

**Comment by nebbles** [comment]
I foolishly momentarily forgot about conditions...

**Comment by blacktwin** [comment]
Remember you can use the condition logic to group users with shows. Or just duplicate the agent and chance the conditions, once you have one setup.
