### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Nihar20** [blacktwin/JBOPS#162]
How to recover KeyError : 'auth'. Thanks in advance

**Comment by blacktwin** [comment]
wat? Context please

**Comment by Nihar20** [comment]
I am try to use playlist_manager.py in that I am getting error at auth key.
When I got key from your config.ini then here I am not getting solution of
this.
 I do not understand what to enter in server_baseurl, server_token,
tautulli_baseurl and tautulli_apikey.

**Comment by blacktwin** [comment]
Yes the `auth` error is related to the CONFIG.ini which you can choose to use or not use. For ease of use lets just forget about the CONFIG.ini for now.

In the script you'll need to add the following information:
```python
PLEX_URL = ''
PLEX_TOKEN = ''
TAUTULLI_URL = ''
TAUTULLI_APIKEY = ''
```
Follow this [link ](https://github.com/blacktwin/JBOPS/blob/master/README.md#common-variables)on the Readme page to find these values.

Should look something like this:
```python
PLEX_URL = 'http://127.0.0.1:32400'
PLEX_TOKEN = 'ruriIadofdaMnAdk987'
TAUTULLI_URL = 'http://127.0.0.1:8181'
TAUTULLI_APIKEY = 'kldaf89a8fjidoas8jkla88'
```

**Comment by Nihar20** [comment]
Thank you so much

**Comment by blacktwin** [comment]
Working now?

**Comment by Nihar20** [comment]
Yes
