### ISSUE TITLE
Remove Inactive Users script issue

### ISSUE THREAD

**Issue by irodimus** [blacktwin/JBOPS#163]
I've started to use the remove_inactive_user script (commit 54bdba174c2250eaef8ba519e9dad4a4bbb532c2) and was able to do the dry run, showing me what users have been inactive. I decided to actually remove users and set DRY_RUN to false. The output result was as expected but after looking at my users in Plex, I saw that no changes were made with users who the script said it was unsharing.

The only thing I noticed that could be causing an issue is that the script displays the friendly names from Tautulli, which I use for my users there. Plex has their own usernames or email and I can't tell if the names aren't matching between Tautulli and Plex.

**Comment by blacktwin** [comment]
The script pulls the user_ids from Plex and checks the ID number against Tautulli. The IDs are unique to the user. 

Have you refreshed or cleared cache on your browser? If you ran the script while having your browser opened to your Plex IP:PORT or plex.tv then you may need to refresh or clear cache in order to see the changes. Also did the script output that users were unshared (exist but no shared libraries) or removed (completely removed)?

@DirtyCajunRice the author.

**Comment by irodimus** [comment]
I thought it might be cache at first so I did refresh the web page. When that didn't work, I tried a different browser. The output from the script shows that the inactivity is passed the unsharing limit I've set and says Unsharing. The user in this case has two libraries being shared. If i rerun the script, it gives the same output . I normally use my local Plex/Web but I've checked on plex.tv to be sure with same result.

I thought maybe it was my Plex token, but it's one I've used for other scripts and if it was wrong, I would think I'd get an error about it.

**Comment by irodimus** [comment]
In an effort to try to troubleshoot this issue, I went ahead and manually unchecked all the user's shares and reran the script. I got this:
```
Traceback (most recent call last):
  File "remove_inactive_users.py", line 116, in <module>
    ACCOUNT.updateFriend(PLEX_USERS[UID], SERVER, removeSections=True)
  File "/usr/local/lib/python2.7/site-packages/plexapi/myplex.py", line 283, in updateFriend
    response_servers = self.query(url, self._session.delete, json=params, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/plexapi/myplex.py", line 176, in query
    raise BadRequest('(%s) %s %s; %s' % (response.status_code, codename, response.url, errtext))
plexapi.exceptions.BadRequest: (404) not_found https://plex.tv/api/servers/20253b4dc5cce18dc752eb4dfeebf9eb9eeea237/shared_servers; <!DOCTYPE html> <html> <head>   <title>The page you were looking for doesn't exist (404)</title> <link href="/assets/errors.css" media="screen" rel="stylesheet" type="text/css" />   <script type="text/javascript">     var _gaq = _gaq || [];     _gaq.push(['_setAccount', 'UA-6111912-23']);     _gaq.push(['_setDomainName', 'plex.tv']);     _gaq.push(['_trackPageview', '/404?url=' + window.location.pathname]);     (function() {       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);     })();   </script> </head>  <body> <div class="block">   <div class="dialog">   	<h1>Oops; a 404 error...</h1>     <h2>That's "page not found" in human language.</h2>     <p>You may have mistyped the address or the page may have moved.<br/>   	  <a href="/">Let us take you to the main page</a> and we can start all over again, shall we?     </p>   </div> </div> </body> </html>
```
I'm not sure if that helps or if that's a bug.

**Comment by DirtyCajunRice** [comment]
That is nothing to do with the script, but an error connecting to plex. also that script is for python3 fyi. also having the output of the first run would be helpful

**Comment by irodimus** [comment]
I just ran it using python3 as I did not try that and while also gave me the same output as python2, the result was the same. The only output I have is the result when it is run:
```
$ python3 remove_inactive_users.py
User1 was last seen 490 days, 20 hours, 18 minutes, 24 seconds ago, and exists in Tautulli but does not exist in Plex. Skipping.
User2 was last seen 232 days, 22 hours, 53 minutes, 24 seconds ago, and exists in Tautulli but does not exist in Plex. Skipping.
User3 was last seen 209 days, 20 hours, 24 minutes, 57 seconds ago, and has reached their inactivity limit. Unsharing.
```
First two are correct and User3 is the one I'm running into the issue with.

**Comment by blacktwin** [comment]
In Plex does the user exist? Do they have libraries shared to them? All libraries should be unchecked but the user will still exist.

**Comment by irodimus** [comment]
User3 does exist in both Tautulli and Plex. There are only two libraries shared with that user but they don't get unshared after running the script.

**Comment by blacktwin** [comment]
@irodimus the last line of the script:

`ACCOUNT.updateFriend(PLEX_USERS[UID], SERVER, removeSections=True)`

change to:

`ACCOUNT.updateFriend(PLEX_USERS[UID], SERVER, SECTIONS, removeSections=True)`

run and confirm that that works.

**Comment by irodimus** [comment]
Just tested this and this change works. Thanks!

**Comment by blacktwin** [comment]
I think this issue can be closed. For reference the issue was with documentation not matching function with the plexapi. See related issue from [plexapi ](https://github.com/pkkid/python-plexapi/issues/346).
