### ISSUE TITLE
[BUG] find_unwatched.py crash on excess amount of files

### ISSUE THREAD

**Issue by AppleMaster** [blacktwin/JBOPS#164]
When running [utility/find_unwatched.py](https://github.com/blacktwin/JBOPS/blob/master/utility/find_unwatched.py) i get the below stacktrace:
```
Rating_key failed: {e}
Library media info failed: {e}
Tautulli API 'get_new_rating_keys' request failed: '0'.Traceback (most recent call last):
  File "find_unwatched.py", line 142, in <module>
    show_lst += get_new_rating_keys(x.rating_key, x.media_type)
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "find_unwatched.py", line 147, in <module>
    print("Rating_key failed: {e}").format(e=e)
AttributeError: 'NoneType' object has no attribute 'format'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "find_unwatched.py", line 150, in <module>
    print("Library media info failed: {e}").format(e=e)
```

This only occurs if I specify my library named `TV Shows` which has about 7500 episodes - so I assume there is some correlation going on. 
Advice/Tips/Fix would be appreciated.

**Comment by blacktwin** [comment]
Library size shouldn't matter as it's only looking back through Tautulli's watch history as far as you've specified.  How far back did you try to look? Can you share your [Tautulli log file](https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support#how-can-i-share-my-logs)?

**Comment by AppleMaster** [comment]
I was trying to look back 8 months, but I think the error here was occurring because the plex library itself hasn't existed for that long- upon setting TFRAME to the default of 6 months the script runs successfully.
