### ISSUE TITLE
[BUG] Notify_User_Favourites

### ISSUE THREAD

**Issue by Runear** [blacktwin/JBOPS#165]
Hey!

First up, thanks for your work on these, saw them ages ago but only just got around to using them to try and stem some unwanted behaviour.

In the notify_user_favourites script, in the resulting email it doesnt appear to handle apostrophes very well. For example, this is the result of one of the recent ones.

`Torres relies on his team?s investigative skills after he wakes up on a dilapidated fishing boat, covered in blood and unable to remember the last 12 hours. `

I had a brief look at the script and it looks like it just takes the input from Tautulli, is this something that can be fixed on the script side?

Its a "?" in Outlook and a funky looking thing on my phone.

Let me know if you need anything more.

Edit: A side question too, I use Direct Send (detailed [here](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3)) for email from my various self hosted services, but it doesn't appear to work with the scripts. Am I doing something silly? It requires port 25, ssl and no auth, so I am setting the port and leaving username and password empty but get:

`smtplib.SMTPException: SMTP AUTH extension not supported by server.`

**Comment by blacktwin** [comment]
Just tested with hotmail/Outlook and can confirm that it does show a `?` in place of at `'`. The funky looking thing is probably the poster image being blocked. Tautulli's email agent handles `'` properly with Outlook, though. 

One solution is to use a different email client. Another, is to use Tautulli's handling of [Email](https://github.com/Tautulli/Tautulli/blob/master/plexpy/notifiers.py#L1315-L1339). 

I don't intend on fixing this. The script is rather old and written before Tautulli (written for PlexPy). I think the better solution would be to lean on Tautulli's already robust notification agents.

As for your second question, I have no idea.

**Comment by Runear** [comment]
No problem, I can't really use the inbuilt ones because as far as I know there is nothing inbuilt to only notify on shows you watch.

Thanks for your time anyway.

**Comment by blacktwin** [comment]
You can setup a notification agent to do that. Trigger for Recently Added, list the shows you want notified for, add whatever text you want to the message, if it's an email agent then just set it up to send to whatever user you think likes the shows listed.
