### ISSUE TITLE
Webhook notification failing to post to discord

### ISSUE THREAD

**Issue by Androkiller** [blacktwin/JBOPS#166]
Found a closed issue.
Discord Rich Text Not Working #132
I made the same mistake in using a Discord Notification Agent instead of Webhook agent.
However now that it has been changed it fails completely to post the notification.
![notfication error](https://user-images.githubusercontent.com/25016806/59038728-69d5ac80-886b-11e9-8268-b3026b8fcdbe.png)
Dont get whats wrong with the agent, I pasted in the webhook url from discord and changed the method to POST

**Comment by Arcanemagus** [comment]
Your Tautulli Public URL is incorrect (`/tautulli`), it should be the _full_ URL to access Tautulli publicly.

Discord rejects any message with an invalid `url` field with the _very_ uninformative `400 - BAD REQUEST` message.

**Comment by Androkiller** [comment]
![image](https://user-images.githubusercontent.com/25016806/59091741-e322dd00-8907-11e9-8c60-b7b883f1271d.png) 
I do have the public url set and it is correct.
I assume that if i am using organizr auth for the subfolder then this would be causing the issue then?

**Comment by Androkiller** [comment]
had to allow api through the reverse proxy without any auth from organizr
