### ISSUE TITLE
Plex LIFX error colorthief

### ISSUE THREAD

**Issue by Septan** [blacktwin/JBOPS#167]
Tautulli Notifiers :: Script error:     Traceback (most recent call last):         File "C:\Users\ME\Downloads\Compressed\JBOPS-master\fun\plex_lifx_color_theme.pyw", line 249, in <module>             palette = color_thief.get_palette(color_count=num_colors, quality=color_quality)         File "C:\Python27\lib\site-packages\colorthief.py", line 77, in get_palette             cmap = MMCQ.quantize(valid_pixels, color_count)         File "C:\Python27\lib\site-packages\colorthief.py", line 218, in quantize             raise Exception('Wrong number of max colors when quantize.')     Exception: Wrong number of max colors when quantize.
--

**Comment by philosowaffle** [comment]
Could you please post your configuration section found [here](https://github.com/blacktwin/JBOPS/blob/master/fun/plex_lifx_color_theme.pyw#L31)?  You can exclude the sensitive information such as player UUID's and APIKey.

**Comment by Septan** [comment]
`# List of Player Id's that should trigger this script.  In order to identify your
# players UUID, enter a dummy id, enable the script, and start playing some media
# on the target device.  In the Tautulli logs, search for `plex_lifx`, the UUID should
# appear there.
PlayerUUIDs = ""

# LIFX API Key
APIKey = ""

# Bulb Brightness when media is playing
Brightness = .25

# Transition duration
Duration = 3.0

# Number of colors to be used across your lights
NumColors = 1

# How closely the colors should match the media thumbnail, 10 is the highest
ColorQuality = 10

# Default theme to restore lights to on media pause/stop
DefaultPauseTheme = "Basic"

# Default theme to set lights to when media poster fails
DefaultPlayTheme = "Blue"

# Lights that should be controlled by this script, the order the lights are specified in will effect the order in which colors are applied.
# You can play around with different light orders until you find one that spreads the colors how you like.  You can also configure more
# or fewer colors above (see 'NumColors') in order to increase or decrease the amount of color diversity across lights.
Lights = "PlexServer"`

**Comment by philosowaffle** [comment]
[PR](https://github.com/blacktwin/JBOPS/pull/168) issued with the fix. In the meantime, change `NumColors` to be something greater than 1.

**Comment by blacktwin** [comment]
Assuming you've tested and it works, as I have never used this script and do not have the hardware necessary.
