### ISSUE TITLE
[Request] Weekly limiter

### ISSUE THREAD

**Issue by sotiris-bos** [blacktwin/JBOPS#172]
Thanks once again for the amazing work!

Is there any chance we can have a total time played limit for each week?

**Comment by blacktwin** [comment]
Whelp that was supposed to be a PR but guess it went to master. @sotiris-bos can you please test and confirm that it's working for you.

There is a new argument to use. `--days`.
`--days 0` will have the script only check history for today,  
`--days 1` will have the script only check history for today and yesterday,
`--days 7` will have the script only check history for the last week,
and so on.

**Comment by blacktwin** [comment]
Examples added to #194

**Comment by blacktwin** [comment]
So this solution would be for a rolling week, month, date range. As each day the date range will move forward. Not sure if that is what you were looking for or not.
