### ISSUE TITLE
find_unwatched.py not respecting the timeframe configured

### ISSUE THREAD

**Issue by millermarkj** [blacktwin/JBOPS#177]
I'm trying to clean up my library of content that hasn't been watched, but find_unwatched.py is trying to remove stuff that aired last week:
```
root@bce53a934494:/# find_unwatched.py 
Showname: Chapter 22 (13165) was added Tue Jul  9 00:07:38 2019 and hasnot been watched. 
 File location: /tv/Showname/season03/Showname - S03E03 - Chapter 22.mkv
Showname: Chapter 22 (13165) was added Tue Jul  9 00:07:38 2019 and hasnot been watched. 
 File location: /tv/Showname/season03/Showname - S03E03 - Chapter 22.mkv
Showname: Chapter 21 (12956) was added Mon Jul  1 23:08:21 2019 and hasnot been watched. 
 File location: /tv/Showname/season03/Showname - S03E02 - Chapter 21.mkv
Showname: Chapter 21 (12956) was added Mon Jul  1 23:08:21 2019 and hasnot been watched. 
 File location: /tv/Showname/season03/Showname - S03E02 - Chapter 21.mkv
Other Showname: Chapter Ninety-Five (12916) was added Wed Jun 26 22:43:48 2019 and hasnot been watched. 
 File location: /tv/Other Showname/season05/Other Showname - S05E14 - Chapter Ninety-Five.mkv
```

**Comment by blacktwin** [comment]
Works for me. Have you modified the script at all? Do you have the latest version?

**Comment by millermarkj** [comment]
No modifications other than the variables at the top.

**Comment by blacktwin** [comment]
Did you change the [`TFRAME`](https://github.com/blacktwin/JBOPS/blob/master/utility/find_unwatched.py#L13) variable?

**Comment by millermarkj** [comment]
Nope. Still at the default, ~6 months.

**Comment by blacktwin** [comment]
Can you add this:

```python
TODAY = time.time()
print(TODAY)  # <-- this
```
Please confirm that the TODAY's time is correct? Plug in this out to this [epoch converter](https://www.epochconverter.com/) to confirm.

**Comment by millermarkj** [comment]
Running tautulli using the linuxserver.io container with python2.7 and can confirm the date is correct:
```
root@bce53a934494:/# python
Python 2.7.16 (default, May  6 2019, 19:28:45) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import datetime
>>> print datetime.now()
2019-07-29 14:41:18.778700
>>> import time
>>> print time.strftime("%m/%d/%Y, %H:%M:%S")
07/29/2019, 14:45:00
```

**Comment by blacktwin** [comment]
I cannot reproduce this issue. Others I've asked to test could not reproduce this issue.

**Comment by millermarkj** [comment]
I also have no idea. There are other weird things going on with the script which I can only attribute to it being run inside a container? I ended up adding a check where it strips any unwatched items containing the string "2019", which is good enough for me to clean the library.

**Comment by hacktek** [comment]
I know this is closed but it just happened to me:

$ ./find_unwatched.py
xxx: Episode 6 (966420) was added Thu Aug 27 15:25:22 2020 and has not been watched.
 File location: /mnt/xxx/xxx.mkv
xxx: Episode 6 (966420) was added Thu Aug 27 15:25:22 2020 and has not been watched.
 File location: /mnt/xxx/xxx.mkv

Also as you can see it's duplicating each entry. Guess I'll dump the results to a file and will then check the date a second time but it's kind of weird.

I'm not running this in a container, tautulli is a container though.

**Comment by blacktwin** [comment]
How is this related to this issue? Why not create a new issue and follow the issue template.
