### ISSUE TITLE
I keep getting--jbop is required when limiting streams

### ISSUE THREAD

**Issue by foizashik** [blacktwin/JBOPS#180]
I keep getting this and i saw another similar issue but didn't seem to have any solution. Am i doing something wrong in my end? i attached the log. I applied the condition according to your example for limiting streams. 
![Capture](https://user-images.githubusercontent.com/34486426/62265284-9b916c80-b3f1-11e9-982a-894183357617.PNG)

**Comment by foizashik** [comment]
little update: it works when i put no usernames and just leave the copy and paste the script as it, but that applies to everyone..Is it not possible to setup for specific usernames?

**Comment by blacktwin** [comment]
What example are you using? You shouldn't be editing the script at all. You control how the script works and targets by using the arguments and conditions.

**Comment by blacktwin** [comment]
No response, closing.

**Comment by skube** [comment]
FWIW, I had the same error showing up and found that I had formed one of the arguments incorrectly:
```diff
- --notify=1
+ --notify 1
```
