### ISSUE TITLE
Potential dependency conflicts between JBOPS and urllib3

### ISSUE THREAD

**Issue by NeolithEra** [blacktwin/JBOPS#181]
Hi, _**JBOPS**_ directly and transitively introduced multiple versions of urllib3.

As shown in the following full dependency graph of  **_JBOPS_**, **_JBOPS_** requires _**urllib3**_ (the latest version), while the installed version of **_requests_**(2.22.0) requires _**urllib3>=1.21.1,<1.26**_.

According to pip's “first found wins” installation strategy, _**urllib3 1.25.3**_ is the actually installed version.  

Although the first found package version _**urllib3 1.25.3**_ just satisfies the later dependency constraint (_**urllib3>=1.21.1,<1.26**_), it will lead to a build failure once developers release a newer version of urllib3.

### Dependency tree--------
```
JBOPS(version range:)
| +-plexapi(version range:)
| | +-requests(version range:)
| | | +-chardet(version range:>=3.0.2,<3.1.0)
| | | +-idna(version range:>=2.5,<2.9)
| | | +-urllib3(version range:>=1.21.1,<1.26)
| | | +-certifi(version range:>=2017.4.17)
| | +-tqdm(version range:)
| | +-websocket-client(version range:)
| +-requests(version range:)
| | +-chardet(version range:>=3.0.2,<3.1.0)
| | +-idna(version range:>=2.5,<2.9)
| | +-urllib3(version range:>=1.21.1,<1.26)
| | +-certifi(version range:>=2017.4.17)
| +-urllib3(version range:)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Fix your direct dependencies to be **_urllib3>=1.21.1,<1.26_** and **_requests==2.22.0_**, to remove this conflict. 

2.	Remove your direct dependency urllib3, and use urllib3 transitively introduced by request.

  I have checked the above two revisions will not affect your downstream projects now.

Build a good dependency ecosystem for python projects is our common goal ^_^.

@blacktwin   May I pull a request to solve this issue?

**Comment by blacktwin** [comment]
Thanks for looking into this. Looks like 
```python
requests.packages.urllib3.disable_warnings()
``` 
will resolve the issue. Replacing:
```python
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```

**Comment by NeolithEra** [comment]
@blacktwin  Thanks for your feedback. This issue will lead to build failures rather than runtime errors. I think the better solution is revising your requirement file.

**Comment by blacktwin** [comment]
The code snip above is only use of the urllib library. It's found in multiple scripts so they'd all need updated. Then the requirement for urllib would not exist and can be removed. 

Is that not what your second solution?
