### ISSUE TITLE
Conditions not clear. What to specify in conditionbox 1.

### ISSUE THREAD

**Issue by SilentDecode** [blacktwin/JBOPS#183]
https://github.com/blacktwin/JBOPS/blob/5d8d40d6eed94bbd7410b0e6f4c5a0043d08c33d/killstream/kill_stream.py#L30

Conditions not clear. What to specify in conditionbox 1.
Script is not triggering, whatever I do.

Tautulli specifies it as:
Set Conditions: [{parameter} | {operator} | {value} ]

**Comment by Arcanemagus** [comment]
There are _many_ different examples of the conditions you can use and how they will change how the script works in the readme:
https://github.com/blacktwin/JBOPS/blob/master/killstream/readme.md

**Comment by SilentDecode** [comment]
But there is not an valid option for the "Kill streams paused for a custom time" script. There is no specific condition specified in the readme section.

What do I need to fill in there? And can they alter the readme, so it would be more clear for other users?

**Comment by blacktwin** [comment]
Follow the example: https://github.com/blacktwin/JBOPS/blob/master/killstream/readme.md#kill-streams-paused-for-a-custom-time

A condition is not required. Conditions are used to isolate the target(s) you want. If it's a blanket rule for all then no conditions are needed. These are examples to get you started, it's up to you to fine tune the conditions and conditional logic to your needs.
