### ISSUE TITLE
Sometime a stream is "Transcoding" but 1 second after he show "Direct Play", is it possible to delay the script execution of X seconds?

### ISSUE THREAD

**Issue by coolfarmer** [blacktwin/JBOPS#190]
**Sometime** someone start a stream and it show "Transcode" on Tautulli but 1 second after that it change to Direct Play, it's enough to trigger KillStream and my conditions. I would know if it's possible to delay the script's execution?

Example with the trigger "Playback start", it could be like that :
`--jbop stream --username {username} --sessionId {session_id} --serverName {server_name} --notify 25 --delay=2000 --killMessage 'Hey!'`

With --delay, the script will wait 2000ms after the playback start THEN it will do is thing.

Sorry for my english, not my main language.

**Comment by blacktwin** [comment]
Use `Transcode Decision Change` trigger instead. Usually streams will attempt to Direct Play then Transcode, not the other way around.

**Comment by coolfarmer** [comment]
I use both and I can't remove Playback Start because if a user start his stream in 328p 0.7 mbps, it will not trigger the transcode decision change because it is already transcoding.

My goal is to block all stream that is not in Original quality, so my condition use the variable {quality_profile} not contain "Original". But like I said in my first post, sometime the video start in a tanscoding state then 1 second later switch to Original.

**Comment by blacktwin** [comment]
Please post a link to your complete Tautulli logs on Gist.
### How to Find Your Logs

View the Tautulli logs by clicking on "View Logs" in the settings menu. Click the "Download logs" button to save a copy of the log file. If Tautulli is unable to start, then the tautulli.log file is located in the logs folder where Tautulli is installed. Paste the logs on Gist and post the link here, do not upload the file as an attachment.

Also, we need to know the client and do they have automatically adjust quality?

**Comment by coolfarmer** [comment]
I don't know if my log will be very usefull but here is the Gist:
https://gist.github.com/coolfarmer/0a7c75466efefe32bd9b90a8bb11c20a

> Also, we need to know the client and do they have automatically adjust quality?

My users are all in "Original" quality, no auto adjust. The problem that some streams are starting in transcode then switch to direct play do not happen every time, very difficult to reproduce, but "easy" to see when KillStream.py kill the stream (I log all the killed stream in a private discord channel).

**Comment by blacktwin** [comment]
What are the conditions for `notifier 31`? I'm assuming thats your script agent that killing streams.

**Comment by coolfarmer** [comment]
This is what I have for notifier 31: https://i.imgur.com/x5I2Ld4.png
`Video Resolution is 4k AND Quality profile is not original`

I have 2 like that, a notifier for 4k (id:31) and another one (id:22) who's blocking all streams that contain 480p, 328p, 240p and 160p in {quality_profile}. Like that the only stream autorized are 720p and 1080p.

I can not just only use the {transcode_decision} because sometime Plex just need to transcode a little bit, like changing the media container (ex.: mkv to mp4), or when the audio or substile need the transcoder, these tasks are not crazy  in terms of CPU.

**Comment by blacktwin** [comment]
Why not use  [ `Video Decision` | `is` | `transcode` ] ? You can isolate what is [transcoding](https://github.com/blacktwin/JBOPS/tree/master/killstream#conditions-considerations).

**Comment by coolfarmer** [comment]
I'm already using that too, but in my problem transcoder is up at 100% (video & audio) THEN it switch to Direct play. So using video decision will trigger the stream to be killed.

Too bad, I close, thanks for your help.
