### ISSUE TITLE
Error: Tautulli Notifiers :: Invalid Webhook json header data: No JSON object could be decoded

### ISSUE THREAD

**Issue by 338lm** [blacktwin/JBOPS#198]
I'm using the Kill Stream script with the 'Limit User streams to one unique IP' config. I added the Slack argument to the end of the Concurrent Streams argument, like this. 
--jbop stream --username {username} --sessionId {session_id} --killMessage 'You are only allowed to stream from one location at a time.' --notify 7 --richMessage slack 
This was working in the past, but stopped sending Slack notifications about 2 weeks ago (I think). Currently, the stream is being killed successfully, but there is no Slack notification any more. The Tautulli log displays this error - 

> Tautulli Notifiers :: Invalid Webhook json header data: No JSON object could be decoded 

The same Slack webhook notification agent is working correctly for other notifications, such as concurrent streams from the same user. I've also updated kill_stream.py recently. 

More from the log: 

> 2019-11-20 16:58:39 | DEBUG | Tautulli Notifiers :: Script returned:    Tautulli API cmd 'notify' failed: Notification failed.
> -- | -- | --
> 2019-11-20 16:58:39 | DEBUG | Tautulli Notifiers :: Subprocess returned with status code 0.
> 2019-11-20 16:58:39 | ERROR | Tautulli Notifiers :: Invalid Webhook json header data: No JSON object could be decoded
> 2019-11-20 16:58:39 | INFO | Tautulli NotificationHandler :: Preparing notification for notifier_id 7.
> 2019-11-20 16:58:39 | INFO | Tautulli Pmsconnect :: Terminating session 77 (session_id 6815d0ac39828077-com-plexapp-android).
> 2019-11-20 16:58:39 | INFO | Tautulli Config :: Writing configuration to file

**Comment by blacktwin** [comment]
@338lm Please download the script again as there was a recent update. that should fix your issue.

**Comment by 338lm** [comment]
@blacktwin thanks for the update, but now it's not killing the stream with the latest kill_stream.py 
I received the following error in the Tautulli log

2019-11-25 16:24:20
 | ERROR | 
Tautulli Notifiers :: Script error:        File "C:\Tautulli Scrips\kill_stream.py", line 7            <!DOCTYPE html>            ^    SyntaxError: invalid syntax
-- | -- | --

**Comment by blacktwin** [comment]
Looks like your filepath changed.

**Comment by 338lm** [comment]
@blacktwin yeah, sorry, I figured out why it stopped killing the stream, and fixed that. 
Now it's killing the stream again, but I'm still getting the error "Tautulli Notifiers :: Invalid Webhook json header data: No JSON object could be decoded"

**Comment by 338lm** [comment]
> 
> 2019-11-25 16:42:40 | DEBUG | Tautulli Notifiers :: Script returned:    Tautulli API cmd 'notify' failed: Notification failed.
> -- | -- | --
> 2019-11-25 16:42:40 | DEBUG | Tautulli Notifiers :: Subprocess returned with status code 0.
> 2019-11-25 16:42:40 | ERROR | Tautulli Notifiers :: Invalid Webhook json header data: No JSON object could be decoded
> 2019-11-25 16:42:40 | INFO | Tautulli NotificationHandler :: Preparing notification for notifier_id 7.
> 2019-11-25 16:42:40 | INFO | Tautulli Pmsconnect :: Terminating session 199 (session_id 0c2a4483e81f090b-com-plexapp-android).
> 
>

**Comment by blacktwin** [comment]
Looks like this is dependent on an update to Tautulli. See #199 . Though it's been merged it's waiting on a Tautulli update that exists in the nightly branch.
