### ISSUE TITLE
is there a way to add Create kill_trans_pause_notify.py

### ISSUE THREAD

**Issue by seanvree** [blacktwin/JBOPS#20]
Hey brother, good addition on the Create kill_trans_pause_notify.py.  

is there a way to add in the "WAIT" function into this? 

Thx,

**Comment by blacktwin** [comment]
Of course.

**Comment by blacktwin** [comment]
Try [this](https://gist.github.com/blacktwin/5df100a3641789dfe64cddf655685bfe).

**Comment by seanvree** [comment]
@blacktwin  will do brotha! thanks!
