### ISSUE TITLE
Discord notifications not working

### ISSUE THREAD

**Issue by DillonsFlix** [blacktwin/JBOPS#202]
I am new to JBOPS.  I successfully setup Killstream to stop anyone using more than 2 concurrent streams.  I would like a discord notification whenever the script agent runs.  I have a webhook on my discord server which is tested as working.  I setup a webhook agent in tautulli as per the instructions.  I added the required arguments to the script agent. My arguments under "Playback Start" look like this.  --jbop stream --username {username} --sessionId {session_id} --killMessage 'You are only allowed 2 streams.' --notify 35 --richMessage discord --debug

Whenever it tires to send notification I get the following in the logs.  Tautulli Notifiers :: Invalid Webhook json header data: No JSON object could be decoded

Am I doing something wrong?

**Comment by blacktwin** [comment]
Their is an update to the script and a pending update to Tautulli (currently in nightly) that should fix this. See #201 and this [comment](https://github.com/blacktwin/JBOPS/issues/201#issuecomment-561846424).
