### ISSUE TITLE
weekly_stats_reporting.py returns incorrect data.

### ISSUE THREAD

**Issue by marcusronnback** [blacktwin/JBOPS#207]
**Describe the bug**
`weekly_stats_reporting.py` returns incorrect data. 
An example is a user that has 22hrs 17min watched as seen on the Tautulli Dashboard, but using this script has 158hrs 0min. This is if i use the standard 7 days.

[weekly_stats_reporting.py](https://github.com/blacktwin/JBOPS/blob/master/reporting/weekly_stats_reporting.py)

**To Reproduce**
1. Run the script as usual, use `--days 1` for easier debug. 
2. Check the data that is returned
3. Notice the incorrect data.

**Expected behavior**
I expect the values to correspond to the actual watchtime for that user. I often see values tenfold of the actual value.

**Software:**
 - OS: Windows 10 (10.0.14393)
 - Python Version: 2.7.15
 - Tautilli version: 2.1.44

**Additional context**
`--days 0` will return correct data.

**Comment by blacktwin** [comment]
Please try this updated version. The list used to collection user duration was not resetting and was constantly building on top itself. Thats been fixed. Tautulli dashboard 1 day is 24 hours and not the actual day of today. So 0days is not 1:1 to Tautulli dashboard. 7 days seems to be correct.

**Comment by marcusronnback** [comment]
Hello! Thanks for the quick fix, unfortunately it does not seem to work for me :/
I re-cloned the file and only updated the lines 23-26 and 29, (api, url etc. so nothing is excluded) but it still gives wierd data as seen in [this picture](https://imgur.com/lY4yESl). Screenshot taken at ~03:40 AM in the day. Please let me know if i can help you by supplying more data :)

**Comment by blacktwin** [comment]
Are you [excluding](https://github.com/blacktwin/JBOPS/blob/master/reporting/weekly_stats_reporting.py#L42) any libraries in the script? I've tested several different day variables (0, 1, 7, 3, 30) and they all return correct or close enough (Tautulli dashboard/history page round).

**Comment by marcusronnback** [comment]
No nothing is excluded.

**Comment by blacktwin** [comment]
I pushed another update but it shouldn't change your results as I did not change the calculation methods. I'm thinking I may just pull directly from the [Home Stats](https://github.com/Tautulli/Tautulli/blob/master/API.md#get_home_stats) instead of basically rerunning the calculations and apparently getting it wrong :).

**Comment by blacktwin** [comment]
@marcusronnback ok new update should fix your issue. Now it's pulling directly from the home stats api call as referenced above. Fixed time calculations. Added the ability to run the library refresh from the script, you'll still need to wait a while before running to get accurate library sizes. Framework is now included to allow for using with rich notifications with Discord or Slack.

Thanks for finding this issue. Let me know if it's fixed for you.
