### ISSUE TITLE
Issue: KeyError: 'Directory' when using plex_api_share.py 

### ISSUE THREAD

**Issue by tenknas** [blacktwin/JBOPS#208]
Sorry if this might be a noob question. I was trying to use the plex_api_share.py script to add everyone to new libraries. But when I execute it using the command` ./plex_api_share.py --allUser --allLibraries` I get the error bellow.

```
Traceback (most recent call last):
  File "./plex_api_share.py", line 295, in <module>
    movie_ratings += get_ratings_lst(movie)
  File "./plex_api_share.py", line 158, in get_ratings_lst
    ratings_keys = content.json()['MediaContainer']['Directory']
KeyError: 'Directory'
```
Tried googling what these all means but can't really find it. I'm trying to execute this remotely, the plex server is on another server, not sure if that is the cause. But I was able to execute the plex_api_invite.py script flawlessly. 

Any help will be greatly appreciated.

**Comment by blacktwin** [comment]
Do you have Plex Pass? Check if Plex's API service is down when you received the error. This could be the issue.

Sounds like a similar issue that was found in the forums. Here was the temporary [solution ](https://forums.plex.tv/t/how-do-i-see-which-users-a-particular-library-is-shared-with/539291/14)and possible explanation. This solution will disallow any Plex Pass related settings to be changed. 

`./plex_api_share.py --allUser --allLibraries`
Also, that command won't do anything. What did you want to do?

**Comment by tenknas** [comment]
I already did this `if plex.myPlexSubscription is False:` and I was able to do what I wanted to do which was to share newly added libraries to all the current users.

Just wondering where I went wrong with my setup and couldn't make it work. I have plex pass and so far I think the Plex API is working since I was able to add users using the plex_api_invite.py and share new libraries using the plex_api_share.py.

**Comment by blacktwin** [comment]
I don't think you did anything wrong, its something to do with pulling the ratings. If you want we can try to figure it out but I'd need you to run a couple tests as everything is working for me. [Here ](https://github.com/blacktwin/JBOPS/blob/ad47db65876ff9e0d0bfd9c723f345c9f8a10dba/utility/plex_api_share.py#L152-L160)is where it's pulling the information to collect all available ratings.

```python
def get_ratings_lst(section_id):
    headers = {'Accept': 'application/json'}
    params = {'X-Plex-Token': PLEX_TOKEN}
    content = sess.get("{}/library/sections/{}/contentRating".format(PLEX_URL, section_id),
                       headers=headers, params=params)

    ratings_keys = content.json()['MediaContainer']['Directory'] # here is where it errors out.
    ratings_lst = [x['title'] for x in ratings_keys]
    return ratings_lst
```

Set back `if plex.myPlexSubscription is True:`
Can you edit to this:

```python
def get_ratings_lst(section_id):
    headers = {'Accept': 'application/json'}
    params = {'X-Plex-Token': PLEX_TOKEN}
    content = sess.get("{}/library/sections/{}/contentRating".format(PLEX_URL, section_id),
                       headers=headers, params=params)

    ratings_json = content.json()
    print(ratings_json)
    # this ^^^^
    ratings_keys = content.json()['MediaContainer']['Directory']
    ratings_lst = [x['title'] for x in ratings_keys]
    return ratings_lst
```
Run the script with a the `-h` argument and the `ratings_json` should print out. 
`python plex_api_share.py -h`

Send me the output from the `ratings_json` print out.

**Comment by blacktwin** [comment]
Fix is in place.
