### ISSUE TITLE
delete watched tv

### ISSUE THREAD

**Issue by dejected1** [blacktwin/JBOPS#21]
I KNOW this is going to be something stupid, im just not sure what it wants. Im trying to setup the delete_watched_tv script. I loaded the scripts into a folder, pointed the scripts folder in plexypy and configured the settings i found in script. 

I got the rating key from the url of the show i was testing in plexpy. this is the show url page.  
IE: http://plexpywebsite.com/info?rating_key=51825

PLEXPY_APIKEY = '94875113e00211942ddf781b192553d0'  # Your PlexPy API key
PLEXPY_URL = 'http://192.168.2.197:8181/94875113e00211942ddf781b192553d0'  # Your PlexPy URL
SHOW_LST = [51825]  # Show rating keys.
USER_LST = ['dejected1 (Me)']  # Name of users

The log shows the following error: 

ERROR 
| PlexPy Notifiers :: Script error:     
Traceback (most recent call last):         
File "C:\JonnyWong16-plexpy-3742f33\Scripts\utility\delete_watched_TV.py", line 7, in             
import requests     
ImportError: No module named requests
-- | --

I didnt see any arguments listed in the script and this is the only script i was testing.

**Comment by blacktwin** [comment]
> ImportError: No module named requests

You need to install `requests`. [Use ](http://docs.python-requests.org/en/master/user/install/)`pip install requests`. 

Fix your `PLEXPY_URL` to: 
```python
PLEXPY_URL = 'http://192.168.2.197:8181/'
```

You can have PlexPy trigger this script but it's not looking for any arguments. It could be changed to. I would suggest running this manually or setup a cron/task to run it on a schedule.

**Comment by dejected1** [comment]
ok so i was off with this. On the plus side i know a lot more about python now.... Anyway,  I got it to work but you mentioned running this task as a cron task. I'm assuming that's not possible from within plexpy? How would i execute the script externally and still pull all the variables from plexypy that is needed? Or is there a way to setup a cron task in plexy py?  i tried running the .py outside of plexypy and of course that doesn't work. Any help would be appreciated.

**Comment by blacktwin** [comment]
> You can have PlexPy trigger this script but **it's not looking for any arguments**.

Just run it.

> i tried running the .py outside of plexypy and of course that doesn't work.

What doesn't work? Is there an error? What is the error?

The only thing the script looks at is the `SHOW_LST` & `USER_LST`. The script touches PlexPy, PlexPy isn't passing any arguments to the script, because the script isn't looking for any.

**Comment by dejected1** [comment]
so will things that require arguments from plexypy still run independently of plexpy. With the just run it mentality?

**Comment by blacktwin** [comment]
No. If the script is needs arguments to run, meaning PlexPy supplying the arguments or you supplying ei `python my_script.py arg1 arg2 arg3` then it will error out if you try to run it without the arguments if they are needed for the script logic ei `foo = sys.argv[1]`.

**Comment by dejected1** [comment]
ok i got it. thanks alot for the help.
