### ISSUE TITLE
Limit Reset After KillMessage

### ISSUE THREAD

**Issue by Fryeswitthat542** [blacktwin/JBOPS#212]
Hello,

Just wanted to say thanks for producing all this, but had a question about resetting the ep_watched section. I'd like to reset that to 0 every time a message appears. So in this real life scenario..Say i have limit plays to 6, once that 6 plays hit it sends the kill message and the user has to go back in to resume (Currently once it hits 6 it'll do it for each episode after). I'd like to reset that to 0 and then once a user watches another 6 episodes to redo that kill message. I've tried to add ep_watched=0 onto the "if ep_watched >= total_limit: section, but i'm pretty sure it resets it back to whatever it was based on history after that.

Any advice or guidance would be greatly appreciated!

Thanks!

**Comment by blacktwin** [comment]
What script? What example are you using?

**Comment by Fryeswitthat542** [comment]
I'm using the limitter.py - Specifically the _Limit user to an amount of Plays of a show during a time of day_, but not using the condition for time of day. Just the
"--jbop limit --username {username} --sessionId {session_id} --grandparent_rating_key {grandparent_rating_key} --limit plays=6 --delay 20 --killMessage "Are you still watching?"

Which works, but if they watch episode 7 or 8 - It still kills the streams so would like a way to reset the episode watched back to 0.

**Comment by blacktwin** [comment]
Then set your limit to 7 or 8 or the user waits the `--delay` time. The script will reset on the next day.

**Comment by Fryeswitthat542** [comment]
Thanks for getting back. I dont think im getting what my goal is preciously.  Currently if i have limit plays to 6, then your limit script will kill EACH play after 6. So it kills on play 7, 8 until that daily reset. Id like to reset on each kill and not based on day. 

User X watches 6 episodes then on the 7th gets the kill message, user continues and watches another 6 episodes and gets another kill message. 

Since people can watch more than 6-12 episodes a day.

**Comment by blacktwin** [comment]
As the script is currently written, that is not possible.

**Comment by Fryeswitthat542** [comment]
Would this be an easy addition (doesn't have to be for public use) or let me know what i would need to change to get this functionality?

**Comment by blacktwin** [comment]
Easy addition, kinda not kinda. You could have the script check the logs for prior runs from that user, create a separate file that the script logs to and check that file, update the agent config and increase the  limit then eventually reset back to the initial limit. There are couple different ways you could go about doing it.

**Comment by Fryeswitthat542** [comment]
Oof - Sounds easy enough for someone like you that knows how to do it haha. I was just hoping that we could just stick like 

If it sends the kill message, then set the ep_watched to 0 and continue to count like it does or something. Is this something maybe you can add in while we're all quarantined :)

**Comment by VozDeOuro** [comment]
I know this is an old issue, but I’ve made an edit to the script and have been using it with that functionality for a while now. I modified it specifically to kill streams that play non-stop for more than 4 episodes, mainly to avoid wasting bandwidth if someone falls asleep or isn't actively watching.

The script is a quick-and-dirty hack to solve my specific need, so I can't guarantee that other features still work as expected. But if you're looking for something like that, feel free to check it out:

🔗 https://github.com/VozDeOuro/scripts (look for `limiterr.py`)
