### ISSUE TITLE
Request - Limit transcode if bitrate with in % of original

### ISSUE THREAD

**Issue by bbakermmc** [blacktwin/JBOPS#213]
It looks like with killstream you can set a min bitrate, but would it be possible for this to be dynamic based on the bitrate of the media being played?   I would probably want something like allow transcode if the bitrate is lower than 2k or 75%.  This should help force users who dont change the default settings.  In most cases they can stream the original fine but the default setting is just slightly lower, but I dont want to not allow transcode if maybe they are on mobile and want to force it way down.

**Comment by blacktwin** [comment]
You control when the script triggers by the conditions. Set up more robust conditions to accomplish what you are asking.

**Comment by bbakermmc** [comment]
Not sure how that helps any.

Does the UI allow for comparing to variables?

This doesnt seem to work.
![image](https://user-images.githubusercontent.com/30090055/78458842-6b862180-7682-11ea-99da-49793778f847.png)

**Comment by blacktwin** [comment]
You could use the condition logic to group profiles together and create the percentage you want to use.

1. Video Bitrate | is | 4000
2. Stream Video Bitrate | is lower than | 3800

3. Video Bitrate | is | 3000
4. Stream Video Bitrate | is lower than | 2850

Condition Logic

({1} and {2}) or ({3} and {4})

So if the video is 4000 and transcoding causes the stream to be less than 3800 (5% of video) then kill or if the video is 3000 and the stream is less than 2850 (5% of video) then kill.

**Comment by bbakermmc** [comment]
Thanks, but that's not dynamic based on the original video bit rate.  You would need to define multiple thresholds.  So you could be bumped into a higher threshold cap that would allow transcoding that they dont need.

But it could be a limitation of taut.

**Comment by blacktwin** [comment]
Any kind of calculations would need to be in a script. 

IMO, Tautulli provides enough conditional control to accomplish what your looking for.
