### ISSUE TITLE
Request: Apply Limits to all users and all libraries in "stream_limiter_ban_email.py"

### ISSUE THREAD

**Issue by Tangogr** [blacktwin/JBOPS#214]
Is it possible to configure this script to ALL users?
And ALL libraries?

Can I use some sort of wildcard?

BAN_LIBRARY = {ALL_USERS: [ALL_LIBRARIES_]} # {UserID1: [LibraryID1], UserID2: [LibraryID1]}

**Comment by blacktwin** [comment]
There are plenty examples in the other scripts for doing this. This is a very old script. If I were to touch it I would want to rewrite the entire thing over. If you want to make improvements please do and create a PR.

**Comment by Tangogr** [comment]
Ok, my python skills are not good enought, but I will try. Thanks!
