### ISSUE TITLE
Prevent plex_api_invite.py stopping when invalid username or email?

### ISSUE THREAD

**Issue by tenknas** [blacktwin/JBOPS#215]
**Describe the bug**

I add a few people to my servers on a regular basis, but whenever there is an incorrect username/email or user already shares libraries, the python script just stops working. Is there a way to allow it to just continue with the other users, even if there is an error?

**Link to script with bug/issue**

**To Reproduce**

**Expected behavior**

Just continue even if there is an error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, Windows, Docker]
 - Python Version [e.g. 22]

**Additional context**

**Comment by blacktwin** [comment]
Sounds like user error.

**Comment by tenknas** [comment]
So no way to skip user errors?
