### ISSUE TITLE
sync_watch_status.py AttributeError: 'NoneType' object has no attribute 'library'

### ISSUE THREAD

**Issue by bruvv** [blacktwin/JBOPS#216]
**Describe the bug**
When I want to sync PLEX > Tautulli I get the following error:
```bash
Connecting to admin server(s) for access info...
Checking nivong's access to Plexdrone
Connecting nivong to Plexdrone...
Finding watched items in libraries...
Checking nivong's library: 'Films' watch statuses...
Marking watched...
Traceback (most recent call last):
  File "sync_watch_status.py", line 509, in <module>
    sync_watch_status(watched_lst, _library.title, server, username, same_server)
  File "sync_watch_status.py", line 381, in sync_watch_status
    sectionTo = accountTo.library.section(section)
AttributeError: 'NoneType' object has no attribute 'library'
```

Note: When syncing TAUTULLI > Plex it does work. But I want it the otherway around as well :)

**Link to script with bug/issue**
https://github.com/blacktwin/JBOPS/blob/master/utility/sync_watch_status.py

**To Reproduce**
1. Run the sync:
```python sync_watch_status.py --userFrom username=Plex --userTo username=Tautulli --libraries Movies "TV Shows"```

**Expected behavior**
Sync from Plex to Tautulli

**Desktop (please complete the following information):**
 - OS: Windows 10 and MacOS 13
 - Browser: Chrome
 - Python Version: Python 2.7.16

**Comment by blacktwin** [comment]
Can't be done. Plex doesn't not provide enough information.

**Comment by bruvv** [comment]
Alright thanks for letting me know! Keep up the github page :) great tools
