### ISSUE TITLE
Profiles fall under the same time limit

### ISSUE THREAD

**Issue by JVTEAM** [blacktwin/JBOPS#217]
**Describe the bug**
Limiterr limits all accounts.  

**Link to script with bug/issue**
limiterr.py
**To Reproduce**
Set the limit for 1 hour per day.  Watch an hour with one user. Switch to another.  You are limited based on the other users watching.
**Expected behavior**
Would like to limit only specific users.

**Comment by blacktwin** [comment]
Use the conditions to isolate the script to specific users. Please provide your conditions and arguments that you're using.

**Comment by JVTEAM** [comment]
Great!  tweaked the conditions to include the user.  Thanks!
