### ISSUE TITLE
playlist_manager.py - Playlist Exporting to CSV

### ISSUE THREAD

**Issue by bbrospo** [blacktwin/JBOPS#219]
https://github.com/blacktwin/JBOPS/blob/master/fun/playlist_manager.py

I am using playlist_manager.py to sync playlists between users. This 100% for music. I'd like a mechanism added to he script to export those playlists to a .csv file. I don't necessarily need an import, but it would be a nice addition to be able to restore them, if possible.

**Comment by blacktwin** [comment]
@bbrospo Please try the updated version of the playlist_manager.py.
