### ISSUE TITLE
alternate forms of notify other than email: pushbullet

### ISSUE THREAD

**Issue by dejected1** [blacktwin/JBOPS#22]
So i was trying to figure out if we could adapt one of the notify scripts to notify a different service. For me its pushbullet. It works through plexpy directly but plexpy has no way of setting different notifications depending on what the media is. (movies and tv shows). the script: notify_fav_tv_all_movie.py from JBOPS would work perfect since it already makes a distinction between movies and tv.

**Comment by blacktwin** [comment]
Can you explain a little more of what exactly you're looking for?

**Comment by dejected1** [comment]
Sure. The "notify_fav_tv_all_movie.py" script from your JBOPS scripts notifies via email. I would like to change or add another form of notification to the script (if possible). Such as pushbullet.

The reason is I have new added notifications sent from plexpy to my pushbullet account using the built in notification system. this works for the most part except it doesn't let you make different notifications based on media type. A Lot of the plex py variables or media specific. So i end up with a lot of duplicates and gibberish in my notification.  (IE: i want to add the season and episode numbers for tv but when i get a movie notification it just says 0x0. )

**Comment by blacktwin** [comment]
Are you using tags in your [Notification Message Body?](https://imgur.com/ttrpu87)

`<movie> {title}} </movie> <tv> {show_name} - S{season_num00}E{episode_num00} - {episode_name}} </tv> has been added.`

**Comment by dejected1** [comment]
aaaaahhhhhhhhhhhhhhh. i didn't even see that. Yeah that would fix it. Nevermind i guess. I wouldn't mind getting notifications from your scripts other than email still. But for the immediate need, the exclusions tags fix it. RTFM i suppose.

**Comment by blacktwin** [comment]
If it's just changing the message then using tags is far easier. If you want to direct the message to someone then a custom script would be best. Does Pushbullet do direct messaging or is it a room thing?

**Comment by dejected1** [comment]
i like the flexibility the script offers. that way i can coordinate users and specific shows as opposed to all shows all users. I also like using pushbullet for notifications. I only use pushbullet for tv and movie notify, so i know when i get something from it that's what it is. I get a lot of email, sometimes the notify gets lost in the email rush.

**Comment by blacktwin** [comment]
I just started looking into pushbullet. I'll see what I can do.

**Comment by blacktwin** [comment]
I think this can be closed with Tautulli's addition of multiple agents and conditions. Setup an agent (pushbullet) to a specific user, assign the user to their specific notifier_id (agent ID) in the script ({"user" : "user1", "notifier_id": 2}). 

@dejected1 Has the update to tuatulli resolve this issue for you already? I know this is an old issue.
