### ISSUE TITLE
Readme.md - incorrect conditions.

### ISSUE THREAD

**Issue by suodrazah** [blacktwin/JBOPS#221]
Haven't reviewed the rest of the documentation (just flicking through), but under "Kill transcode by bitrate" you have

Conditions 

[ **Bitrate** | is greater than | 4000 ]

And in Args

--jbop stream --username {username} --sessionId {session_id} --killMessage 'Transcoding streams are not allowed from over 4 Mbps (Yours: {**stream_bitrate**}).'

You need to modify these to both be "Stream Bitrate" otherwise the stream is ended with reference to the source bitrate not stream bitrate as mentioned in the user dialog.

https://github.com/blacktwin/JBOPS/tree/master/killstream#kill-transcode-by-bitrate

**Comment by blacktwin** [comment]
I don't think you understand the use case. This allows transcoding for anything with a source bitrate below `4000`. If transcoding a file with greater than `4000` show the file limit and the stream bitrate of the offending stream in the message.
![image](https://user-images.githubusercontent.com/22177672/82181761-2116d800-98b1-11ea-9faa-ea0861350de4.png)
![image](https://user-images.githubusercontent.com/22177672/82181833-473c7800-98b1-11ea-9bad-1c95b656f297.png)

Ultimately, the message is up to you. You change it :)

**Comment by suodrazah** [comment]
I understand completely, but the language is mismatched and will unfortunately confuse the end user. And we all love explaining simple concepts to users...amiright?

e.g. Transcoding output of a stream is manually selected by a user to be 2mbps, source media is >4000kbps so the stream is ended. User gets the following notification:

"Transcoding streams are not allowed from over 4 Mbps (Yours: 2000)."

The dialog makes no sense unless the compared values are of the same reference. Source media or output bitrate, not one of each. The use case can be either, but the example needs to reference the same data source for comparison otherwise it makes no logical sense.

Alternatives:

```
[ Bitrate | is greater than | 4000 ]

--jbop stream --username {username} --sessionId {session_id} --killMessage 'Transcoding streams are not allowed from over 4 Mbps (Yours: {bitrate}).'
```
or
```
[ Stream_bitrate | is greater than | 4000 ]

--jbop stream --username {username} --sessionId {session_id} --killMessage 'Transcoding streams are not allowed from over 4 Mbps (Yours: {stream_bitrate}).'
```
or, in line with your desired use case with friendlier language
```
[ Bitrate | is greater than | 4000 ]

--jbop stream --username {username} --sessionId {session_id} --killMessage 'Transcoding is not allowed from sources over 4 Mbps (Current source: {bitrate}kbps).'
```

Of course, this is just my opinion and however you want to present the readme is completely up to you :-). Thanks for the script either way!
