### ISSUE TITLE
[Request] Have a message show up, by using killstream, once a day for a certain user during the start of the first stream

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [blacktwin/JBOPS#225]
I'm trying to display a message to a certain user once everyday when the user starts his/her first stream. Possible to edit the kill stream script to include this? Thanks!

**Comment by blacktwin** [comment]
Possible? Sure. Most things are possible with time. However I don't think using the killstream to do this would be the best method. What is the message that you're trying to send to the user? Why not use any of the other notification agents to send the message?

If you kill the first stream of the day, depending on your history logging settings in Tautulli, that user would never have a first stream as you'd kill it each time they start one. There would be no history of them starting a stream to have the script easily check against. You'd have to either scrape the logs or create a file somewhere to track streams started and killed streams from this user for the day.
