### ISSUE TITLE
plex_api_share error

### ISSUE THREAD

**Issue by crogers2287** [blacktwin/JBOPS#23]
root@plex:~# python plexlib.py -s unshare -u user -l Movies
Traceback (most recent call last):
  File "plexlib.py", line 73, in <module>
    unshare(opts.user, opts.libraries)
  File "plexlib.py", line 50, in unshare
    plex.myPlexAccount().updateFriend(user=user, server=plex, removeSections=True, sections=libraries)
TypeError: updateFriend() got an unexpected keyword argument 'removeSections'

It's listing users and libraries when ran with --help, but throwing this error when sharing/unsharing

**Comment by blacktwin** [comment]
You'll need to update plexapi. Use git to update.
try:
`pip install git+git://github.com/pkkid/python-plexapi@master --upgrade`

**Comment by crogers2287** [comment]
That fixed the error, but now when I unshare, it shows that all libraries have been unshared, but it doesnt actually change anything in plex

**Comment by blacktwin** [comment]
When you unshare you always unshare all libraries. If you want to unshare one library then you'll need to share all the other libraries excluding the one you don't want to share.

So, if you have Movies, TV Shows and Music and a user1 has access to all three but you want to unshare Music then you'd use `-s "TV Shows" Movies -u user1`. Does that help? 

What doesn't change in Plex? Is this in regards to what the user sees or what is seen by the admin on the user screen?

**Comment by crogers2287** [comment]
root@plex:~# python plexlib.py -s unshare -u realplexshares
Unshared all libraries from realplexshares.

![image](https://user-images.githubusercontent.com/5433396/31910718-6abfc972-b80c-11e7-86dc-c174357fa456.png)

![image](https://user-images.githubusercontent.com/5433396/31910729-76f17a92-b80c-11e7-8b17-da2db1faf5ec.png)

I'm just trying to keep it simple and unshare all libraries, nothing changes in plex on my end, or as far as I can tell with people that I've had check on their end either.

**Comment by blacktwin** [comment]
You may need to refresh the page for it to show correctly. But you're saying the user 'realplexshares' still has access to libraries? User isn't the server admin?

**Comment by crogers2287** [comment]
Right, I've refreshed, tried different users, different libraries, etc, but nothing changes and it shows no errors. I had a friend check after running the script against his username and he still retained access.

**Comment by blacktwin** [comment]
Ok. I think I've resolved it. The problem was that the unshare needed a sectionId in order to run. I've updated the script. Please try.

**Comment by blacktwin** [comment]
@crogers2287 Can you confirm that this issue is resolved?

**Comment by crogers2287** [comment]
Sorry it took so long to get back to you, this did resolve the issue. Also had to change line 71 to the same thing to get re-sharing to work. Thanks for all the help.
