### ISSUE TITLE
[Request] Copying playlists to a second server

### ISSUE THREAD

**Issue by CoffeeKnyte** [blacktwin/JBOPS#243]
I would like to copy playlists from USER1 on Server1 to USER1 on Server2.
Both servers are owned by the same Plex account.
This could be an additional feature to the playlist_manager.py script.
https://github.com/blacktwin/JBOPS/blob/master/fun/playlist_manager.py

I have just set up a second server as a backup and one of my users would like to copy over their playlists. However, it's very tiresome to recreate them all (he has 70+ playlists now).  It would be ideal to be able to copy all playlists at once (instead of having to name them one by one).

I've tried exporting and re-importing playlists using the plugin Webtools, but that can only be done 1 by 1 (and is very slow).
Copying playlists with Webtools is only possible between users on the same server.

I can see that the script sync_watch_status.py is able to copy data from one plex server to another if owned by the same account. I hope that the same method can be used to also copy a playlist over.

Thank you.

**Comment by blacktwin** [comment]
playlist_manager has an export feature now but no import. One issue would be that the libraries between servers would need to have the same agent as it would make things easier if I can just use the guid for the matching. Sounds like a cool idea.

**Comment by CoffeeKnyte** [comment]
I agree, requiring the libraries to have the same agents would keep things much simpler for you.
It would not be an issue in my case as my agents are the same anyway.

If the features overlap, perhaps you can also make the script import playlists in general? Specifically from the playlists that it can already export (csv or json). This is just a thought and it might not be worth the trouble depending on how much coding it needs.

**Comment by blacktwin** [comment]
@CoffeeKnyte just added an import feature to the playlist_manager script. 

`--action import --users User1 "Another User" --importJson test_import.json --libraries "TV Shows"`
