### ISSUE TITLE
check_play issue obtaining watched history

### ISSUE THREAD

**Issue by abnersnell** [blacktwin/JBOPS#244]
Attempting to use check_play.py (python3) and receive the following:

Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/scripts/plexpy/check_play.py", line 89, in <module>
            if sum(hisy.watched) == 0:
    AttributeError: 'NoneType' object has no attribute 'watched'

I am passing {user} {title} as arguments of Playback Resume.

Can someone point me in the right direction?  

Thanks!

**Comment by blacktwin** [comment]
Please follow Tautulli's [Asking for Support page](https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support#how-can-i-share-my-logs) for sharing logs. Please link your logs here.

**Comment by blacktwin** [comment]
No response in a month. Closing.
