### ISSUE TITLE
plex_api_invite.py      error: the following arguments are required: --user

### ISSUE THREAD

**Issue by sirloinofbeef** [blacktwin/JBOPS#245]
**Describe the bug**
When trying to invite a user I get "error: the following arguments are required: --user"

**Link to script with bug/issue**
plex_api_invite.py

**To Reproduce**
1.Execute plex_api_invite.py --allLibraries --user USERXXX
   (where USERXXX is a valid username which I can add / remove from Plex manually)
2. Receive error "error: the following arguments are required: --user"

**Expected behavior**
Add USERXXX to Plex and share all libraries

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: Chrome 85.0.4183.121
 - Python Version: 3.8.5

**Additional context**
I have tried various usernames and variations, all with the same result.

**Comment by blacktwin** [comment]
I'm unable to confirm on my end. Can you provide a screenshot/copy&paste of your terminal showing the command executed and the error?

**Comment by sirloinofbeef** [comment]
<img width="636" alt="Screenshot 2020-10-02 231424" src="https://user-images.githubusercontent.com/2571904/94927432-994f0480-0505-11eb-89c8-32f32853e3ec.png">

**Comment by blacktwin** [comment]
![image](https://user-images.githubusercontent.com/22177672/94928891-5273f700-0492-11eb-987d-72ea1d64bf88.png)
![image](https://user-images.githubusercontent.com/22177672/94929247-d332f300-0492-11eb-9fc8-3727268ea9f4.png)

Worked on python 3.7 and 3.8. Weird. You're not misspelling `--user` and there is nothing appended to it. Try without `--allLibraries` and just the `--user USER`.

**Comment by sirloinofbeef** [comment]
Same result with --user USER
I even re-downloaded the script just to make sure nothing was altered (same result). Very weird.

To add to the mystery, I tried running it from a different machine, with different but equally perplexing results:
![Annotation 2020-10-03 082325](https://user-images.githubusercontent.com/2571904/94974491-11dbb280-0552-11eb-95ea-427f32031202.png)
No errors are thrown (with or without argument usage) and no user is added to the server.
