### ISSUE TITLE
Cannot get kill_stream to work

### ISSUE THREAD

**Issue by spdrcr5** [blacktwin/JBOPS#251]
**Describe the bug**
I setup kill_stream and it will not kill anything.  I'm sure I am missing something, just cannot figure out what.

**Desktop (please complete the following information):**
 - OS:Windows Server 2012 R2
 - Browser:  Chrome
 - Python Version: 2.7

**Additional context**
My first script I setup for 20 min pause before killing.  I tried to have it ignore local playback as I don't care if my daughter leaves something paused too long.  I have several people using my Plex that leave things pause for hours and if I don't kill it my server has had issues.  In the Tautulli log is is showing that the script ran and gives the success check in the log.  Unfortunately it actually isn't doing anything.  the sessionId is not even filling in the sessionId, it remains [session_id} which means that isn't being grabbed properly. 

Here is my setup:
**Configuration**: script folder and script file are located at c:\killstream on my server
script timeout is 0
**Triggers**: I have checked Playback Pause
**Conditions**: are Stream Local is not 1
**Arguments**: Under Playback Pause:  --jbop paused --sessionId {session_id} --killMessage 'Your stream was paused for over 20 minutes and has been automatically stopped for you.'

With the above not doing anything I decided to try a 5 minute Pause kill and this time not exclude local content.  This too didn't work.
The above is the same except I didn't add any **Conditions** and the **Argument** was:
--jbop paused --interval 15 --limit 300 --sessionId {session_id} --killMessage 'Your stream was paused for over 5 minutes and has been automatically stopped for you.'

What am I doing wrong?

Thanks
Larry

**Comment by blacktwin** [comment]
Can you please share your [Tautulli ](https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support#how-can-i-share-my-logs)logs?

**Comment by spdrcr5** [comment]
Here are the logs

https://gist.github.com/spdrcr5/0600e499cd80ccad9aceb4c6579a74fe

Thanks

**Comment by blacktwin** [comment]
Your logs never show that you created a script agent or that an agent has been triggered. Did you even setup the agent?

**Comment by spdrcr5** [comment]
Here is the Notification Agent settings
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]

**Comment by blacktwin** [comment]
Your pictures didn't attach.

**Comment by spdrcr5** [comment]
Hopefully the pictures are attached now.

**Comment by spdrcr5** [comment]
![script1](https://user-images.githubusercontent.com/71077641/96154247-988e7900-0edc-11eb-9037-12b0efe37170.jpg)
![script2](https://user-images.githubusercontent.com/71077641/96154250-99270f80-0edc-11eb-85b7-4ba2f397c272.jpg)
![script3](https://user-images.githubusercontent.com/71077641/96154251-99270f80-0edc-11eb-9608-a2ef1d2d2b5d.jpg)
![script4](https://user-images.githubusercontent.com/71077641/96154252-99270f80-0edc-11eb-8cab-f70fa5a95b12.jpg)

**Comment by spdrcr5** [comment]
Any update on this?

Thanks

Larry

**Comment by blacktwin** [comment]
Can you post updated logs? Your previous logs don't show the script ever running.

**Comment by spdrcr5** [comment]
That's the issue which is why I included the screen shots showing how I configured this.  I don't know if it is actually running.  Is it setup correctly?  I see notifications in the Notification Logs but that's about all.  I attached the 

The Tautulli logs do not include the Notification Logs, which is rather strange.  I took a screenshot below of part of that log.

https://gist.github.com/spdrcr5/74d5d1efb1e5279abf269b506cd02b6c

![10-20-2020 1-45-46 PM](https://user-images.githubusercontent.com/71077641/96624413-b42dc100-12da-11eb-99e7-f7e2d8f71404.jpg)

**Comment by blacktwin** [comment]
```
2020-10-05 07:46:27 - DEBUG   :: MainThread : Altering database. Updating database table notifiers.
2020-10-05 07:46:27 - ERROR   :: MainThread : Can't connect to the database: UNIQUE constraint failed: image_hash_lookup.img_hash
```

Looks like you have some database errors which is causing the notifiers to not work properly. See the [Tautulli FAQ](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q18) for steps to fix you DB issue.

**Comment by spdrcr5** [comment]
I repaired the database and ran it again after pausing something.

https://gist.github.com/spdrcr5/9d6e3ee44d7476f3514ec44ded1dc10f

**Comment by blacktwin** [comment]
Good, now your notification agents are working. Can you run the following command `pip install future` this may resolve the `ImportError: No module named builtins` error you're getting. Or update your Tautulli install to the [python3 ](https://github.com/Tautulli/Tautulli-Wiki/wiki/Upgrading-to-Python-3-%28Tautulli-v2.5%29)version.

**Comment by spdrcr5** [comment]
It worked!!!!  Thanks so much for the help on this, it is greatly appreciated.

Larry
