### ISSUE TITLE
Sync_Watch_Status - Completes without marking watched history

### ISSUE THREAD

**Issue by kronnnnnn** [blacktwin/JBOPS#252]
**Describe the bug**
Watch history isn't updated and appears to die at "Marking watched.."

```
root@trashbox:/opt/scripts# python3 sync_watch_status.py --userFrom kronnn=Tautulli --userTo kronnn=Media --libraries "Movies" "Movies (New)"
Connecting to admin server(s) for access info...
Finding watched items in libraries...
Connecting kronnn to Media...
Checking kronnn's library: 'Movies' watch statuses...
Marking watched...
```

**Link to script with bug/issue**
https://github.com/blacktwin/JBOPS/blob/master/utility/sync_watch_status.py

**Expected behavior**
Expected the watch history to sync. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Python Version 3.6.9

**Additional context**
Attempting to recover the watched history from a corrupt DB failure. The new server name is Media which is the same as the old one. Potential issue?

Added print(*watched, sep = "\n") above the print('Marking watched...') and this returned a blank line so it appears watched is null.

**Comment by blacktwin** [comment]
Does kronnn have any history in Tautulli with those libraries?

**Comment by kronnnnnn** [comment]
Yes. This user has watch history within the previous libraries called Movies. Hmmm, I think I see the issue. There are 3 Libraries called Movies, 2 from previous servers which have been upgraded and 1 which is the current active. Soo.. 

Movies (Active) - Current Server
Movies (Library not on Plex)
Movies (Library not on Plex)

Is there a way to specify which library to pull from besides the name? Using the ID instead. I think that's the way.

**Comment by blacktwin** [comment]
> Movies (Active) - Current Server
Movies (Library not on Plex)
Movies (Library not on Plex)

The libraries not on Plex, what are they? Are they empty? Duplicates?

**Comment by kronnnnnn** [comment]
Should have made that part of the post clearer. 

> The libraries not on Plex, what are they? 
These two Movies libraries are from servers that were migrated to the current. 

>Are they empty? Duplicates?
No, they aren't empty and 1 them is much larger than the other. There are definitely some duplicates on the smaller Movies library that will be present in the larger one. How many I'm not sure.

**Comment by blacktwin** [comment]
> These two Movies libraries are from servers that were migrated to the current.

I don't know what that means. Do these library have history in Tautulli? Are they worth keeping in Tautulli?

**Comment by kronnnnnn** [comment]
Yes, this libraries have history as do others with the same name. Seems I need to clean up my database prior to attempting this update/sync. 

[https://imgur.com/a/paA6HSL](url)

**Comment by blacktwin** [comment]
Look at the Tautulli FAQ, especially this [FAQ](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#q-i-moved-media-in-plex-now-tautulli-is-linking-to-the-wrong-itemshowing-up-twice). Then once all your history is corrected and updated to the active libraries you can [delete the duplicated libraries](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#q-my-libraries-are-duplicated-how-do-i-remove-them). Make DB back ups before doing anything.

**Comment by blacktwin** [comment]
@kronnnnnn were you able to resolve this?

**Comment by kronnnnnn** [comment]
Yes, appears so. I've only completed one library so far but after consolidating and executing the scripts again it's updating the items correctly. Though it appears to not insert the watch date but I don't think that's supported. Closed for now. thanks for the help!
