### ISSUE TITLE
FIlters for genre not working

### ISSUE THREAD

**Issue by irodimus** [blacktwin/JBOPS#255]
I'm using PlexAPI 4.2.0 with playlist_manager.py from commit 573651d. I've been using this command (example):
```
python3 playlist_manager.py --jbop random --action update --name "02 Action" --libraries Movies --limit 50 --filter genre=action
```
for a over a year and just realized that it no longer work properly. When running, I get this error:
```
Traceback (most recent call last):
  File "playlist_manager.py", line 879, in <module>
    keys_list = build_playlist(opts.jbop, libraries, opts.days, opts.top, filters, search, opts.limit)
  File "playlist_manager.py", line 530, in build_playlist
    keys_list = get_content(libraries, jbop, filters, search, limit)
  File "playlist_manager.py", line 413, in get_content
    for key, value in filters.items():
RuntimeError: dictionary keys changed during iteration
```
I have another command that filters for decade and that works just fine. I'm not sure what has changed that it making this no longer work. Any help is appreciated.

**Comment by blacktwin** [comment]
That commit should resolve this issue.

**Comment by irodimus** [comment]
Updated to commit https://github.com/blacktwin/JBOPS/commit/e54372379b1a4d70d01bac5b5387ac73d7ca0e0e. Tested and it worked without issue. Thank you!
