### ISSUE TITLE
playlist_manager.py Issue

### ISSUE THREAD

**Issue by ReenigneArcher** [blacktwin/JBOPS#257]
**Describe the bug**
Script stopped working. Last known working on 11/5/2020

**Link to script with bug/issue**
https://github.com/blacktwin/JBOPS/blob/master/fun/playlist_manager.py

**To Reproduce**
1. Run example command: `py -3 playlist_manager.py --action update --self --allUsers --libraries "Movies" --name "2020's Movies" --filter decade="2020"`
2. See error
```
Traceback (most recent call last):
  File "playlist_manager.py", line 181, in <module>
    filters_lst = list(set([y.key for x in sections if x.type != 'photo' for y in x.filterFields()]))
  File "playlist_manager.py", line 181, in <listcomp>
    filters_lst = list(set([y.key for x in sections if x.type != 'photo' for y in x.filterFields()]))
AttributeError: 'MovieSection' object has no attribute 'filterFields'
```

**Expected behavior**
Create/update named "2020's Movies" with videos from Movies library created in 2020 decade.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Win 10 Pro
 - Browser: n/a... Firefox
 - Python Version: 3.8.5

**Additional context**

**Comment by blacktwin** [comment]
Update your `plexapi` library.

**Comment by ReenigneArcher** [comment]
> 
> 
> Update your `plexapi` library.

Thank you, that fixed it!
