### ISSUE TITLE
Kill stream on additional stream fails

### ISSUE THREAD

**Issue by ArBohe** [blacktwin/JBOPS#258]
**Describe the bug**
First time around, kill stream is correctly triggered when a second stream is launched for same user.
However, if user press on Cancel, then resume, the stream starts playing again and no notification is sent. If briefly pause/play is pushed notification is properly triggered.

**Link to script with bug/issue**
Kill_stream.py

**To Reproduce**
1. Play a video
2. On other device, play another video. Notif. Will be triggered.
3. After the notification, press on upper right cancel button (the “x”)
4. Hit resume —> no more notification
5. Hit pause then play, notification is triggered

**Expected behavior**
After a notification, cancelling and resuming should re-trigger a notification

**Desktop (please complete the following information):**
 - OS: iOS, iPadOS
 - Browser: -
 - Python Version 3

**Comment by blacktwin** [comment]
What triggers are you using?

**Comment by ArBohe** [comment]
Playback start, playback resume

Cheers,
Arnaud
________________________________
De : blacktwin <notifications@github.com>
Envoyé : Sunday, December 6, 2020 2:08:12 PM
À : blacktwin/JBOPS <JBOPS@noreply.github.com>
Cc : ArBohe <arnaud@bohelay.com>; Author <author@noreply.github.com>
Objet : Re: [blacktwin/JBOPS] Kill stream on additional stream fails (#258)


What triggers are you using?

**Comment by blacktwin** [comment]
Can you please follow Tautulli's instructions for sharing logs and post them here?
