### ISSUE TITLE
Unable to delete admin playlist

### ISSUE THREAD

**Issue by irodimus** [blacktwin/JBOPS#259]
**Describe the bug**
Admin playlist that is specified does not delete when using commit 4632dfc600207d0e4698be093e95afd7416dc65d

**To Reproduce**
Run command:
```playlist_manager.py --action remove --playlists "63 Christmas" --self```

**Expected behavior**
Delete specified playlist

**Additional context**
Used with and without --self

**Comment by blacktwin** [comment]
@irodimus pushed an update, please try.

**Comment by irodimus** [comment]
This resolved the issue. Thank you!
