### ISSUE TITLE
Kill Stream don't work

### ISSUE THREAD

**Issue by Sevea** [blacktwin/JBOPS#260]
Hi,
This is the message i see on the log : 

Tautulli Notifiers :: Script error:    Traceback (most recent call last):        File "C:\Program Files (x86)\Tautulli\Scripts\kill_stream.py", line 42, in <module>            from builtins import object    ImportError: No module named builtins
--

with tautulli 2.6.2,

Thanks

**Comment by blacktwin** [comment]
`ImportError: No module named builtins` and Python27 you'll need to install builtins `pip install future` or update to the python 3 build.
