### ISSUE TITLE
Create Custom plex homescreen for all plex server users

### ISSUE THREAD

**Issue by brasiledo** [blacktwin/JBOPS#261]
**Is your feature request an improvement on an existing script? Please link to script.**
Looking for a script to create a custom plex homescreen for all my users and all devices.  I want to be able to control the standard hubs that users see on their homescreen i.e 'Recently added Movies', 'Recently Added TV Shows' , 'Continue watching' ... etc

Also, creating custom hubs would be a good addition as well

**Is your feature request related to a problem? Please describe.**
For less technical users they have issues seeing content that i add or just have disorganized cluttered home screen with un needed content.   For the custom hubs, I'd like to create a dynamic hub that through my movie content and displays suggested items based off users watching patterns.  If not that complex at least i'd like to create custom static hubs based off of genre or other category

**Describe alternatives you've considered**
none

**Comment by blacktwin** [comment]
This is not something that can be done via the WebUI so it's not something that can be scripted. What you're looking for is a custom player, which wouldn't be a script but a complete application.
