### ISSUE TITLE
kill_stream stopped working 

### ISSUE THREAD

**Issue by spdrcr5** [blacktwin/JBOPS#263]
You had helped me get kill_stream working after a 20 min pause.  It was working great then it just stopped working.

I uploaded the logs.

[tautulli.log](https://github.com/blacktwin/JBOPS/files/5673637/tautulli.log)

Thanks

Larry

**Comment by blacktwin** [comment]
`ImportError: No module named builtins` and Python27 you'll need to install builtins `pip install future` or update to the python 3 build.

**Comment by spdrcr5** [comment]
I updated to Python 3.9.1 and it is still not working.  Logs are attached.

[tautulli.log](https://github.com/blacktwin/JBOPS/files/5698943/tautulli.log)

Thanks

Larry
