### ISSUE TITLE
Can't get watched movie deleter to work

### ISSUE THREAD

**Issue by A54DH** [blacktwin/JBOPS#264]
Hi there. First off thank you for the scripts. I've only recently discovered them and can't thank you enough.

Unfortunately, I'm having trouble getting the delete scripts to work. I'm trying to get the watched movie deleter script working but I'm running into issues. Managed to solve the first error by installing the request module but after Googling the latest errors, I'm stumped. Please can somebody take a look at the logs below and help me figure this one out?

Thank you. ☺️ 

EDIT: Forgot to mention, I'm using the watched trigger.

> 2020-12-10 20:58:03 - INFO    :: Thread-3 : Tautulli NotificationHandler :: Preparing notification for notifier_id 2.
> 2020-12-10 20:58:04 - DEBUG   :: Thread-3 : Tautulli Notifiers :: Trying to run notify script: C:\Users\Media\Documents\Taut Scripts\remove_jake_watched_movies.py, arguments: [], action: test
> 2020-12-10 20:58:04 - DEBUG   :: Thread-3 : Tautulli Notifiers :: Full script is: ['python', 'C:\\Users\\Media\\Documents\\Taut Scripts\\remove_jake_watched_movies.py']
> 2020-12-10 20:58:04 - DEBUG   :: Thread-3 : Tautulli Notifiers :: Executing script in a new thread.
> 2020-12-10 20:58:11 - WARNING :: CP Server Thread-12 : Failed to access uri endpoint /library/metadata/4529. Status code 404
> 2020-12-10 20:58:11 - WARNING :: CP Server Thread-12 : Tautulli Pmsconnect :: Unable to parse XML for get_metadata_details: 'NoneType' object has no attribute 'getElementsByTagName'.
> 2020-12-10 20:58:11 - WARNING :: CP Server Thread-12 : Unable to retrieve data for get_metadata_details.
> 2020-12-10 20:58:13 - DEBUG   :: Thread-65 : Tautulli Notifiers :: Subprocess returned with status code 1.
> 2020-12-10 20:58:13 - ERROR   :: Thread-65 : Tautulli Notifiers :: Script error: 
>   Tautulli API 'get_metadata' request failed: 'library_name'.Traceback (most recent call last):
>     File "C:\Users\Media\Documents\Taut Scripts\remove_jake_watched_movies.py", line 132, in <module>
>       delete_files(delete_lst)
>     File "C:\Users\Media\Documents\Taut Scripts\remove_jake_watched_movies.py", line 82, in delete_files
>       del_file = input('Delete all watched files? (yes/no)').lower()
>   EOFError: EOF when reading a line
> 2020-12-10 20:58:13 - DEBUG   :: Thread-65 : Tautulli Notifiers :: Script returned: 
>   'NoneType' object has no attribute 'title'
>   Saw III has been watched by Jake
>   Delete all watched files? (yes/no)
> 2020-12-10 20:58:13 - INFO    :: Thread-65 : Tautulli Notifiers :: Script notification sent.

**Comment by blacktwin** [comment]
You should be running that script outside of Tautulli using cmd or terminal. You can see in the logs that it's waiting for a response on whether to delete the watched items or not. That script was not mention to be ran by Tautulli.

**Comment by A54DH** [comment]
Oh my. I feel like a right idiot. Thank you for your prompt reply.

Just out of curiosity, is there anyway to automate the script running after a movie has been watched? Or weekly?

I’m also assuming the TV show version is also meant to be run outside of Tautulli?

**Comment by blacktwin** [comment]
I don't have any examples yet but [media_manager](https://github.com/blacktwin/JBOPS/blob/master/utility/media_manager.py) is the replacement for all of my deletion based scripts. What is it that you're trying to do, maybe I can help with figuring out the arguments needed for Tautulli.

**Comment by blacktwin** [comment]
Or just change your script like this.
[This](https://github.com/blacktwin/JBOPS/blob/master/utility/remove_watched_movies.py#L81-L88)
```python
def delete_files(tmp_lst):
    del_file = input('Delete all watched files? (yes/no)').lower()
    if del_file.startswith('y'):
        for x in tmp_lst:
            print("Removing {}".format(os.path.dirname(x)))
            shutil.rmtree(os.path.dirname(x))
    else:
        print('Ok. doing nothing.')
```
to this 
```python
def delete_files(tmp_lst):
    for x in tmp_lst:
        print("Removing {}".format(os.path.dirname(x)))
        shutil.rmtree(os.path.dirname(x))
```
