### ISSUE TITLE
Feature Request: playlist manager sort by date

### ISSUE THREAD

**Issue by ReenigneArcher** [blacktwin/JBOPS#265]
**Is your feature request an improvement on an existing script? Please link to script.** https://github.com/blacktwin/JBOPS/blob/master/fun/playlist_manager.py
Would it be possible to add the ability to sort by date when using the playlist manager like the following?

`--action update --self --allUsers --libraries "Movies" --name "James Bond" --filter collection="James Bond"`

It looks like the script already contains a function "sort_by_dates" so maybe an option could added to use this function when using a filter?

**Is your feature request related to a problem? Please describe.**
I am using playlist_manager.py to create some playlist similar to above... James Bond, Marvel Cinematic Universe, etc. It would be ideal if they were sorted by release date like the history playlists.

**Describe alternatives you've considered**
Manual creation of the lists, which is very time consuming.

**Additional context**

**Comment by blacktwin** [comment]
Maybe adding a `--sort` argument to apply to any query? I'd also like to make this into a simple UI that would allow for even more customization.

**Comment by ReenigneArcher** [comment]
> 
> 
> Maybe adding a `--sort` argument to apply to any query? I'd also like to make this into a simple UI that would allow for even more customization.

I think that would be perfect!
