### ISSUE TITLE
Is all JBOPS scripts ready for python 3?

### ISSUE THREAD

**Issue by Anuruddha094** [blacktwin/JBOPS#268]
Hi currently I'm running Tautulli and JBOPS on python 2. I haven't updated to python 3 version until all JBOPS's scripts supports python 3. Now I can't find Python 3 branch. I'm assuming may be all scripts supports python 3.

please update me about this.

Thank you very much for your excellent scripts. It's must for all plex users.

cheers

**Comment by blacktwin** [comment]
Yes. They all should work for python 3.x. To be honest, I haven't tested all of them. So let me know if you have an issue.

**Comment by Anuruddha094** [comment]
> Yes. They all should work for python 3.x. To be honest, I haven't tested all of them. So let me know if you have an issue.

@blacktwin Thank you very much for your fast reply. I have been checking all your scripts source code to verify future module is importing or not. Now I don't need to do it. 😊

Sure I will let you know, if I encounter any phrase errors.

Thank you again. 👍

**Comment by vegasit** [comment]
I am using python 3.8.6 on windows and I keep getting this error: Tautulli Notifiers :: Failed to run script: [WinError 2] The system cannot find the file specified

But all the other scripts run fine. Windows server 2008 R2

**Comment by Anuruddha094** [comment]
> I am using python 3.8.6 on windows and I keep getting this error: Tautulli Notifiers :: Failed to run script: [WinError 2] The system cannot find the file specified
> 
> But all the other scripts run fine. Windows server 2008 R2

I'm running tautulli with python 3.8.6.  I randomly checked the all JBOPS scripts except Killstream. Everything works fine. I assume you didn't specify the correct full path to the jbops script in tautulli. can you please post the photo of **configuration tab** in you script settings. 

cheers

**Comment by vegasit** [comment]
@Anuruddha094  you can take a look but still no joy, it runs the notifier, but never executes the scripts. Transcoded video continues to play no kill or notice

![image](https://user-images.githubusercontent.com/32071088/102668557-d1073900-4151-11eb-9f88-da51ae32edb3.png)


And this is the error that i get everything
![image](https://user-images.githubusercontent.com/32071088/102668612-f72cd900-4151-11eb-8e8b-03472d033ebb.png)

**Comment by Anuruddha094** [comment]
Is that full path to the file is correct?

**Comment by blacktwin** [comment]
@Anuruddha094 can this issue be closed as it's initial question has been resolved. @vegasit has already created their own issue #269

**Comment by Anuruddha094** [comment]
@blacktwin Yes for sure. Your scripts works fine with python 3. Thank you again for your excellent work.
