### ISSUE TITLE
URL formatting issue

### ISSUE THREAD

**Issue by vegasit** [blacktwin/JBOPS#271]
There is a problem with the URL formatting in the  'purge_removed_plex_friends'

If there is a trailing '/' then the script fails when running

![image](https://user-images.githubusercontent.com/32071088/102667302-a8317480-414e-11eb-92a2-b7bf2411a67d.png)

I have fixed it and tried to update the code in branch but it will not let me. So here it is. 

Original Line 38:

`formatted_url = f'{TAUTULLI_URL}/api/v2'`

chnaged to:

`formatted_url = TAUTULLI_URL.rstrip('/') + '/api/v2'`

Now it will execute with or without the trailing '/'

**Comment by blacktwin** [comment]
Are you using a config file to store your credentials and URLs or are you adding this information to the script?

**Comment by vegasit** [comment]
I am using the script for the config no seprate config file. I will look at the PR template, I tried to push one and it would not allow me to. I will attempt again

**Comment by blacktwin** [comment]
Or just remove the trailing `/`.
