### ISSUE TITLE
Media Manager use x number of days instead of a date

### ISSUE THREAD

**Issue by cyturralde** [blacktwin/JBOPS#279]
**Is your feature request an improvement on an existing script? Please link to script.**
https://github.com/blacktwin/JBOPS/blob/master/utility/media_manager.py

I was thinking it might be useful in terms of automation if the script could be set up to use a set number of days from todays date to go back and check if things had been watched or unwatched, as opposed to having to manually type in a date.

**Is your feature request related to a problem? Please describe.**
No

**Describe alternatives you've considered**
I have already made the necessary adjustments to the script and got it working if you are interested.

**Additional context**
n/a

**Comment by blacktwin** [comment]
> I have already made the necessary adjustments to the script and got it working if you are interested.

Yes, please create a PR.

**Comment by cyturralde** [comment]
Not super familiar with github, so I think I did it right. Sorry if I did it wrong.

**Comment by blacktwin** [comment]
I don't see anything, so I'm not sure what you did?

**Comment by cyturralde** [comment]
Sorry githubs not really my thing. Tried it again.

**Comment by blacktwin** [comment]
This issue should now be resolved via #270
