### ISSUE TITLE
[Script Request] Pause SabNZBd when Activity detected, Resume SabNZBd when Activity ends

### ISSUE THREAD

**Issue by ramair02** [blacktwin/JBOPS#280]
Thought this might be a useful script for the community.

I prefer not to be downloading while my users are streaming (to save CPU resources). Currently, I use SabNZBd scheduling to run downloads from 2 AM - 10 AM, a block when my users are typically not streaming.

Would it be feasible to write a script that tells SabNZBd to pause downloading when Tautulli detects a new stream and resume downloading when streaming finishes? Essentially, pause SabNZBd when any user is streaming from Plex and resume only when no one is streaming.

Thanks!

**Comment by blacktwin** [comment]
This already [exists](https://gist.github.com/Hellowlol/a5d0cab4bde185b38404). Found in the [Tautulli scripts list](https://github.com/Tautulli/Tautulli-Wiki/wiki/Custom-Scripts#tautulli-scripts).

**Comment by ramair02** [comment]
> This already [exists](https://gist.github.com/Hellowlol/a5d0cab4bde185b38404). Found in the [Tautulli scripts list](https://github.com/Tautulli/Tautulli-Wiki/wiki/Custom-Scripts#tautulli-scripts).

Wow, thank you and sorry for missing that
