### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by fkalmes** [blacktwin/JBOPS#281]
Hello, I reinstall my tautulli server with .exe , i install pynthon (same version 3.8.6)
When the script launch i get this error :

```
2021-01-17 18:32:49 | ERROR | Uncaught exception: Traceback (most recent call last):    File "plexpy\logger.py", line 405, in new_run    File "threading.py", line 870, in run    File "plexpy\notifiers.py", line 3067, in run_scriptUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 26: invalid continuation byte
-- | -- | --
2021-01-17 18:32:49 | ERROR | Uncaught exception: Traceback (most recent call last):    File "plexpy\logger.py", line 405, in new_run    File "threading.py", line 870, in run    File "plexpy\notifiers.py", line 3067, in run_scriptUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 26: invalid continuation byte
2021-01-17 18:32:49 | DEBUG | Tautulli Notifiers :: Subprocess returned with status code 9009.
2021-01-17 18:32:49 | DEBUG | Tautulli Notifiers :: Subprocess returned with status code 9009.
```

I tried to run in cmd : python --version   and  python 3.8.6 is is recognized.

Thank you for your help

**Provide logs**
https://gist.github.com/fkalmes/ecaf2a9b0e340344e1d12a17f76227a5

**Desktop**
 - OS: Windows 10 (10.0.19041)
 - Python Version 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
 - Tautulli VERSION V2.6.5
 - Plex server Version 1.21.1.3876

**Comment by blacktwin** [comment]
Please provide you entire logs. Also what notifier_id is the script?

**Comment by fkalmes** [comment]
the logs https://gist.github.com/fkalmes/83a4d7f39e651e07947c2a79dee23892

I have several scripts : 

<img width="873" alt="Capture d’écran 2021-01-18 à 08 50 43" src="https://user-images.githubusercontent.com/77584409/104887696-029b3c00-596c-11eb-8935-542c9bdb3612.png">


<img width="759" alt="Capture d’écran 2021-01-18 à 08 50 56" src="https://user-images.githubusercontent.com/77584409/104887726-121a8500-596c-11eb-9e88-d80c844e492c.png">

When i reinstall Tautulli, i import my tautulli.db. I din't restore config.ini , i just setup again Tautulli. Should have?

I just download the last killstream.py and put it in C:\Program Files\Tautulli\scripts\killstream\kill_stream.py
I updated each notification agent script with the good path.

Thanks

**Comment by blacktwin** [comment]
> i install pynthon (same version 3.8.6)

How did you install Python? python.org or Windows Store?

**Comment by fkalmes** [comment]
python.org

**Comment by blacktwin** [comment]
Can you create a simple python script and try to run it using the Test Script button in the Test Notifications section of the agent?

simple script:
```python
import os
import sys
print(sys.prefix)
print(vars(os.environ))
```

The error code: 9009 suggests that Tautulli can't find Python but as you've provided `python` is set in `PATH`.

**Comment by blacktwin** [comment]
You should be seeing a wall of text when running that script.

**Comment by fkalmes** [comment]
Maybe i can try to reinstall Tautulli without the .exe?

**Comment by blacktwin** [comment]
It's not Tautulli, it's your python install.

**Comment by fkalmes** [comment]
yes but tautulli uses its own version of python with the .exe file, am I Right?

**Comment by fkalmes** [comment]
SOLVED, 

I move my python File from AppData to C:\Program Files, I set the PATH again , restart Tautulli ans everything works like a charm.

Thank you for you time and your amazing scripts ;)

**Comment by blacktwin** [comment]
Thanks for reporting back with your fix.
