### ISSUE TITLE
can allow subtitles transcode on Killstream.py script 

### ISSUE THREAD

**Issue by bison529** [blacktwin/JBOPS#284]
I am using Killstream.py on PLEX Server to terminate 4K transcodes, but some 4K movies have PGS subtitles, and this type is need to transcode on some PLEX App.

I have use Killstream from 
https://github.com/Cloudbox/Community/wiki/Tautulli-Custom-Scripts

**Comment by blacktwin** [comment]
https://github.com/blacktwin/JBOPS/tree/master/killstream#conditions-considerations
