### ISSUE TITLE
[Request] Killstream show IP of killed stream 

### ISSUE THREAD

**Issue by Kazz3r24** [blacktwin/JBOPS#285]
**Is your feature request an improvement on an existing script? Please link to script.**
An improvement on the Killstream script would be to show the IP of a stream that is killed in the Discord notification - Session key that is currently displayed doesn't really do much good except to the Plex service.

**Is your feature request related to a problem? Please describe.**
Not related to a problem, but this would be a vast improvement, especially since blocking can't be done by Tautulli or Plex natively.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by blacktwin** [comment]
You can customize the your rich notification however you'd like. What is in the script is a general output of information and a basic template of what can be done.

Add what you'd like [here](https://github.com/blacktwin/JBOPS/blob/40131f5c20911762ec240a39c8cc460a6cc86ca0/killstream/kill_stream.py#L453-L497). the `stream` object holds all the information about the stream that is being killed. Any of the stream parameters can be used and can be found following these [instructions](https://github.com/Tautulli/Tautulli-Wiki/wiki/Debugging#activity).

```python
                    "fields": [
                        {
                            "inline": True,
                            "name": "User",
                            "value": self.stream.friendly_name
                        },
                        {
                            "inline": True,
                            "name": "Session Key",
                            "value": self.stream.session_key
                        },
                        {
                            "inline": True,
                            "name": "Watching",
                            "value": self.stream.full_title
                        },
                        {
                            "inline": True,
                            "name": "IP Address",
                            "value": self.stream.ip_address   # Your request
                        },
                        {
                            "inline": False,
                            "name": "Message Sent",
                            "value": message
                        }
                    ],
```

**Comment by Kazz3r24** [comment]
Oh perfect! Thank you for pointing that out to me.
