### ISSUE TITLE
Hi I just need to know JBOPS scrips support python 3.9

### ISSUE THREAD

**Issue by Anuruddha094** [blacktwin/JBOPS#287]
I'm planning to upgrade my python version to python 3.9 which supports by tautulli. But before I upgrade I just need to  know JBOPS supports python 3.9 or not.

Thank you very much

**Comment by blacktwin** [comment]
Should be ok. Report any issues you find.

**Comment by Anuruddha094** [comment]
@blacktwin thank you for the clarification. I will post here if any issues raised.
