### ISSUE TITLE
Killstream SSL error

### ISSUE THREAD

**Issue by Oke11** [blacktwin/JBOPS#289]
Hello,

I seem to be having an issue with Killstream not respecting the SSL Verify option being set to False, when running the script via Tautulli with SSL Enabled. 

I receive the following error:
```
Tautulli` Notifiers :: Script returned:
    Tautulli request failed for cmd 'terminate_session'. Invalid Tautulli URL? Error: HTTPSConnectionPool(host='localhost', port=8181): Max retries exceeded with url: /tautulli/api/v2?session_id=2anhbguxjggx90xakepjhuof&message=Oop+issue.&cmd=terminate_session&apikey=**************** (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))
```

Any idea on how to fix this?

**Comment by blacktwin** [comment]
I'll need your entire [logs](https://github.com/Tautulli/Tautulli/wiki/Asking-for-Support#how-can-i-share-my-logs). Also, what happens when you kill a stream from Tautulli (not the script) or when killing from Plex?

**Comment by Oke11** [comment]
hey @blacktwin.

The question was a by-product of trying to solve an issue with the Tautulli remote app that was unrelated to the script. I already had a https reverse proxy regardless so I didn't actually need to go down the avenue of enabling https within Tautulli. I think the error I posted might have been issues with the LetsEncrypt certificate I was using not registering though? Not entirely sure.

Anyway, I'll close this. The script is working fine.

**Comment by pannal** [comment]
This somewhat is still an issue. The `TAUTULLI_URL` environment variable doesn't seem to be respected.
