### ISSUE TITLE
playlimit error:  No JSON object could be decoded.

### ISSUE THREAD

**Issue by ajkis** [blacktwin/JBOPS#29]
play_limit.py script produces this error:

PlexPy Notifiers :: Script error:     PlexPy API 'get_history' request failed: No JSON object could be decoded.
--

**Comment by blacktwin** [comment]
Check your `PLEXPY_APIKEY` and `PLEXPY_URL`? How are you testing?

**Comment by ajkis** [comment]
Now i get:

> PlexPy Notifiers :: Script error:     Traceback (most recent call last):         File "/home/plex/scripts/py_watch_limit.py", line 67, in             if get_get_history(username) > WATCH_LIMIT[username]:     KeyError: 'Ajki'

--

**Comment by blacktwin** [comment]
Is `'Ajki'` in your `WATCH_LIMIT` dict?

```python
WATCH_LIMIT = {'user1': 2,
               'user2': 3,
               'user3': 4}

```

**Comment by ajkis** [comment]
No its 
WATCH_LIMIT = {'iShiki': 1 }

**Comment by blacktwin** [comment]
But you tested it using `'Ajki'`. If the name is not in the dict then the script will error out, which it should because the user `'Ajki'` is not defined. Does that make sense? If need be I can pretty it up so say `User is not defined in WATCH_LIMIT, skipping`

**Comment by ajkis** [comment]
Should I use id instead of usernames, since user Ajki is my main account.

**Comment by blacktwin** [comment]
This [section of the script](https://github.com/blacktwin/JBOPS/blob/master/killstream/watch_limit.py#L44-L49):

```python
def get_get_history(username):
    # Get the PlexPy history.
    payload = {'apikey': PLEXPY_APIKEY,
               'cmd': 'get_history',
               'user': username,  # <------ here
               'start_date': TODAY}
```
is calling for the `user` based on the [API doc for PlexPy](https://github.com/JonnyWong16/plexpy/blob/master/API.md#get_history). If you want to change it to `user_id` then go ahead but then change that section of the script to:

```python
def get_get_history(username):
    # Get the PlexPy history.
    payload = {'apikey': PLEXPY_APIKEY,
               'cmd': 'get_history',
               'user_id': int(username), 
               'start_date': TODAY}
```
 the `username` value needs to be an `int` (based on the API doc). Change it however you want.

But again if the id or username is not defined in the dict the script fail, which it should. If the username or id is not defined think of it as ignoring that user. So if you want your main account `Ajki` to be ignored, don't add it to the dict. Does that make sense?

**Comment by ajkis** [comment]
Yup, working
