### ISSUE TITLE
Kill stream based on IP range?

### ISSUE THREAD

**Issue by spdrcr5** [blacktwin/JBOPS#291]
Is it possible to use Killstream to prevent a range of IPs from being able to play anything?

Thanks

**Comment by Anuruddha094** [comment]
@spdrcr5 yes you can. you need to use kill_stream.py.  You can whitelist all ips who you want to allow media streaming and who is not in that list will be blocked by the script.

https://github.com/blacktwin/JBOPS/tree/master/killstream#ip-whitelist

cheers

**Comment by spdrcr5** [comment]
Appreciate the answer and info. Unfortunately that wouldn’t work as I know
people connect using mobile devices and others travel including myself. I
would prefer to blacklist a set of known ranges.

Thanks

**Comment by Anuruddha094** [comment]
@spdrcr5 I think @blacktwin will reply you soon. He is the creator of all those scripts. Anyway why don't you block unwanted users by username or email.

Conditions: [ Username | is | Bob ] 
Conditions: [ email | is | bob@bobemail.com ]

https://github.com/blacktwin/JBOPS/tree/master/killstream#kill-all-of-a-users-streams-with-notification

cheers

**Comment by spdrcr5** [comment]
A friend is sharing his Plex account with someone and I want to block them
entirely. Not worth getting into a fight about it. Just pisses me off. I
figured if I could block the entire ISPs block of IPs it would knock them
off. They are out of state and it could work.

**Comment by spdrcr5** [comment]
I see it says Begins With.  Maybe that would accept the first 2 octets?
Meaning if I enter 57.25. Would that cover all IPA?

**Comment by blacktwin** [comment]
If someone is account sharing then remove them or unshare your libraries with them until they change their password. This is a lot simpler than what you're attempting to. If this causes a "fight" then you have something else to consider. Generosity has it's limits.
