### ISSUE TITLE
Getting it running on Windows Server

### ISSUE THREAD

**Issue by magoralczyk** [blacktwin/JBOPS#293]
I am needing some support for getting the scripts running. Plex and Tautulli both are installed on a windows server and are working. Both applications bring their own python, but I had also a seperate older Python 2.7 Installation on the server. The Scripts were triggered, but du to the python 2.7 in the PATH, the script was not working (could not import module buildin). After deinstallation of the seperate python, now the script is no longer found. I can browse for the script folder and in the dropdown I find the script file, but when triggered in the tautulli log I find the error 
Tautulli Notifiers :: Failed to run script: [WinError 2] The system cannot find the specified file. 
I tried to put the file everywhere, gave everyone all rights.
Then I tried a new seperate python installation, but this responded in the same error in tautulli, but when I run the script manually from windows command line by 
python Z:\\path\\to\\script\\limiterr.py args
it runs the script...

**Comment by blacktwin** [comment]
Can you please provide your Tautulli log? Please follow these [instructions](https://github.com/Tautulli/Tautulli/wiki/Asking-for-Support#how-can-i-share-my-logs).
