### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by goku-son** [blacktwin/JBOPS#296]
**Describe the bug**

Updating existing Aires today playlist does not update the playlist, but instead creates a new one. 

playlist_manager.py --jbop historyToday --libraries Movies "TV Shows" --action update --allUsers 

The above command runs as a cron job every day.  After several days, I got aired today playlists for each instance executed. 

I expect unless I understand the syntax incorrectly, that the update action should replace the previous playlist not create a new one. It’s like if I was using the add action. 

Any ideas? Running latest versions of scripts with python 3.7. Thanks in advance.

**Comment by blacktwin** [comment]
Are you changing the name afterwards? That script should have logs, can you them in a gist?

**Comment by goku-son** [comment]
Hi at @blacktwin here is the link to the gist:

https://gist.github.com/goku-son/efef1e4d2308162132e14af690ff57f1

For example, right now I got 3 plays lists for aired today:

Aired Today 5-27 in History 
Aired Today 5-28 in History 
Aired Today 5-29 in History 

I did not see anything in the logs, but I may have missed something.

**Comment by goku-son** [comment]
I just went the nuclear option and delete all playlists and recreate them.
