### ISSUE TITLE
Limit populartv playlist

### ISSUE THREAD

**Issue by goku-son** [blacktwin/JBOPS#297]
Is there a way to limit the populartv playlist? It produces hundreds of items amounting to days worth of content. I tried using the “—limit 10” option, but it appears to ignore that flag.

**Comment by blacktwin** [comment]
Seems to work fine for me.

PlexAPI 4.5.2 & 4.6.0 work just fine. Can you provide more detail? An example?

**Comment by goku-son** [comment]
Here is the command I am running

‘’’
/source/fun/playlist_manager.py --jbop popularTv --libraries "TV Shows" --action update --limit 10 --allUsers --user Ben
‘’’

How can I determine what plexapi version I running?

**Comment by blacktwin** [comment]
The limit would be for shows. So 10 shows. Which could have 109 episodes combined.
