### ISSUE TITLE
Feature Request: Kill stream based if user see Library X 

### ISSUE THREAD

**Issue by ajkis** [blacktwin/JBOPS#30]
How can I modify: watch_limit.py to be based if user have access to Library X eg:

If user have shared Library A then watch limit is 1, Library B watch limit is 5, Library C watch limit = unlimited.

**Comment by blacktwin** [comment]
Cool idea. I'll look into adding this or maybe creating a more robust all in one solution for limits.

**Comment by ajkis** [comment]
Great.

**Comment by ajkis** [comment]
Is there a way to send kill stream text to user

**Comment by blacktwin** [comment]
Like a text message?

**Comment by ajkis** [comment]
Yes the:

![image](https://user-images.githubusercontent.com/23003132/32668741-ae5a6fe4-c63e-11e7-8597-0fcc9310a433.png)

**Comment by blacktwin** [comment]
the `MESSAGE = 'You have reached your play limit for today.'` is what gets sent to the user's client. Is that what you're asking?

**Comment by ajkis** [comment]
Yes
