### ISSUE TITLE
Playlist Manager script adds then deletes custom playlist

### ISSUE THREAD

**Issue by irodimus** [blacktwin/JBOPS#303]
**Describe the bug**

Updated to commit a479596b350f3a2d44e279ee787e1ad0dfa9e19c for playlist_manager.py script. Use the script with random to create genre related playlists. When running script using the update command, it will delete any playlist showing and then add a new playlist like normal. On the next loop, it will delete the last created playlist and create a new playlist, repeating depending how many times you run the command.

**To Reproduce**

1. Create a new "playlist_1". 
2. Run playlist manager using the update command creating a new "playlist_2" as well.
3. "playlist_1" will be deleted and the script will create "playlist_2"
4. If you had run the script again, "playlist_2" will be deleted and "playlist_3" will be created.

```plex-ht:Scripts administrator$ sh channels.sh
Deleting the playlist(s)...
...Deleted Playlist: 45 Futurama for 'admin'.
Creating playlist(s)...
...Added Playlist: 01 Science Fiction to 'admin'.
Done.
Deleting the playlist(s)...
...Deleted Playlist: 01 Science Fiction for 'admin'.
Creating playlist(s)...
...Added Playlist: 02 Action to 'admin'.
Done.
Deleting the playlist(s)...
...Deleted Playlist: 02 Action for 'admin'.
Creating playlist(s)...
...Added Playlist: 03 Comedy to 'admin'.
Done.
```

**Expected behavior**

Delete the previous playlist and create(update) the new playlist 

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Python Version [3.9.5]
 - PlexAPI version [4.6.1]

**Comment by blacktwin** [comment]
What are the arguments you're using?

**Comment by irodimus** [comment]
Here is the first command:
```
python3 playlist_manager.py --jbop random --action update --name "01 Science Fiction" --libraries Movies --limit 50 --filter genre=sci-fi
```
I have a script that then goes into another command like this using a different playlist name and genre.

**Comment by blacktwin** [comment]
Can you check this update?

**Comment by irodimus** [comment]
Tested the new commit, https://github.com/blacktwin/JBOPS/commit/c84cee5fece9d53bfad6f5273e71d71bf70e506a, and it appears to have resolved the issue. Thank you!
