### ISSUE TITLE
[Feature Request] Playlist Manager - Copy playlist poster when using Share action

### ISSUE THREAD

**Issue by rg9400** [blacktwin/JBOPS#304]
**Is your feature request an improvement on an existing script? Please link to script.**
https://github.com/blacktwin/JBOPS/blob/master/fun/playlist_manager.py
Request is to copy over playlist poster when using Share action on this script.

**Is your feature request related to a problem? Please describe.**
Not really a problem, but Plex added an option in the UI to add posters to playlists. I added a top 250 poster onto my top 250 playlist which is updated daily. I re-share this playlist on a daily basis to users, and it would be good for them to see the top 250 logo instead of the auto-generated Plex one

**Describe alternatives you've considered**
Just live with the auto generated Plex playlist poster

**Comment by blacktwin** [comment]
Users can't change a poster so I assume this would not be possible. I haven't really looked into past confirming that users can't change posters on the playlists.
