### ISSUE TITLE
kill_stream Condition different IP

### ISSUE THREAD

**Issue by nomascashtv** [blacktwin/JBOPS#305]
Hello, I am trying to configure your script on my server, currently I have it installed and to kill the transcodes it works perfectly, also to kill the streams with more than 2 devices simultaneously. My problem is that I also want to kill the streams that have a different IP, along with their respective warning message, I do not understand what conditions I have to add, I have used the following but it does not work:
 
{ip_address} / not is / =

I don't know if I should post here, I'm new and I don't really understand if it's allowed. Thanks in advance.

**Comment by blacktwin** [comment]
> I also want to kill the streams that have a different IP

Different than what? Something different than [this](https://github.com/blacktwin/JBOPS/tree/master/killstream#limit-user-streams-to-one-unique-ip)?

**Comment by blacktwin** [comment]
Need some more feedback from you or I can close this.
