### ISSUE TITLE
Discord Notifications Not Embedding

### ISSUE THREAD

**Issue by mattyteds** [blacktwin/JBOPS#310]
Normally my Discord agent works with Tautulli but when the kill_stream script triggers it the bot's messages are not embedding correctly. This is what the bot posts:
` tautulli: {"embeds": [{"author": {"icon_url": "https://github.com/Tautulli/Tautulli/raw/master/data/interfaces/default/images/logo-circle.png%22,%22name": "Tautulli","url": "http://REDACTED/tautulli/tautulli%22%7D,%22color": 15048717,"fields": [{"inline": true,"name": "User","value": "REDACTED."},{"inline": true,"name": "Session Key","value": "248"},{"inline": true,"name": "Watching","value": "Dragon Ball Z - Welcome Back Goku"},{"inline": false,"name": "Message Sent","value": "Unauthorized client. Contact the Plex admin for help."}],"footer": {"text": "REDACTED | Kill Stream"},"thumbnail": {"url": "http://REDACTED/tautulli/tautulli/image/REDACTED,%22timestamp": "2021-09-07T15:46:35.618812","title": "Killed REDACTED's stream.","url": "https://app.plex.tv/desktop#!/server/REDACTED/details?key=%2Flibrary%2Fmetadata%2F27228%22%7D]%7D`

I have Include Rich Metadata Info, Include Link to Plex Web, and Use Poster Thumbnail all checked in the Discord agent but it does the same thing if I uncheck them. And the Discord agent can normally embed messages.

Also if you enabled Include Subject Line in the Discord agent settings the notification from kill_stream fails to send because there is no subject.

**Comment by blacktwin** [comment]
Can you please provide the entire log file?

**Comment by mattyteds** [comment]
The above was a copy and paste of the message in Discord. I assume you mean the Tautulli log file since you didn't specify. Here it is but there is nothing useful logged because everything works as intended, it's just not formatted correctly.

[tautulli.log](https://github.com/blacktwin/JBOPS/files/7145469/tautulli.log)

**Comment by blacktwin** [comment]
Please add `--debug` to your arguments and share your **_entire_** log.

**Comment by mattyteds** [comment]
This is the **_relevant_** log file.  You will **not** be getting my **_entire_** log file because I am competent enough to trim a log file, my log file goes back 3 months and I've had this script a week. Still pretty certain this is a syntax or formatting issue with how the embed is actually being generated and passed to the Discord notification agent, but anyways.

[tautulli.log](https://github.com/blacktwin/JBOPS/files/7148142/tautulli.log)

**Comment by blacktwin** [comment]
You need to be using a [Webhook agent](https://github.com/blacktwin/JBOPS/tree/master/killstream#webhook-setup).

**Comment by mattyteds** [comment]
I'm really curious what you think I'd be using instead of that with Tautulli to send Discord notifications...?

![Untitled](https://user-images.githubusercontent.com/1725926/133310073-a45bea1d-d27a-48a8-a998-7f4f22ddaa91.png)

Like I said, Discord notifications work with Tautulli, I even provided a screenshot of it working. Do are you able to send Discord notifications with script on your setup?

**Comment by blacktwin** [comment]
@mattyteds did you get it working?

**Comment by mattyteds** [comment]
I did, it created a Webook Agent rather using the Discord Agent. But I am confused how you got a poster in your Discord example image [here](https://github.com/blacktwin/JBOPS/tree/master/killstream#webhook-setup).

**Comment by blacktwin** [comment]
Yeah. You would have the Discord Agent for say Recently Added or Watched statuses and the Webhook agent for using the kill script or if you wanted to setup a custom notification that is more than what is available in the Discord Agent.

**Comment by blacktwin** [comment]
Can you share pictures and logs?

**Comment by mattyteds** [comment]
![Untitled](https://user-images.githubusercontent.com/1725926/133317557-2cd5a63f-7174-4eef-975a-2b1fa6cd649f.png)
[tautulli.log](https://github.com/blacktwin/JBOPS/files/7164457/tautulli.log)

Based on the log it should be working.

**Comment by blacktwin** [comment]
That poster, errr logo, is correct. You're `Killing All Streams` so to account for when there are multiple sessions being killed it falls back to the Tautulli logo. Instead of attempting to choose a poster from all the sessions it's killing it falls back to the logo.

**Comment by mattyteds** [comment]
"**Limitations**

- Due to size limitations by Slack. A thumbnail may not appear with every notification when using --posterUrl {poster_url}.
- allStreams will not have poster images in the notifications."

I need to learn to read.

**Comment by blacktwin** [comment]
LOL it happens. All good now?

**Comment by mattyteds** [comment]
I think so. I just used:
`--notify 6 --richMessage discord --jbop stream --username {username} --sessionId {session_id}  --killMessage 'Unauthorized client. Contact the Plex admin for help.' --serverName {server_name} --plexUrl {plex_url} --posterUrl {poster_url} --richColor '#E5A00D'`

It appears to work. I don't think I need to kill all streams.
