### ISSUE TITLE
remove_inactive_users [Tautulli API 'get_users_table' request failed]

### ISSUE THREAD

**Issue by ados8** [blacktwin/JBOPS#311]
**Describe the bug**

Even when running directly in the docker I get this error every time:

**Tautulli API 'get_users_table' request failed. Error: Expecting value: line 1 column 1 (char 0)**

I will mention this is the first time using this script but I have filled out the settings:
PLEX_URL = 'http://[IP]:32400'
TAUTULLI_URL = 'http://[IP]:8181'

**Provide logs**

![image](https://user-images.githubusercontent.com/49982433/133245653-dbde7883-624b-4f55-9837-b32ec6664c09.png)

**Link to script with bug/issue**
remove_inactive_users.py

**To Reproduce**

1. Simply run even in dry run mode

**Expected behavior**
Tautulli API 'get_users_table' request failed. Error: Expecting value: line 1 column 1 (char 0)

**Screenshots**
![image](https://user-images.githubusercontent.com/49982433/133245916-462998f1-05e1-4547-a80d-a9caa745e671.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Python Version 3.9.6
 - Tautulli version V2.7.6

**Additional context**

**Comment by blacktwin** [comment]
Please provide your entire log file.

**Comment by ados8** [comment]
> Please provide your entire log file.

Thanks for your help
[tautulli.log](https://github.com/blacktwin/JBOPS/files/7169111/tautulli.log)
