### ISSUE TITLE
Refresh Next Ep

### ISSUE THREAD

**Issue by elit3ge** [blacktwin/JBOPS#313]
https://github.com/blacktwin/JBOPS/blob/57afb59f0bea30a79d15f09029ebc5ba53d29f83/utility/refresh_next_episode.py#L51

I'm obviously looking at this wrong.

Is the script meant to refresh the next episode just before the episode finishes?
Me reading that it's refreshing the season before it?

**Comment by blacktwin** [comment]
The description is pretty clear on what it does. What is the issue?

**Comment by elit3ge** [comment]
No issue as such. Just looking at the code and wondering how the current_season is season_num takeaway one. To me, that would be the season before?
