### ISSUE TITLE
Script (plex_theme_songs.py) dosn't work

### ISSUE THREAD

**Issue by Jerome2103** [blacktwin/JBOPS#316]
https://github.com/blacktwin/JBOPS/blob/bf605ab62834ab190418eb35a40e3297e7a7ef12/utility/plex_theme_songs.py#L25-L26

```
Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/config/scripts/JBOPS-master/utility/plex_theme_songs.py", line 29, in <module>
            PLEX_URL = CONFIG.data['auth'].get('server_baseurl', PLEX_URL)
    KeyError: 'auth'
```
The URL and Token is correct. The variables are correct in the file and work with other scripts.

**Comment by blacktwin** [comment]
If you're not using the config file then just comment out those two lines for now. Or 
https://github.com/blacktwin/JBOPS/blob/bf605ab62834ab190418eb35a40e3297e7a7ef12/fun/playlist_manager.py#L151-L154
A lot of these scripts are me learning the language or quick little ideas or requests from someone else. So there are some inconsistencies in the structure across the project. That and being too busy or too lazy to want to clean it up.

**Comment by Jerome2103** [comment]
Even if I paste the url in the script, it doesn't work
