### ISSUE TITLE
aired_today_playlist makes playlist of ALL episodes from previous years 

### ISSUE THREAD

**Issue by seanvree** [blacktwin/JBOPS#32]
aired_today_playlist makes the playlist great.  However, it also includes all episodes on the current date but from previous years as well. 

Example below:

![image](https://user-images.githubusercontent.com/8906637/32916775-e3352e24-cad1-11e7-85fc-23fb7234555f.png)

**Comment by blacktwin** [comment]
Yeah that is the intent. It's "This Day In History" kinda thing. Whatever aired 11/16 for any year.

**Comment by seanvree** [comment]
Oh shoot, don't I feel like a horses rear.  I was using it for what aired today actually. 

Ha, I'll go ahead and close this now.

**Comment by blacktwin** [comment]
The name and description is terrible. I should just put This Day In History.

**Comment by seanvree** [comment]
Yup, this is all your fault @blacktwin 

JK. 

What are you using for Today only?

**Comment by blacktwin** [comment]
> What are you using for Today only?

Recently added? If you wanted to use this script to do just Today then you could modify it.

**Comment by seanvree** [comment]
Ha, right, but I wanted an actual playlist for the stuff that aired only today.  All good brotha.  Keep up the good fight.
