### ISSUE TITLE
Playlist Manager - Remove Playlists

### ISSUE THREAD

**Issue by sydtrakked** [blacktwin/JBOPS#323]
**Describe the bug**

Playlist Manager Script

Trying to delete All Playlists from All Users using the following arguments:
--action remove --allUsers --allPlaylists

**Provide logs**
https://gist.github.com/sydtrakked/b48b52261f9e2de0f9ecc0fa8934834f

**Link to script with bug/issue**
https://github.com/blacktwin/JBOPS/blob/master/fun/playlist_manager.py

**To Reproduce**
Test Script in Tautulli with above args

Ran in Powershell with same args

Both result in 
Log returns:
 Deleting the playlist(s)...
    Done.

**Expected behavior**
Delete Shared Playlists from all Plex friends

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 310
 - PlexAPI version 4.8.0

**Additional context**

**Comment by blacktwin** [comment]
This shouldn't be ran through Tautulli. What does `--action show --allUsers` show you?
