### ISSUE TITLE
Plex/LIFX Script Error

### ISSUE THREAD

**Issue by sydtrakked** [blacktwin/JBOPS#324]
**Describe the bug**

Receiving this error in Tautulli Logs when script is trying to run:

Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "c:\Plifx\plex_lifx_LivingRoom.pyw", line 22, in <module>
            import numpy
    ModuleNotFoundError: No module named 'numpy'

**Provide logs**
https://gist.github.com/sydtrakked/26326383a5ac6e46ff4105e5ac67db4b

**Link to script with bug/issue**
https://github.com/blacktwin/JBOPS/blob/master/fun/plex_lifx_color_theme.pyw

**To Reproduce**

1. Play some content
2. Script doesn't run successfully

**Expected behavior**
Script should run and update LIFX lights

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.10
 - PlexAPI version [e.g. 4.1.0]

**Comment by snaj06** [comment]
For me it's : 

  File "/home/xxxxxx/bin/plex_api_poster_pull.py", line 73, in <module>
    urllib.request.urlretrieve(thumb_url, image_path)
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Since few days.

**Comment by blacktwin** [comment]
@philosowaffle pinging you as I do not have the required environment and you are the creator.

**Comment by philosowaffle** [comment]
@blacktwin this looks like a simple dependency issue.  Is the [global requirementes.txt](https://github.com/blacktwin/JBOPS/blob/master/requirements.txt) where you want scripts to add packages they need?

For reference, here is the original `requirements.txt` file for this script: https://github.com/philosowaffle/plex-lifx-webhook/blob/master/requirements.txt#L3

**Comment by blacktwin** [comment]
Ugh, I didn't even read this issue before pinging you... Sorry about that @philosowaffle. Let's leave it as is for now.

@sydtrakked you need to install the missing module that is listed in the error message. You can do by running `pip install numpy` in cmd.

**Comment by philosowaffle** [comment]
@sydtrakked full list of things you might need to install:

```
> pip install numpy
> pip install colorthief
> pip install pifx==0.0.3
```

**Comment by sydtrakked** [comment]
so weird because it's been working fine for so long and I haven't made any changes. Sorry for any time wasted on your parts!
Thanks for checking in on everything.

**Comment by sydtrakked** [comment]
So the change that did happen is actually that my server is using Python 3.X now and it appears that urllib.urlretrieve has been deprecated. 

I'm pretty noobish with python but maybe you would be able to update this script more efficiently than I can? From what I gather urlretrieve is now within urlib.request function
