### ISSUE TITLE
Killstream killing a stream that is being direct played 

### ISSUE THREAD

**Issue by rainman369** [blacktwin/JBOPS#328]
99.9% of my content is 1080p and higher and killstream has been working great. I have one movie I am trying to watch, which is in 720p, that is being killed. I look at it on Tautulli and it is definitely direct play, so I'm not sure why this would be happening. I'm using the default arguments provided for killstream.py.

**Comment by rainman369** [comment]
Update: This seems to play fine on a mobile device but the error persists when trying to watch the movie on my TV.

**Comment by Atomatth** [comment]
Without logs I have no idea.

**Comment by blacktwin** [comment]
Without logs I don't know

**Comment by rainman369** [comment]
> Without logs I don't know

Sorry about that, I think this spells it out the clearest:  [https://imgur.com/a/lyNX4kN](url)

**Comment by blacktwin** [comment]
Without the entire logs, not a picture, I can assume that it started transcoding initially then changed to direct play?
