### ISSUE TITLE
The system cannot find the specified file

### ISSUE THREAD

**Issue by Harybo** [blacktwin/JBOPS#331]
**Describe the bug**

Hello,
My tautulli does not want to run the killstream script. But I manage to make it work manually in a cmd

**Provide logs**

[tautulli.log](https://github.com/blacktwin/JBOPS/files/8053594/tautulli.log)

**Link to script with bug/issue**

kill_stream.py

**To Reproduce**

python kill_stream.py --jbop stream --userId 127009871 --sessionId ga9tgf3loo5jy70kx3no7jig --killMessage 'blabla'

**Desktop (please complete the following information):**
 - OS: Windows Server 2022
 - Python Version 3.10.2

![Screenshot_4](https://user-images.githubusercontent.com/29784405/153714899-4eff56ae-5ad8-4fdc-b489-349ef9f68f8c.png)

**Comment by blacktwin** [comment]
Follow this [guide](https://github.com/Tautulli/Tautulli/wiki/Custom-Scripts#windows-script-guide), please.
