### ISSUE TITLE
Python newbie problem

### ISSUE THREAD

**Issue by nicolasrata** [blacktwin/JBOPS#332]
Hi,
I'm trying to use the hide spoilers script but I keep getting the same error.
`Tautulli Notifiers :: Script error: 
    Traceback (most recent call last): 
        File "/Users/Ni********a/JBOPS/utility/hide_episode_spoilers.py", line 31, in <module> 
            import requests 
    ImportError: No module named requests`

I'm using a Mac mini M1, macOS 12.2.1
Tautulli installed via the installer
python3.9.10 installed with Homebrew and aliased ton python
pip 22.0.3 installed with Homebrew
requests in /opt/homebrew/lib/python3.9/site-packages (2.27.1)

Any idea why it keeps asking for requests?

Thanks

**Comment by blacktwin** [comment]
Follow this [guide](https://github.com/Tautulli/Tautulli/wiki/Custom-Scripts#windows-script-guide), please. Specifically [here](https://github.com/Tautulli/Tautulli/wiki/Custom-Scripts#how-to-install-python-packages).

**Comment by nicolasrata** [comment]
Hi,
I have installed the requirements before running the script.
plexapi and requests are installed.
`% pip freeze
PlexAPI==4.9.1
requests==2.27.1
requests-cache==0.5.2
requests-oauthlib==1.3.0
`

The script run ok manually but in Tautulli it keeps outputting the same error.
I see Tautulli uses Python3.9.10.
I have add to my path `export PATH="/opt/homebrew/opt/python@3.9/libexec/bin:$PATH"`
which python shows `/opt/homebrew/opt/python@3.9/libexec/bin/python`

Don't understand why it won't work from Tautulli.
Any idea?
