### ISSUE TITLE
How to for sync_watch_status ?

### ISSUE THREAD

**Issue by Ltek** [blacktwin/JBOPS#337]
I have read the script but its not very clear on the setup hoping someone can help...

`Set Conditions: [{username} | {is} | {user_to_sync_from} ]`
Seems this argument cannot be put directly into "Condition Logic" as the instructions seem to imply. So, are we supposted to create a condition that selects from the drop-down menus 'Username'  'is' and enter {user_to_sync_from} in the 3rd box (which is text entry)?

```
Script Arguments:
 Select: Notify on Watched
 Arguments: --ratingKey {rating_key} --userFrom Tautulli=Tautulli --userTo "Username2=Server1" "Username3=Server1"
```
Which are the variables we need to change? 

For instance, I have four users (MediaRoom, LivingRoom, Office, PlayRoom) and one server (Plex @ 192.168.2.60). Is this correct ...

--ratingKey {rating_key} --userFrom Tautulli=Tautulli --userTo "MediaRoom=Plex" "LivingRoom=Plex" "PlayRoom=Plex" "Office=Plex"

**Comment by blacktwin** [comment]
![image](https://user-images.githubusercontent.com/22177672/161194026-01f7e963-0f36-46a7-8dd0-c3f453e58c73.png)

If you `Ltek` watch something this script will execute, thus using your user's watch status to update the `--userTo` users.

`--ratingKey {rating_key} --userFrom Tautulli=Tautulli --userTo "MediaRoom=Plex" "LivingRoom=Plex" "PlayRoom=Plex" "Office=Plex"`

If `Plex` is the name of your server, then yes.

**Comment by Ltek** [comment]
@blacktwin I tried that but Tautulli will not let me save the Notification... error shows: " Invalid condition logic."

Username is MediaRoom  

I tried both 
--ratingKey {rating_key} --userFrom Tautulli=Tautulli --userTo "LivingRoom=Plex" "PlayRoom=Plex" "Office=Plex"

and 
--userFrom Tautulli=Tautulli --userTo "LivingRoom=Plex" "PlayRoom=Plex" "Office=Plex"

**Comment by blacktwin** [comment]
Just add more usernames to your condition.
