### ISSUE TITLE
Added a condition if someone is watching on the same device

### ISSUE THREAD

**Issue by Harybo** [blacktwin/JBOPS#339]
For killstream.py

Added a condition if someone is watching on the same device and the stream is not yet cut due to a bug. That his new streams are not counted and that he is not killed

**Comment by Harybo** [comment]
![Capture](https://user-images.githubusercontent.com/29784405/161457654-de705f6a-87b7-40f4-9a3e-178d7f66ee40.PNG)


Here is an example of what I would like to do. In the screenshot of course it can't work but here is the idea

**Comment by Harybo** [comment]
> Can you give me more of an example for when this issue happens? What's the bug? Is it specific to a client?

I don't have an example at hand but for example. Someone is watching on a computer with the PLEX application windows but the connection goes down for a while. The flow is still considered to be in progress by PLEX server. But it will not be able to restart on the same computer if the maximum number of flows allowed is set to 1. So I would like to have a condition if the person reads a flow on the same computer that does not count it in the maximum flows allowed to the user.

**Comment by blacktwin** [comment]
I still don't understand the issue here. Please reopen when you have steps to reproduce the scenario you want to solve for.
