### ISSUE TITLE
sync_watch_status - Pending Invite Breaks Script

### ISSUE THREAD

**Issue by Deadly-Bytes** [blacktwin/JBOPS#341]
When running sync_watch_status.py from cmd line the following error occurs:

`Connecting to admin server(s) for access info...
Traceback (most recent call last):
  File "sync_watch_status.py", line 436, in <module>
    plex_access = plex_admin.users_access()
  File "sync_watch_status.py", line 270, in users_access
    sections = {section.title: section for section in server.sections()
  File "/usr/local/lib/python2.7/dist-packages/plexapi/myplex.py", line 725, in sections
    data = self._server.query(url)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/myplex.py", line 178, in query
    raise BadRequest('(%s) %s %s; %s' % (response.status_code, codename, response.url, errtext))
plexapi.exceptions.BadRequest: (404) not_found https://plex.tv/api/servers/None/shared_servers/None; <?xml version="1.0" encoding="UTF-8"?> <errors>   <error>Not found</error> </errors>`

A user with the same problem motioned it in discord:
https://discord.com/channels/183396325142822912/283629564087762945/619231287860789248

The fix, as suggested by @blacktwin is to remove any pending invites. After removing pending invites the script runs correctly. I can confirm that was the case for me as well.

This is a bit of an annoying bug as anytime there is a pending invite on the server the script fails and will remain broken until the invite is either accepted of removed, and sometimes an invite can be pending for a relatively long time.

Greatly appreciate this script, it's really critical to keeping two accounts in sync.

Thank you

**Comment by blacktwin** [comment]
I'm not seeing this issue.... Doesn't look like the pending invites are being pulled in anymore. Might have been a PlexAPI update, I can't remember. Can you please confirm @Deadly-Bytes ?

**Comment by Deadly-Bytes** [comment]
Sorry for the late reply. I also don't know what changed but I don't see the issue anymore. Happy it's working consistently now. Thank you for this. It's really great being able to sync the watch statuses.
