### ISSUE TITLE
plex_netflix_check - Add Disney+

### ISSUE THREAD

**Issue by PierreDurrr** [blacktwin/JBOPS#346]
**Is your feature request an improvement on an existing script? Please link to script.**
Would it be possible to improve **plex_netflix_check** to include Disney+ comparison ?
[https://github.com/blacktwin/JBOPS/blob/master/reporting/plex_netflix_check.py](https://github.com/blacktwin/JBOPS/blob/master/reporting/plex_netflix_check.py)

**Is your feature request related to a problem? Please describe.**
Not really

**Describe alternatives you've considered**
None yet as this script is almost perfect

**Additional context**
-

**Comment by blacktwin** [comment]
Please use https://github.com/blacktwin/JBOPS/blob/master/reporting/streaming_service_availability.py
