### ISSUE TITLE
Kill stream not saving video progress

### ISSUE THREAD

**Issue by zeroquinc** [blacktwin/JBOPS#356]
**Describe the bug**

Whenever someone gets terminated with the following script, Plex doesn't remember the progress anymore and people have to manually skip forward again. This is annoying if you exactly forgot where you left off, if you stop it manually it does save the progress.

**Provide logs**

https://pastebin.com/FGj92uNW

It's the following script:

Kill non-local streams paused for a long time
The default values will kill anything paused for over 20 minutes, checking every 30 seconds.

Script Timeout: 0 Important!
Triggers: Playback Paused
Conditions: [ Stream Local | is not | 1 ]

Arguments:

--jbop paused --sessionId {session_id} --killMessage 'Your stream was paused for over 20 minutes and has been automatically stopped for you.'

**To Reproduce**

1. Configure the script
2. Let someone pause the stream for 20mins.

**Expected behavior**
I expect it to stop their stream but save playback progress.
Is this normal behavior?

**Desktop (please complete the following information):**
 - OS: Docker
 - Python Version latest
 - PlexAPI version latest

**Comment by blacktwin** [comment]
What is the client that is being killed? Some clients are slower than other to update or receive updates.

If progress is being lost then it's the client that hasn't sent the latest view offset value back to the PMS or the client hasn't checked back from PMS to know the last offset value. 

Ultimately this isn't an issue with the script but a shortcoming of the client or the feature.
