### ISSUE TITLE
Your "buy me a beer/coffee" links are broken :) 

### ISSUE THREAD

**Issue by myrison** [blacktwin/JBOPS#357]
**Describe the bug**

I wanted to thank you for your useful scripts and tried to buy both a coffee and beer, and both result in a 403 forbidden error when you click on them.  Let me know if you get it fixed, I still owe you a drink!  Cheers.

**Comment by blacktwin** [comment]
Links are to PayPal with static amounts in the url. https://www.paypal.com/paypalme/Adam581/ should work too. Not sure if this is still an issue for you but I'm not able to reproduce.

**Comment by myrison** [comment]
Thanks @blacktwin , it must have been a temporary issue as it's working now.  One beer payment on the way!
