### ISSUE TITLE
Kill Message and notification aren't working

### ISSUE THREAD

**Issue by Kazz3r24** [blacktwin/JBOPS#358]
**Describe the bug**

Not sure if this is a bug, I've been trying to test the killstream.py for 4K streams on my Nvidia Shield, the stream seems to get killed but just with a generic error from Plex that there was an error trying to play it. The Discord rich message is also never sent. Discord notifications work for the other agents I have configured so there's no problem there.

From what I can tell, if my syntax is off then the script just error's out period stating it's either missing the --jbop argument, "stream" is missing or "discord" is missing as arguments - so I've now put quotes around them like below and it does still kill the stream, so this tells me parts of it are working correctly.

Playback Start event and Transcode Decision Change are set as triggers with the following arugments:
`--jbop "stream" --username {username} --sessionId {session_id} --notify 2 --richMessage "discord" --killMessage "Please set your REMOTE VIDEO QUALITY to ORIGINAL/MAXIMUM for 4K or select 1080p version if you're not on a 4K capable device."`

**Provide logs**

https://gist.github.com/Kazz3r24/d88596e2963a1c918c624668c4edcb5d

Tautulli logs - Please follow [Tautulli's guide](https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support#how-can-i-share-my-logs) for sharing logs. Please provide a link to a gist or pastebin.

PlexAPI logs - Create or find your logs location for [PlexAPI](https://python-plexapi.readthedocs.io/en/latest/configuration.html). Please follow [Tautulli's guide](https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support#how-can-i-share-my-logs) for sharing logs. Please provide a link to a gist or pastebin.

**Link to script with bug/issue**

**To Reproduce**

1. Configure Discord agent
2. Configure killstream.py
3. Create 4K kill stream notification

**Expected behavior**
I expect when a stream starts and meets the criteria that the stream be killed (which it is) but then a message as to why it was killed should be displayed instead of a generic Plex error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Python Version 3.8
 - PlexAPI version latest

**Additional context**
Parts of the script are working, so I'm under the impression I've made a mistake somewhere, but from what I can tell I've followed every guide available for this.

**Comment by f4hd** [comment]
--norify discord

Try without quotations ?

**Comment by Kazz3r24** [comment]
I tried that when I was first troubleshooting this. Quotations didn't make any difference being there or not.
I was in the Discord getting support there, the message does work just seems spotty when using a pre-roll.

It seems to work for other users, just not my Shield which doesn't matter much. I'll close this.
