### ISSUE TITLE
plex_api_share - all users?

### ISSUE THREAD

**Issue by haltdev** [blacktwin/JBOPS#36]
Hello,

Listing each user seperated by a space throws invalid argument errors.
```
root@media:/opt/plexpy/scripts# python plex_share.py -s share_all -u User1 User2
usage: plex_share.py [-h] -s  [-u ] [-l  [...]]
plex_share.py: error: unrecognized arguments: User2
```

Really what I would like is an "all users" option - is that possible?  I tried changing opts.user to user_lst but that throws all kinds of errors I'm too ignorant to know how to deal with.  Could an all users option be easily added?

I typically I want to Share or Unshare All Libraries with All Users (i.e. when my data cap for the month is reached).

**Comment by blacktwin** [comment]
Yeah as of right now the script will only take one username. It can be modified to what you're asking.

**Comment by blacktwin** [comment]
Ok added multiple user support. now `script.py -s share -l lib1 lib2 -u user1 user2` will work.

For all users just edit the for loop at the bottom to:

```python
for user in user_lst:
```
