### ISSUE TITLE
Issue with missing .png files

### ISSUE THREAD

**Issue by NicodemPL** [blacktwin/JBOPS#360]
**Describe the bug**

Whatever I do script does not work due to lack of .png file to be blurred. I have local media asset turned on for TV series.
Any idea what is missing?

**Provide logs**

Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/config/scripts/hide_episode_spoilers.py", line 123, in <module>
            modify_episode_artwork(plex, **vars(opts))
        File "/config/scripts/hide_episode_spoilers.py", line 99, in modify_episode_artwork
            with open(episode_artwork, 'wb') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tv/The Thing About Pam/Season 1/The.Thing.About.Pam.S01E04.1080p.BluRay.x264-BORDURE.png'

**Comment by blacktwin** [comment]
This could be a permissions issue. There is [another thread](https://github.com/blacktwin/JBOPS/issues/334) with other people mentioning a similar issue.
