### ISSUE TITLE
Error when trying media manager

### ISSUE THREAD

**Issue by cyturralde** [blacktwin/JBOPS#362]
Using code 
`python "\media-manager.py" --libraries "*library*" --select watched --users *user* --action delete `

I get the error below. I am running this through a bat file if that matters.

Finding watched items from user: *username*
Checking library: '*library*' watch statuses...
The following items were added before None and marked for deletion.
Traceback (most recent call last):
  File "\media-manager.py", line 774, in <module>
    plex_deletion(watched_by_all, libraries, opts.toggleDeletion)
  File "\media-manager.py", line 325, in plex_deletion
    section = plex.library.sectionByID(_library.key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\plexapi\library.py", line 84, in sectionByID
    raise NotFound(f'Invalid library sectionID: {sectionID}') from None
plexapi.exceptions.NotFound: Invalid library sectionID: 9

**Comment by blacktwin** [comment]
Seems like Tautulli and Plex are not in sync. Tautulli thinks there is a library with ID 9 but Plex says no. Any changes to your libraries? You may need to run this https://gist.github.com/JonnyWong16/f554f407832076919dc6864a78432db2

**Comment by blacktwin** [comment]
What do you see when you go to `http://TAUTULLI_IP:PORT/library?section_id=9` in Tautulli?

What do you see when you go to `https://app.plex.tv/desktop/#!/media/YOUR_SERVER_MACHINE_ID/com.plexapp.plugins.library?source=9`

**Comment by cyturralde** [comment]
Both of those pull up the correct corresponding libraries.

**Comment by cyturralde** [comment]
@blacktwin just curious if you had any other thoughts or ideas?

**Comment by cyturralde** [comment]
That seems to of fixed it. Thanks for all the help!

**Comment by dama-de** [comment]
I've just stumbled upon the same error. It still needs to be fixed in the repo.
