### ISSUE TITLE
Hide episode spoiler - Manual run and updated files

### ISSUE THREAD

**Issue by makkish** [blacktwin/JBOPS#371]
Hello!

I am running Plex as a service on a Debian VM and Tautulli in docker.

1.  Is it possible to manually run hide_episode_spoilers.py? I have a lot of episodes that were added before I started with this script. If possible, what command and do I need to run in inside Tautulli container?

2.  Is it possible for the script to run after an episode has been updated (eg. sonarr downloaded a proper)?

Thanks!

**Comment by blacktwin** [comment]
Yes.
