### ISSUE TITLE
[Request] Library Retention Policy Script

### ISSUE THREAD

**Issue by Desy10140** [blacktwin/JBOPS#373]
Improvement on Delete watched TV:
https://github.com/blacktwin/JBOPS/blob/master/utility/delete_watched_TV.py

The idea is a script that would automate a retention policy for your plex server via Tautulli, radarr and sonarr

Basic function:
If library item Hasn't been watched for X number of days
If Library item has NEVER been watched and is XX number of days since added
Then Delete file, Delete Plex renditions if they exist, remove from Radarr, Remove from Sonarr and unmonitor

Additional nice to have features:
- Run with a UI that shows library items found that will be deleted and allow the user to choose which items to delete
- Whitelist library items to never be deleted
- Whitelist library items in a playlist
- Only delete items based on file size to a total size deleted starting with oldest items first.
--- EX: Delete items found, starting with the oldest watched date but stop once sum of deleted files equal 1TB
- Run script based X remaining space in root folder
--- EX: If Root folder 1 is below 1TB free space, then run script.
- Ability to handle multiple drive pools and set retention limits on each pool independently
- Ability to set retention limits by Library

I've looked at Plex Cleaner but it's been abandoned. I've seen a few bespoke scripts but nothing that really talks to the larger ecosystem of apps.

**Comment by blacktwin** [comment]
[media_manager.py](https://github.com/blacktwin/JBOPS/blob/master/utility/media_manager.py) is the current improvement on the two deletion based on watch status scripts [TV](https://github.com/blacktwin/JBOPS/blob/master/utility/delete_watched_TV.py) and [movies](https://github.com/blacktwin/JBOPS/blob/master/utility/remove_watched_movies.py). I've been neglecting this project for awhile so I probably won't ever get to this one as it's very complex (gui and the use of more services).
