### ISSUE TITLE
Unable to pull ratings from section ID: 15

### ISSUE THREAD

**Issue by Nexius2** [blacktwin/JBOPS#374]
**Describe the bug**

when using plex_api_share.py --allLibraries (or anything using libraries) I have this error in result.
`Unable to pull ratings from section ID: 15`
with --backup, the json does seem to get all libraries
if I do plex_api_share.py --libraries [...] it show all libraries in the error invalid choice so I guess he can collect all libraries.
is there anyway to log or get more information to find the issue or what the code meens?
thanks

oh, and i would be nice to ba able to pass ULR and token via arguments also (useful when mutliple servers ;-) )
something like :

--url [ ...]
-- token [...]

parser.add_argument('--url', nargs='+', default=False, choices=sections_lst, metavar='',
                        help='Plex URL')
parser.add_argument('--token', nargs='+', default=False, choices=sections_lst, metavar='',
                        help='Plex token')

...

**Comment by blacktwin** [comment]
What is the entire error message?

**Comment by Nexius2** [comment]
Hello,
"Unable to pull ratings from section ID: 15" is the exact and only message.
it's from line 167. it's like I have a library with no rating.... something like that... but I can't know wich one or anything to check.

**Comment by blacktwin** [comment]
What is the entire error message?
