### ISSUE TITLE
[Request] Delete watched movie 

### ISSUE THREAD

**Issue by axelmvt** [blacktwin/JBOPS#376]
Would it be possible to have a similar script to [delete_watched_TV](https://github.com/blacktwin/JBOPS/blob/master/utility/delete_watched_TV.py) but for movies? I know about [remove_watched_movies](https://github.com/blacktwin/JBOPS/blob/master/utility/remove_watched_movies.py) but it deletes the entire library that I don't want. 

From a list of Movies, check if users in a list has watched the movie. If all users in list have watched it, then delete episode.

Thanks!

**Comment by blacktwin** [comment]
Use [media_manager ](https://github.com/blacktwin/JBOPS/blob/master/utility/media_manager.py)instead.
