### ISSUE TITLE
Kill after days (calender)

### ISSUE THREAD

**Issue by roand0617** [blacktwin/JBOPS#379]
Hello

I would like to know if there is a way to limit a user's plays after an estimated time, independent of the session time

I want a user to have access to the content for 30 days. So once I give it access I want to configure a script or counter that counts the 30 days, and after that time kills the reproductions made by the user. Even if the user in those 30 days only saw 2 hours of content, if the 30 days were up, make the limitation.

**Comment by blacktwin** [comment]
No.
