### ISSUE TITLE
Individual User Streams on Kill Streams

### ISSUE THREAD

**Issue by JamsRepos** [blacktwin/JBOPS#382]
**Is your feature request an improvement on an existing script? Please link to script.**
To add a new addition on to the "Limit User Streams to one Unique IP" to only check for that indivudual user, not all.
https://github.com/blacktwin/JBOPS/blob/master/killstream/kill_stream.py

**Is your feature request related to a problem? Please describe.**
This very well may be possible however i'm quite new to the Tautulli Scripts section, if this already exists through a condition then i'd love to know.

**Comment by blacktwin** [comment]
You would use the conditions to only run for one user.

![image](https://github.com/blacktwin/JBOPS/assets/22177672/eb872978-309b-451d-9a26-8aad917d086a)
