### ISSUE TITLE
[Request] Add/Remove "Allow Only Labels" and "Exclude Labels" on users

### ISSUE THREAD

**Issue by NaturalCarr** [blacktwin/JBOPS#383]
**Is your feature request an improvement on an existing script? Please link to script.**
https://github.com/blacktwin/JBOPS/blob/master/utility/plex_api_share.py
Greetings, I want to request the addition and removal of restrictions for users, specifically adding or removing "Allow Only Labels"and "Exclude Labels"

**Alternatives Tried**
I've considered doing this with completely separate libraries, but then adding media to them becomes more complicated than button presses through plex's gui (especially on TV)

**Additional context**
I like want to create some collections that I want to only share with specific users (ie "movies to watch with parents" and "movies to watch with gf"). As of now I'd need to assign a tag to my collection and go to every user and restrict that tag. Being able to automate that would save so much time.

**Comment by blacktwin** [comment]
You can already do this with label arguments. 
```python
  --movieLabels         Add label restrictions to movie library types
  --tvLabels            Add label restrictions to show library types
  --musicLabels         Add label restrictions to music library types
```

Well I guess I need to update the argument descriptions and the docstring. `--movieLabels label="movies to watch with parents"` to add/remove Allow Only Label or  `--movieLabels label!="movies to watch with parents"` to add/remove Exclude Label. `label="movies to watch with parents","movies to watch with gf"` comma separating multiple labels will add/remove multiple labels.

Check out this previous [issue](https://github.com/blacktwin/JBOPS/issues/336#issuecomment-1117694854).
