### ISSUE TITLE
merge_multiepisode.py causes Plex to show 2 dpulicate files for each merged episode.

### ISSUE THREAD

**Issue by lightmaster** [blacktwin/JBOPS#387]
**Describe the bug**

merge_multiepisodes.py - When running this script, for multiple episodes files, Plex now shows 2 identical files for each episode, causing a "2" to be displayed on each episode in some clients. I suspect that if there is a 3 part episode, it would then show 3 identical files for that episode instead.

**Provide logs**
[Plex server log](https://pastebin.com/Btaj0VEf)
[PlexAPI log](https://pastebin.com/bmcKkvUN)

**Link to script with bug/issue**
https://github.com/blacktwin/JBOPS/blob/master/utility/merge_multiepisodes.py

**To Reproduce**

1. Run merge_multiepisode.py
2. Click on "get info" for an episode that was merged
3. See 2 identical files under "Files"

**Expected behavior**
Episode descriptions and information should be merge, but the file should not be listed twice.

**Screenshots**
![image](https://github.com/blacktwin/JBOPS/assets/5307827/b82d604d-e31c-4fe6-9136-8b1274dd9a6a)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Python Version: 3.10.6
 - PlexAPI version: 4.14.0

**Additional context**

**Comment by JonnyWong16** [comment]
This is expected behaviour. That's just how Plex works when you merge entries together. There's no way around it.
