### ISSUE TITLE
Issue with sync_watch_status.py

### ISSUE THREAD

**Issue by boivinx7** [blacktwin/JBOPS#389]
Im sure im just missing something dumb

Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/root/snap/tautulli/common/Tautulli/Scripts/sync_watch_status.py", line 504, in <module>
            plexTo.append([user, check_users_access(plex_access, user, server_name, libraries)])
        File "/root/snap/tautulli/common/Tautulli/Scripts/sync_watch_status.py", line 337, in check_users_access
            for access in _user['access']:
    TypeError: 'NoneType' object is not subscriptable

**Comment by boivinx7** [comment]
welp yes was dumb

**Comment by checkerbomb** [comment]
What was the issue here? I'm running into the same thing.

**Comment by boivinx7** [comment]
I was not using it correctly

 sync_watch_status.py --userFrom USER1=Server1 --userTo USER2=Server1 --libraries Movies
 USER1 = usersname
 Server1 = name of the plex server
 
 I was doing something like 
 USER1=PlexMediaHome
 without changing the USER1 to a real value
