### ISSUE TITLE
[Request] Limiter to work on playlists.

### ISSUE THREAD

**Issue by XenoKie** [blacktwin/JBOPS#390]
For limiter, it doesn't seem to work on a playlist with multiple shows.
Every new show that plays, it would count as 0 watched unless the same show plays multiple times.
It would be nice if it would be possible to somehow register the episodes played to count towards the limit in a playlist by using the session ID.
In the attachments you can see that the episode count goes back to 0 when it plays a different show.
![Untitled1](https://github.com/blacktwin/JBOPS/assets/139071261/9046d925-a827-4cdd-9a55-1c014284789f)
![Untitled](https://github.com/blacktwin/JBOPS/assets/139071261/294d69bc-a080-4468-b744-5aa8c86406d3)

**Comment by blacktwin** [comment]
Sounds like this [example](https://github.com/blacktwin/JBOPS/blob/master/killstream/limiterr_readme.md#limit-user-to-total-playswatches-in-a-specific-library-movies) should work.

**Comment by XenoKie** [comment]
I am using this for the script, not sure what I am doing wrong. If their Playlist has multiple shows, it doesn't stop after 3 plays.
Do I use --jbop watch instead?

--jbop limit --username {username} --sessionId {session_id} --grandparent_rating_key {grandparent_rating_key} --limit plays=3 --delay 3 --killMessage "Are you still there?"
