### ISSUE TITLE
[Request] off_deck.py to have --action watch argument again

### ISSUE THREAD

**Issue by dezerving** [blacktwin/JBOPS#391]
**Is your feature request an improvement on an existing script? Please link to script.**

For this script: https://github.com/blacktwin/JBOPS/blob/master/utility/off_deck.py

I saw here https://www.reddit.com/r/PleX/comments/eqa7zu/comment/fepd95d/ that you can use` --action watch --shows {show_name}` to mark the episode as watched AND remove from continue watching.

**Is your feature request related to a problem? Please describe.**

I guess the script was redone a little while back and the argument --action watch was removed.

I was hoping it could be re-added whenever you get the time.

I requested some support on Tautulli discord however things can easily get lost there so I thought I'd open an issue on GH as well for tracking.

Thank you!

**Comment by blacktwin** [comment]
Added.
