### ISSUE TITLE
[More Settings Please?] Sorry for being a noob, instead of 2, how can I change it to 3 or more? 

### ISSUE THREAD

**Issue by daicain** [blacktwin/JBOPS#40]
Hi, If I wanted to change from the current 2 concurrent stream to like 3, where would I do that?

Maybe it'd be nice to add that as one of the settings?
## EDIT THESE SETTINGS ##
PLEX_TOKEN = 'xxxxx'
PLEX_URL = 'http://localhost:32400'
**CON_CURRENT_STREAM = 3**

Also, I've set this up the way the script says, but I cannot find 
PlexPy > Settings > Notification Agents > Scripts > Gear icon:
        **Playback User Concurrent Streams**: kill_more_than.py

As for the log, it shows this : 

> from plexapi.server import PlexServer
> ImportError: No module named plexapi.server

**Comment by blacktwin** [comment]
You'd need to install plexapi.  Check the readme.md. 

Concurrent stream trigger is set in plexpy not the script.
