### ISSUE TITLE
Sync_watch_status =/= Plex token

### ISSUE THREAD

**Issue by tchirou** [blacktwin/JBOPS#400]
Hi

On 2 different tautulli instances on 2 differents servers in countries apart, I have had a problem for the past few weeks with an error, whereas it has worked flawlessly for months before that

I updated the tokens but to no effect

Here is the log of one of them (they are the same on the 2 servers) : 

`Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/home/xxxxx/scripts/sync_watch_status.py", line 435, in <module>
            plex_admin = Plex(PLEX_TOKEN)
        File "/home/xxxxx/scripts/sync_watch_status.py", line 198, in __init__
            self.account = MyPlexAccount(token)
        File "/home/xxxxx/plexpy/lib/plexapi/myplex.py", line 122, in __init__
            data, initpath = self._signin(username, password, code, remember, timeout)
        File "/home/xxxxx/plexpy/lib/plexapi/myplex.py", line 135, in _signin
            data = self.query(self.SIGNIN, method=self._session.post, data=payload, timeout=timeout)
        File "/home/xxxxx/plexpy/lib/plexapi/myplex.py", line 241, in query
            raise BadRequest(message)
    plexapi.exceptions.BadRequest: (400) bad_request; https://plex.tv/api/v2/users/signin <?xml version="1.0" encoding="UTF-8"?> <errors> <error code="1004" message="password is missing" status="400"/> </errors>`

Maybe a plex update broke it ? tested on 1.32.5.7349 and 1.32.5.7516 

Anyone else has an issue ?

Thanks a lot

**Comment by saitoh183** [comment]
Same issue

**Comment by saitoh183** [comment]
@tchirou Copy config.ini in the repo to ~/.config/plexapi/config.ini
Make sure you fill in the info

**Comment by tchirou** [comment]
Hi
I created the folder plexapi in tautulli, added the config.ini and filled the info
Removed the info from sync_watch_status.py so it can pick up the config.ini

No I have 
`Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/config/sync_watch_status.py", line 75, in <module>
            PLEX_TOKEN = CONFIG.data['auth'].get('server_token')
                                      ~~~~~~~~~~~^^^^^^^^
    KeyError: 'auth'`

I checked the token and it is the right one

Thanks for the help though :-)

**Comment by saitoh183** [comment]
> Hi I created the folder plexapi in tautulli, added the config.ini and filled the info Removed the info from sync_watch_status.py so it can pick up the config.ini
> 
> Now I have `Tautulli Notifiers :: Script error: Traceback (most recent call last): File "/config/sync_watch_status.py", line 75, in <module> PLEX_TOKEN = CONFIG.data['auth'].get('server_token') ~~~~~~~~~~~^^^^^^^^ KeyError: 'auth'`
> 
> I checked the token and it is the right one
> 
> Thanks for the help though :-)

Have you tried to run the script manually outside of tautulli? if you add the plex token to the script directly, does it give the same error?

**Comment by tchirou** [comment]
No I haven’t tried outside of Tautulli 
The plex token directly in the script is how I have used successfully the script for months and then it started to give the error I wrote in the first post

**Comment by tchirou** [comment]
Would anyone have an idea of what is going on ? I just spent 2 hours trying to fix this but it still doens't work :-(

**Comment by tchirou** [comment]
The log is here : https://gist.github.com/tchirou/b7ea7755dc927dcca35b511d3191d295

When I use config.ini, the error is 
`  Traceback (most recent call last):
    File "/config/plexapi/sync_watch_status.py", line 75, in <module>
      TAUTULLI_URL = CONFIG.data['auth'].get('tautulli_baseurl')
                     ~~~~~~~~~~~^^^^^^^^
  KeyError: 'auth'`

When I write the info directly in the file, the error is
`  Traceback (most recent call last):
    File "/config/plexapi/sync_watch_status.py", line 459, in <module>
      plex_admin = Plex(PLEX_TOKEN)
                   ^^^^^^^^^^^^^^^^
    File "/config/plexapi/sync_watch_status.py", line 198, in __init__
      self.account = MyPlexAccount(token)
                     ^^^^^^^^^^^^^^^^^^^^
    File "/app/tautulli/lib/plexapi/myplex.py", line 124, in __init__
      data, initpath = self._signin(username, password, code, remember, timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/app/tautulli/lib/plexapi/myplex.py", line 137, in _signin
      data = self.query(self.SIGNIN, method=self._session.post, data=payload, timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/app/tautulli/lib/plexapi/myplex.py", line 245, in query
      raise BadRequest(message)
  plexapi.exceptions.BadRequest: (400) bad_request; https://plex.tv/api/v2/users/signin <?xml version="1.0" encoding="UTF-8"?> <errors>   <error code="1004" message="password is missing" status="400"/> </errors> `

**Comment by tchirou** [comment]
The author answered on discord 

Here : https://github.com/blacktwin/JBOPS/blob/master/utility/sync_watch_status.py#L198C48-L198C48 

This 
`class Plex(object):
    def __init__(self, token, url=None):
        if token and not url:
            self.account = MyPlexAccount(token)`

Must be replaced by 
`class Plex(object):
    def __init__(self, token, url=None):
        if token and not url:
            self.account = MyPlexAccount(token=token)`

And now i works beautifully as before
