### ISSUE TITLE
Migrate Transcodes to Backup Server

### ISSUE THREAD

**Issue by baadsha007** [blacktwin/JBOPS#414]
Is it feasible to create a script that could transfer all transcoding streams to a backup server? I have a secondary server that is more efficient in transcoding, and it would be beneficial if such a script existed.

**Comment by blacktwin** [comment]
I think you're asking for load balancing? I think. If so, no. Plex isn't designed to operate in that way. If you have a secondary server then use it for you Plex server or have it run optimization/conversion of whatever files would be transcoding and have them stored for your primary Plex server to access as different Versions (versions being different quality profiles).

**Comment by baadsha007** [comment]
Sorry, not load balancing. Essentially, if a stream has the video decision of transcode, then the stream is started on a secondary server.
