### ISSUE TITLE
plexapi_haiku_movies.py chokes on titles with numbers

### ISSUE THREAD

**Issue by vinfam** [blacktwin/JBOPS#45]
Examples:

ring one begins in
runner 2009 hotel stop affairs
for 2 spirited

country infernal
on casablanca the world
away 101 king bourne

bad park good morty
call saul the sherlock bad good
sherlock trek 2017 humans

Maybe add an option to blacklist numbers and titles that include II or III ?

**Comment by blacktwin** [comment]
Ok I've updated it. Not sure if "I" will show up or not now. Numbers and Romans for now omitted.
