### ISSUE TITLE
JBOPS/killstream/wait_kill_pause_notify_main.py - Error Import Request

### ISSUE THREAD

**Issue by Laronski** [blacktwin/JBOPS#50]
My Tautulli reports errors with **wait_kill_pause_notify_main.py**.

Log reports:
	Tautulli Notifiers :: Script error: 
    Traceback (most recent call last): 
        File "c:\PlexPy\wait_kill_pause_notify_main.py", line 23, in <module> 
            import requests 
    ImportError: No module named requests

**Comment by blacktwin** [comment]
You'll need to install the requests module. `pip install requests`
