### ISSUE TITLE
notify_added_custom.py AttributeError: 'NoneType' object has no attribute 'added_at'

### ISSUE THREAD

**Issue by fkick** [blacktwin/JBOPS#52]
After updating to Tautulli release version, This error is being generated by your notify_added_custom.py:

```
$ /usr/bin/python /Applications/Tautulli/Scripts/notify_added_custom.py -t art -d 7
Sending email(s) to redacted@email.com
PlexPy API 'get_metadata' request failed: 'metadata'.Traceback (most recent call last):
  File "/Applications/Tautulli/Scripts/notify_added_custom.py", line 341, in <module>
    build_parts = [build_html(rating_key, height, width, opts.type) for rating_key in sorted(rating_keys_lst)]
  File "/Applications/Tautulli/Scripts/notify_added_custom.py", line 204, in build_html
    added = time.ctime(float(meta.added_at))
AttributeError: 'NoneType' object has no attribute 'added_at'
```

Thanks

**Comment by blacktwin** [comment]
I'm in the process of updating all the scripts to better work with Tautulli. Try this one. https://github.com/blacktwin/JBOPS/blob/tautulli-update/notify/notify_added_custom.py

**Comment by jstrollo17** [comment]
I'm getting the same error with the file you just posted.  I'm wondering if I have the wrong PLEXPY_APIKEY defined.  I'm not really 100% sure where this comes from though.  This is my first stab at using scripting with PlexPy/Tautulli.

**Comment by fkick** [comment]
That solved my issue. I'm able to pull metadata again and send emails. Thanks
