### ISSUE TITLE
Requests Module isn’t found

### ISSUE THREAD

**Issue by thamilton91** [blacktwin/JBOPS#67]
Hey this has been driving me nuts, I definitely have requests installed, have you see this before? I’m sure it’s something simple I’m missing. 

Tautulli Notifiers :: Script error: 
    Traceback (most recent call last): 
        File "/opt/Tautulli/scripts/kill_a_stream.py", line 7, in <module> 
            import requests 
    ImportError: No module named requests

**Comment by thamilton91** [comment]
import sys
import requests
from plexapi.server import PlexServer

**Comment by thamilton91** [comment]
root@login:~# python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.__version__
'2.18.4'
>>> 

I’m also confirming that it’s installed

**Comment by thamilton91** [comment]
>> root@login:~# python
>> Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
>> [GCC 5.4.0 20160609] on linux2
>> Type "help", "copyright", "credits" or "license" for more information.
>> import requests
>> requests.__version__
>> '2.18.4'

**Comment by blacktwin** [comment]
What is Tautulli running in? Docker?
