### ISSUE TITLE
PLEX_URL Guidance

### ISSUE THREAD

**Issue by unamundan** [blacktwin/JBOPS#69]
For Line 39:

plex = PlexServer(PLEX_URL, PLEX_TOKEN, session=sess)

What format is expected in PLEX_URL? And, should it be LAN or WAN IP? I’m guessing WAN, since localhost and XXX.XXX.XXX.XXX LAN IP failed.

**Comment by blacktwin** [comment]
If you are running the script on the same machine as Plex then `PLEX_URL = 'http://localhost:32400'`.
