### ISSUE TITLE
Issue with 'Kill Paused Streams'

### ISSUE THREAD

**Issue by clovisd** [blacktwin/JBOPS#72]
Hey! I'm getting the following error:
```2018-05-31 16:16:53 - INFO :: Thread-2 : Tautulli NotificationHandler :: Preparing notifications for notifier_id 11.
2018-05-31 16:16:53 - DEBUG :: Thread-2 : Tautulli Notifiers :: Trying to run notify script, action: test, arguments: u'3', u'Clovis', u'For the Birds', u'600', u'20'
2018-05-31 16:16:53 - DEBUG :: Thread-2 : Tautulli Notifiers :: Full script is: ['python', u'/home/scripts/plexpy/wait_kill_paused_notify.py', 'u3,', 'uClovis,', 'uFor the Birds,', 'u600,', 'u20']
2018-05-31 16:16:53 - DEBUG :: Thread-2 : Tautulli Notifiers :: Executing script in a new thread.
2018-05-31 16:16:53 - ERROR :: Thread-18 : Tautulli Notifiers :: Script error:
  Traceback (most recent call last):
    File "/home/scripts/plexpy/wait_kill_paused_notify.py", line 48, in <module>
      from plexapi.server import PlexServer
  ImportError: No module named plexapi.server
```

I updated the script to include the URL to my PLEX server as well as the token. 

Plex Version: 1.13.2.5102
Tautulli Version: 2.1.9

Running on Linux Ubuntu 18.04.

Any help or pointers would be appreciated!

Thanks,
C

**Comment by Foebik** [comment]
I'm having a similar issue with using the "kill_more_than.py" script.

```
Tautulli Notifiers :: Script error: 
    Traceback (most recent call last): 
        File "C:\plexpy\scripts\kill_more_than.py", line 16, in <module> 
            from plexapi.server import PlexServer 
    ImportError: No module named plexapi.server
```

**Comment by McGriddle** [comment]
Maybe a dumb question, but you have installed plexapi? `pip install plexapi`

**Comment by Foebik** [comment]
Not a dumb questions. Just a dumb user, I didn't know that was a thing. Let me work on it and come back.

**Comment by Foebik** [comment]
Well, that fixed my error installing that. But the script isnt working as expect now. Kills all concurrent streams. Not just the ones that have a different IP.

My idea using this stream is to help kill account sharing. I dont care if they have several streams from the same locations. Or even a new stream on a different IP. I just dont want 2 concurrent streams at the same time from different IPs.

**Comment by blacktwin** [comment]
@foebik there should be a script that fits your request. Which script were you using? Can you provide a link?

**Comment by Foebik** [comment]
Yep, that is the one I'm trying to get working(kill_more_than.py). And technically it is working. But it is also killing concurrent streams on the same IP. I know it must be something I did wrong, just haven't figured it out yet.

**Comment by Foebik** [comment]
Just to clarify, this is my current settings. I think I got them mostly right. The directions in the script and the naming convention within Tautulli seem to have change slightly.

![image](https://user-images.githubusercontent.com/6633492/40846715-62c4a4f2-6588-11e8-9999-2870c048c617.png)
![image](https://user-images.githubusercontent.com/6633492/40846737-72c1cede-6588-11e8-8054-d488e5814118.png)
![image](https://user-images.githubusercontent.com/6633492/40846761-8408772e-6588-11e8-8405-ff4e221e7b8f.png)

**Comment by blacktwin** [comment]
@Foebik looks good. Can you post your logs to a gist and link it? 

>How to Find Your Logs
>View the Tautulli logs by clicking on "View Logs" in the settings menu. Click the "Download logs" button to save a copy of the log file. If Tautulli is unable to start, then the tautulli.log file is located in the logs folder where Tautulli is installed. Paste the logs on Gist and post the link here, do not upload the file as an attachment.

**Comment by Foebik** [comment]
Yep, I'll do it a bit later tonight when my user use slows down. Don't want to start booting people yet until I figure this out. Thanks in advance.

**Comment by Foebik** [comment]
I tried to clear the logs data between tries to keep it clean. There are two logs. One with one client on the local network and the other on cellular data. The other were they are both on the local network. Both had the same result of the last one to stream got ended.

https://gist.github.com/Foebik/0d2399db39c8d9d6f7240989394a46cb

**Comment by clovisd** [comment]
Ok, other than the fact that this got side tracked on a different script, @McGriddle was right and all I had to do was install `pip install plexapi` and it's working now. 💯

**Comment by blacktwin** [comment]
@Foebik 

Add your username to the ignore list in the script or create a condition of `username | is not | me` or `Stream Local | is | 1` or `Stream Location | is | local` . You're interested in other people sharing their account. Not you sharing your account.

**Comment by blacktwin** [comment]
@clovisd I used the [readme](https://github.com/blacktwin/JBOPS#jbops---just-a-bunch-of-plex-scripts) to list the most commonly used modules. I plan on using a requirements.txt eventually.

**Comment by blacktwin** [comment]
@Foebik 
How are you testing? Are you using two clients on the same machine (2x chrome)? If you are testing with two different clients on different machines (1 roku, 1 chrome) then the IPs will be different.

Use a print [here ](https://github.com/blacktwin/JBOPS/blob/master/killstream/kill_more_than.py#L54-L56)to determine what IPs are being collected. 
```python
    print(userip_sessions) #<--- this
    if len(user_sessions) >= 2 > len(userip_sessions):
        for session in user_sessions:
```

**Comment by Foebik** [comment]
I didn't even think of that. I was testing on my phone using data and a local system. I was thinking of how it would be for a remote user I was testing for. But a remote user would only come over as 1 IP (external) even if they had multiply internal IPs. But because my server is also internal it sees the internal IPs locally. So maybe you are correct and my testing method was flawed. I guess I can only wait and see if someone else tries to do it and see what happens.

In the mean time I updated my ignore list so it dont get kicked off ;) - Thanks
