### ISSUE TITLE
kill_trans_library.py - playing a "duplicate" movie triggers kill

### ISSUE THREAD

**Issue by mescon** [blacktwin/JBOPS#73]
I have blocked transcodes from a 4K library with library ID 25.
The movie in question is also available in a 1080p library with library ID 12.

When a user starts playing something in library ID 12, the trigger sent from Tautulli is:
``'python', u'/opt/JBOPS/killstream/kill_trans_library.py', u'12', u'25'``
Notice it sends both ID 12 and ID 25.
This is because the movie in question is available in both the 1080p library (where I want to allow transcodes) AND in the 4K library (where I do not want to allow transcodes).
Users are therefore kicked out, even though they are only transcoding a 1080p movie.

**Comment by blacktwin** [comment]
`u'12', u'25'`
```
Tautulli > Settings > Notifications > Script > Script Arguments:
        {section_id} {session_key}
```
Your section_id is 12 and you session_key is 25.
