### ISSUE TITLE
kill_stream error --jbop is required

### ISSUE THREAD

**Issue by Qwatuz** [blacktwin/JBOPS#75]
Trying to set up kill_stream.py and am running into this error:

```

Tautulli Notifiers :: Script error: 
    usage: kill_stream.py [-h] --jbop {stream,allStreams} [--userId USERID] 
                                                [--username USERNAME] --sessionId SESSIONID 
                                                [--killMessage KILLMESSAGE [KILLMESSAGE ...]] 
                                                [--notify NOTIFY] 
    kill_stream.py: error: argument --jbop is required

Tautulli Notifiers :: Full script is: ['python', u'/home/user/data/.Automation/scripts/kill_stream.py']

```

Is there something I forgot to configure?

**Comment by seanvree** [comment]
Yeah, same question here as well.

**Comment by blacktwin** [comment]
I've updated the killstream section's [readme](https://github.com/blacktwin/JBOPS/tree/master/killstream#kill_streampy-examples) with examples. 

I was hoping that the `--jbop` would output the available choices. Basically, it's `stream`: kill single stream or `allStreams`: kill all of the offending user's streams.

**Comment by seanvree** [comment]
@blacktwin  just tested, works great. One more question  - is there a way to set a "wait" period before killing the stream like in the previous "wait_kill_paused_notify" scripts?

**Comment by blacktwin** [comment]
@seanvree not yet. The "wait_kill_paused_notify" script will be kept as is due to it's complexity, but it may eventually get rolled in. I'm thinking about combining the limit* scripts into one as well.

**Comment by seanvree** [comment]
@blacktwin got it. Thanks sir.

**Comment by blacktwin** [comment]
@Qwatuz you good too?

**Comment by Qwatuz** [comment]
It works but not every time - the error is still popping up in the logs even with a successful kick, is this normal?

```
Tautulli Notifiers :: Script error: 
    usage: kill_stream.py [-h] --jbop {stream,allStreams} [--userId USERID] 
                                                [--username USERNAME] --sessionId SESSIONID 
                                                [--killMessage KILLMESSAGE [KILLMESSAGE ...]] 
                                                [--notify NOTIFY] 
    kill_stream.py: error: argument --jbop is required
```
These are what I have for the settings:

Playback Start/Resume ticked in triggers

https://i.imgur.com/0Oxzu8j.png
https://i.imgur.com/05T750e.png

Appreciate the help! :)

**Comment by blacktwin** [comment]
Can you post your logs?
>View the Tautulli logs by clicking on "View Logs" in the settings menu. Click the "Download logs" button to save a copy of the log file. If Tautulli is unable to start, then the tautulli.log file is located in the logs folder where Tautulli is installed. Paste the logs on Gist and post the link here, do not upload the file as an attachment.

**Comment by Qwatuz** [comment]
Here we go: https://pastebin.com/6Vd8PGfN

I tested the movie Virus which was successfully kicked due to transcoding, and the second movie I tried was Jurassic Park which was not kicked for transcoding.

**Comment by blacktwin** [comment]
@Qwatuz The notifierID for `--notify` is for a notification agent that actually sends a notification out like email, discord, etc. Its not supposed to the notifierID of the script agent you've created. If you don't want to send a message out then just omit the `--notify` arg. Lets start with that.
