### ISSUE TITLE
Q/Feat request:  Define how long the Kill message appears (create_wait_kill_trans)

### ISSUE THREAD

**Issue by seanvree** [blacktwin/JBOPS#8]
Loving create_wait_kill_trans man, great job. 

So, I noticed when the Kill message "REASON" is displayed on the client device, the message actually only appears for a split second. Like, not even long enough to ready it.  

 Is it designed that way? Is it configurable?  

 Or, is it maybe it's my rig?

thanks buddy!

p.s.  sorry for all the issues man.  Just trying to debug!

**Comment by blacktwin** [comment]
@seanvree I think it depends on the client. For Roku the user needs to click/select OK to remove the message. On the newly released web player (3.17.2) the user would need to click outside the message window or the X in the window to move past the message. I'm not sure if the web player behavior is new, I can't remember. 

Which client are you referring to?

**Comment by seanvree** [comment]
I've tested on a sumsung TV and a Samsung mobile device.

**Comment by blacktwin** [comment]
@seanvree just tested on my Note 4. Same as what I described above. Clicking outside the message window or X or OK closes the message.

**Comment by seanvree** [comment]
@blacktwin 

humm, gotcha, yeah, the Samsung TV and webclient it just disappears automatically after a split second. 

First world problems. 

Thanks for looking into it!
