### ISSUE TITLE
kill_more_than.py is gone?

### ISSUE THREAD

**Issue by keithah** [blacktwin/JBOPS#83]
When I click on the link in the main repo, it 404's.

**Comment by blacktwin** [comment]
All the kill_stream scripts have been combined into one [`kill_stream.py`](https://github.com/blacktwin/JBOPS/blob/master/killstream/kill_stream.py).  See examples for how to mimic you [kill_more_than.py](https://github.com/blacktwin/JBOPS/tree/master/killstream#limit-user-stream-count-kill-last-stream)

**Comment by blacktwin** [comment]
I need to clean up the main readme.md. Lots of links are broken and newer scripts are not listed.

**Comment by blacktwin** [comment]
Cleaned up Killstreams section of the readme.
