### ISSUE TITLE
kill_stream.py - Not working for second stream kill.

### ISSUE THREAD

**Issue by deepwather** [blacktwin/JBOPS#84]
Hello Guys,
I am using your "kill_stream.py" script, to block the ability to have more than one stream per user.
When I tested the script, I saw, that it is just working once.... Why? -> If I immediately restart the auto-killed stream on the second device, neither of the both streams are killed anymore. -> The two Concurrend streams are untouched the second time. _(First stream is running the whole time. / second killed just once.)_

**My Taultulli configuration:** 
Taultulli > Settings > Notification Agents > New Script > Configuration:
> Script Folder: /opt/scripts/  |  Script File: ./kill_stream.py  |  Script Timeout: 0

Taultulli > Settings > Notification Agents > New Script > Triggers:
> Ticked: Playback Start

Taultulli > Settings > Notification Agents > New Script > Conditions:
> Condition 1:  ->> "User Streams"  /   "is greater than"  /  "1"

Taultulli > Settings > Notification Agents > New Script > Arguments:
> Playback Start:  --jbop stream --username {username} --sessionId {session_id} --killMessage 'You are only allowed to have one stream.'

cheers deepwather

**Comment by blacktwin** [comment]
Logs please. View the Tautulli logs by clicking on "View Logs" in the settings menu. Click the "Download logs" button to save a copy of the log file. If Tautulli is unable to start, then the tautulli.log file is located in the logs folder where Tautulli is installed. Paste the logs on Gist and post the link here, do not upload the file as an attachment.
