### ISSUE TITLE
Showing rating for tv show delete

### ISSUE THREAD

**Issue by phairplay** [blacktwin/JBOPS#90]
Hi I'm wanting to use your script to monitor tv shows I have for a family member that I don't want to keep once they have watched it. I've come across your script but I can't to seem to find where the show rating key is.

Could You please point me in the right direction

Many thanks

**Comment by blacktwin** [comment]
Which script? For shows there are 3 levels Show (grandparent_rating_key), Season (parent_rating_key), and Episode (rating_key). In a web browser click on the Show to get the grandparent_rating_key, click on a Season for the parent_rating_key, or click an Episode to the the rating_key. Here is an example of the [grandparent_rating_key](https://i.imgur.com/ezdCkQb.png). The 90153 in `metadata%2F90153` is the grandparent_rating_key. That number will change to whatever level of the show you're in. Does that help?

**Comment by phairplay** [comment]
Hi
Yes this was super helpful thank you.
