### ISSUE TITLE
kill_stream.py not terminating stream Script error Line 70

### ISSUE THREAD

**Issue by marcel5454** [blacktwin/JBOPS#92]
Here's the log

> 2018-09-03 16:20:49 - INFO    :: CP Server Thread-8 : Cleared the tautulli.log file.
> 2018-09-03 16:21:09 - DEBUG   :: Thread-3 : Tautulli ActivityHandler :: Session 102 started by user xxx (xxx) with ratingKey 9587 (Summer with Monika).
> 2018-09-03 16:21:09 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Checking custom notification conditions for notifier_id 4.
> 2018-09-03 16:21:09 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Custom condition evaluated to 'True'. Conditions: [True, False].
> 2018-09-03 16:21:09 - INFO    :: Thread-2 : Tautulli NotificationHandler :: Preparing notification for notifier_id 4.
> 2018-09-03 16:21:09 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Trying to run notify script, action: play, arguments: [u'--jbop', u'stream', u'--username', u'xxx', u'--sessionId', u'xxx', u'--killMessage', u"'Transcoding", u'streams', u'are', u'not', u"allowed.'"]
> 2018-09-03 16:21:09 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Full script is: ['python', u'xxx/plexpy/scripts/kill_stream.py', u'--jbop', u'stream', u'--username', u'xxx', u'--sessionId', u'xxx', u'--killMessage', u"'Transcoding", u'streams', u'are', u'not', u"allowed.'"]
> 2018-09-03 16:21:09 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Executing script in a new thread.
> 2018-09-03 16:21:10 - ERROR   :: Thread-43 : Tautulli Notifiers :: Script error: 
>   Traceback (most recent call last):
>     File "xxx/plexpy/scripts/kill_stream.py", line 70, in <module>
>       urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
>   AttributeError: 'module' object has no attribute 'disable_warnings'
> 2018-09-03 16:21:47 - DEBUG   :: Thread-3 : Tautulli ActivityHandler :: Session 102 stopped.
> 2018-09-03 16:21:47 - DEBUG   :: Thread-3 : Tautulli ActivityProcessor :: Play duration for session 102 ratingKey 9587 is 38 secs which is less than 180 seconds, so we're not logging it.
> 2018-09-03 16:21:47 - DEBUG   :: Thread-3 : Tautulli ActivityHandler :: Removing sessionKey 102 ratingKey 9587 from session queue

**Comment by blacktwin** [comment]
Can you confirm that these scripts are running with python 2.7 and not python 3?
