### ISSUE TITLE
Delete watched issues

### ISSUE THREAD

**Issue by phairplay** [blacktwin/JBOPS#93]
hi,
could you please help me with a few issues?

1,
for some reason the script isn't detecting all the watched shows and deleting them.
https://imgur.com/a/sSqssml
as you can see from the above
_The Writing on the Wall
What We Want To Be
Thanksgiving in Dallas
The Edge_
have all been watched yet it only deleted
_Happy Halloween_
https://imgur.com/a/96SNNOD
here is also the files
https://imgur.com/a/6aN7dnu

is there something i'm doing wrong?

2, i set this up to run once Barry has stopped watching something, yet it doesn't see to work
https://imgur.com/a/vvuHssi

i would really appreciate any help

**Comment by blacktwin** [comment]
Assuming you're talking about this [script](https://github.com/blacktwin/JBOPS/blob/master/utility/delete_watched_TV.py)? Do not run it via Tautulli, instead run it from a cmd/terminal or double click. Set your `USER_LST` for all the user that have to have watched the shows. If you have a name in that list that hasn't watched the show then it will not delete the show/episode. Lets start there.

**Comment by phairplay** [comment]
Yes this is the script.
Barry Is the only user in the script and all or nothing Is the only show bring tracked.

Yet it hasn't deleted all the shows he watched. 
I have it set up to run once something has Barry stops watching something,

**Comment by blacktwin** [comment]
> I have it set up to run once something has Barry stops watching something,

Run it manually via cmd or terminal.

**Comment by phairplay** [comment]
I did in the snap shot (in my first post) and it didn't delete all the eps within the show that had been watched.
Also in the command imgur it states two shows as being watched, yet only deletes one.

**Comment by blacktwin** [comment]
Try now.
