### ISSUE TITLE
Remove from Trakt watchlist when downloaded to PLEX

### ISSUE THREAD

**Issue by tjurczyk** [blacktwin/JBOPS#95]
Hey,

thanks for sharing your scripts! I have a use case that is still not available in the official trakt plex plugin. I would like to remove movies from my trakt watchlist once they land in my PLEX.
Do you consider adding a script like this?

Thanks!

**Comment by blacktwin** [comment]
This is very old and I don't use Trakt. I believe there are other projects that do this. Sorry, I'm closing this.
