### ISSUE TITLE
Installation instructions don't implicitly state that Tautulli API has to be enabled in order for killstream to work.

### ISSUE THREAD

**Issue by Daedilus** [blacktwin/JBOPS#97]
Took me awhile to realize that for the killstream script to work properly you must enable the Tautullli API under Settings -> Web Interface -> API.

I know it's silly and obvious with 20/20 hindsight but for some people it would be difficult to troubleshoot why your script isn't working for them.

**Comment by blacktwin** [comment]
Added to the readme, thanks.
